### ISSUE TITLE
Non-roman characters not displaying in page_header/page_footer tags

### ISSUE THREAD

**Issue by goulvench** [spipu/html2pdf#1]
I am generating a document in several languages (including Japanese, Chinese, Korean, Thai, but also Greek, Polish and more). All characters display properly in the document except when they appear in page_header or page_footer tags, where they get replaced by question marks.
I've confirmed that these characters display properly when replacing `<page_header>` and `<page_footer>` tags with ordinary `<div>`s.

I've been trying to find a fix for this for hours with no success at all unfortunately.

Here is the code I'm using to initialize the library:
`$pdf = new HTML2PDF('P', 'A4', 'en', true, 'UTF-8', array(14, 14, 14, 12));`
I'm using Arial Unicode MS to make sure that TCPDF uses the proper font, as described on several forums: 
`$pdf->setDefaultFont('arialunicid0');`

As you can see on the screenshot below, all characters are properly displayed on the page, but not in the header.
![japanese characters not displaying in header](https://cloud.githubusercontent.com/assets/419086/5834480/6c144ad6-a15e-11e4-8118-909e8443c0c6.png)

Thanks for the great library by the way!

**Comment by goulvench** [comment]
I hacked around and found the same problem in TCPDF: the header/footer font is Arial, even when declaring Arial Unicode as a default font for the whole document.

I'll submit a patch for HTML2PDF and TCPDF as soon as I have something clean.

**Comment by nhantam** [comment]
I have same problem. How do I show japanese on pdf ?

Thanks & Regards
