### ISSUE TITLE
Error with dependencies with 4.5.1 (but OK with 4.4.0)

### ISSUE THREAD

**Issue by mattheoh** [spipu/html2pdf#103]
Hi,
I have this error when I use HTM2PDF 4.5.1
[ERROR]
         It seems that HTML2PDF dependencies are not installed...
         you must install thems with `composer install`

When I replac with the previous version 4.4.0, everything is OK.
I m on a Debian 8 server, PHP 5.6.
Not a big deal ... it's just to let you know !

**Comment by juchi** [comment]
Hi,
This is perfectly normal. In order to correctly manage dependencies, html2pdf uses composer since version 4.5. You can install the project by following the instructions in the readme file.

**Comment by mattheoh** [comment]
Thanks for the information.
I didn't understand this point...
That means it will be more complicated for someone who has a share hosting to be able to use html2pdf ... :-( right ? Cause you need to install compozer at a server level.

**Comment by spipu** [comment]
No.

You have just to prepare you delivery package on your computer, and then send it to your server. You have not to install Composer on your production server.

**Comment by mattheoh** [comment]
OK, perfect. Thanks a lot.
I m going to look forward into it. You can close the issue.
Have a nice week-end.
