### ISSUE TITLE
Bootstrap css integration

### ISSUE THREAD

**Issue by AEK-BKF** [spipu/html2pdf#104]
Hi
First of all thank you so much for this nice package.
I want to say that I have a " dream " :D that soon, we can integrate bootstrap css ^^ this is very important for most apps web
Thanks :)))

**Comment by spipu** [comment]
It will never be possible : responsive does not exist on PDF...

and as it is written on the html homepage : This library has been made to assist in the creation of PDF files, not to directly convert an HTML page. You can not use the <html>, <head>, <body> tags. Read carefully the examples.
