### ISSUE TITLE
Exception - ERROR n°6  Unable to load image

### ISSUE THREAD

**Issue by atlantisUnity** [spipu/html2pdf#110]
Hello , here I have this error that appears, I tried to solve it but not here is the code of my img tag :

img src="http://moodle-dev.dinf.cll.qc.ca/pluginfile.php/45/mod_ouwiki/content/46/ch%20gene.jpg" height="237" width="725" alt="ch%20gene.jpg"

**Comment by juchi** [comment]
Hi,
You needed authentication in order to view the image, so Html2Pdf cannot retrieve it as it cannot authenticate itself. You need to make the image accessible without authentication or read it from your filesystem.

**Comment by atlantisUnity** [comment]
Thank you for your answer, I go tried to find a solution to this problem.
