### ISSUE TITLE
Removing page format limitations

### ISSUE THREAD

**Issue by bestdamnfriend** [spipu/html2pdf#111]
Is it possible to remove the page format limitations, so the PDF just creates a document page as long as required dynamically? I have some images that are longer than A4 that I would like to display on one page, and then Adobe's software to "fit" the image to a page size of the user's choosing. Currently I'm having to splice the image into two separate PDFs, with one on page 1 and one on page 2.

**Comment by spipu** [comment]
PDF is for paper... unlimited paper does not exist....
