### ISSUE TITLE
Damaged pdf

### ISSUE THREAD

**Issue by patlaci** [spipu/html2pdf#112]
Generating a pdf from the sample_not_ok.html file will produce a damaged pdf ( sample_not_ok.pdf ). But with the sample_ok.html for example there is no problem at all ( sample_ok.pdf ) although the difference between the two html is only one character ( . vs , ). Can you fix this problem please? Thanks

[sample.zip](https://github.com/spipu/html2pdf/files/260969/sample.zip)

**Comment by juchi** [comment]
Hi,

Are you trying to generate the PDF from the exact html provided in your file? You're not supposed to include the whole html page, only the content of the body tag, as specified in the doc.
I tried to generate a pdf from your files with only the body content and it worked fine. Could you try again this way?

**Comment by spipu** [comment]
Other point : what is the used version of html2pdf? And what do you mezn with "damaged" ?

**Comment by patlaci** [comment]
Thanks for your answers. Finally we found the problem: there was a bug in our system which in some cases made a broken file from the correct pdf generated by html2pdf. So the html2pdf worked perfectly, I'm sorry to wasting your time.

Anyway the only-the-content-of-the-body-tag info was useful.

**Comment by juchi** [comment]
You are welcome.
