### ISSUE TITLE
Fixed a bug

### ISSUE THREAD

**Issue by atlantisUnity** [spipu/html2pdf#113]
Hello, here is I come to subject(submit) you a bug which I have to notice, I am sorry but I do not remember any more this bug but in any case to correct him(it) it is necessary to import these files in htlm2pdf.php

`require_once(dirname(__FILE__).'/_class/locale.class.php');
require_once(dirname(__FILE__).'/_class/myPdf.class.php');
require_once(dirname(__FILE__).'/_class/exception.class.php');
require_once(dirname(__FILE__).'/_class/parsingCss.class.php');
require_once(dirname(__FILE__).'/_class/parsingHtml.class.php');`

can you this code in your file pls, ty
:)

**Comment by spipu** [comment]
It is because you do not use composer to install html2pdf, with its autoload. Look at the readme and the examples
