### ISSUE TITLE
Class 'HTML2PDF_locale' not found in ....  

### ISSUE THREAD

**Issue by ScovelRacing** [spipu/html2pdf#116]
I ran composer install on the html2pdf folder and everything seemed like it was going to work, but then when i create the pdf I get .. Class 'HTML2PDF_locale' not found in ..

I applied some fixes found on the old forum 

require_once(dirname(__FILE__).'/_class/tcpdfConfig.php');
require_once(dirname(__FILE__).'/_class/locale.class.php');
require_once(dirname(__FILE__).'/_class/myPdf.class.php');
require_once(dirname(__FILE__).'/_class/exception.class.php');
require_once(dirname(__FILE__).'/_class/parsingCss.class.php');
require_once(dirname(__FILE__).'/_class/parsingHtml.class.php');

this fixed that issue.. but now I get Fatal error: Class 'TCPDF' not found in /home/accountname/public_html/timers/html2pdf/_class/myPdf.class.php on line 20

I'm confused, and could use some help... please.

**Comment by ScovelRacing** [comment]
Additional Info: I'm on a shared server so had to install to the directory as instructed on https://getcomposer.org/download/ 

`php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '92102166af5abdb03f49ce52a40591073a7b859a86e8ff13338cf7db58a19f7844fbc0bb79b2773bf30791e935dbd938') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"`

I then ran `php composer-setup.php --filename=composer` and `php composer install` everything worked great and it said it installed the dependencies.

**Comment by spipu** [comment]
Have you require the vendor autoloader in your script ? Look at the examples to see how to do. It allows you to not include all the class manually

**Comment by Seb00ch** [comment]
+1 Spipu !
Remove all the require_once you added and require_once the autoload BEFORE the html2pdf class
