### ISSUE TITLE
Bold not working

### ISSUE THREAD

**Issue by Seb00ch** [spipu/html2pdf#117]
Hi folks !
I install html2pdf 4.5.1 with Composer in the third_party Codeigniter's directory.
I copy an example and all works in my view, but neither "B" nor "STRONG" work.
I must hard-code a "style='font-weight: bold'"....
For information, i ran the script on Firefox, Chrome and export the pdf, no success... Italic & underlining works

Any idea ??

**Comment by juanjosv** [comment]
I use the <b> and works, had you tried with the tag lowercase?

**Comment by avlima** [comment]
+1
