### ISSUE TITLE
Class 'Spipu\Html2Pdf\Html2Pdf' not found 

### ISSUE THREAD

**Issue by vinvin27** [spipu/html2pdf#118]
Hello,

Im struggling with Html2Pdf, I installed composer then did _composer require spipu/html2pdf_ 

Output : 

`Using version ^4.6 for spipu/html2pdf
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing tecnickcom/tcpdf (6.2.12)
    Loading from cache

  - Installing spipu/html2pdf (v4.6.1)
    Loading from cache`

And I got this php files to generate my Pdf like your example : 

```
<?php
require_once dirname(__FILE__).'/vendor/autoload.php';

use Spipu\Html2Pdf\Html2Pdf;
use Spipu\Html2Pdf\Exception\Html2PdfException;
use Spipu\Html2Pdf\Exception\ExceptionFormatter;

// Form sent
if( isset($_POST['val']) ){
    ob_start();
    include dirname(__FILE__).'/res/foo.php';
    $content = ob_get_clean();

    $html2pdf = new Html2Pdf('P', 'A4', 'fr', true, 'UTF-8', array(15, 5, 15, 5));
    $html2pdf->pdf->SetDisplayMode('fullpage');
    $html2pdf->writeHTML($content);
    $html2pdf->Output('exemple02.pdf');
}
?>
```

And Im getting this error on log : 

**"PHP message: PHP Fatal error:  Class 'Spipu\Html2Pdf\Html2Pdf' not found** on line with  = new Html2Pdf

I don't understand what's going on !

**Comment by juchi** [comment]
Hi,
Try updating the class name you require with uppercase : HTML2PDF

**Comment by vinvin27** [comment]
Hello,

You mean : 
use Spipu\Html2Pdf\HTML2PDF; ? still not working :/

**Comment by juchi** [comment]
you also need to update the instantiation line : new  HTML2PDF(...)

**Comment by vinvin27** [comment]
Thanks Juchi but still nothing,

Im getting this error :  PHP Fatal error:  Class 'Spipu\Html2Pdf\HTML2PDF' not found in

`require_once dirname(__FILE__).'/vendor/autoload.php';

use Spipu\Html2Pdf\HTML2PDF;
use Spipu\Html2Pdf\Exception\Html2PdfException;
use Spipu\Html2Pdf\Exception\ExceptionFormatter;

// Form sent
if( isset($_POST['val']) ){


    ob_start();
    include dirname(__FILE__).'/res/foo.php';
    $content = ob_get_clean();

    $html2pdf = new HTML2PDF('P', 'A4', 'fr', true, 'UTF-8', array(15, 5, 15, 5));
    $html2pdf->pdf->SetDisplayMode('fullpage');
    $html2pdf->writeHTML($content);
    $html2pdf->Output('exemple02.pdf');


}
`

**Comment by juchi** [comment]
I get it. There is no namespace support in version 4.6.1, it will be in version 5. HTML2PDF class is still in the global namespace.

**Comment by vinvin27** [comment]
Ok, so I just added : 

require_once dirname(__FILE__).'/vendor/autoload.php';
require_once(dirname( __FILE__ ).'/vendor/spipu/html2pdf/html2pdf.class.php');

without any use instructions.

It's Workin 👍

**Comment by SuN-80** [comment]
`require_once( __DIR__ .'/vendor/autoload.php');` is enough. then `new Html2Pdf();`

**Comment by dennisheiden** [comment]
Just for everyone who is using Html2Pdf in a sub directory:

Folders:

```
"/printer/composer.json" -> install config for Composer
"/printer/src/" -> Html2Pdf stuff
"/printer/vendor/" -> Autoloader
```

In your printer.class :

```
require_once(__DIR__.'/printer/vendor/autoload.php');

use Spipu\Html2Pdf\Html2Pdf;
use Spipu\Html2Pdf\Exception\Html2PdfException;
use Spipu\Html2Pdf\Exception\ExceptionFormatter;

class printer{
```

**Comment by fh-thudson** [comment]
Let me know when you just fix this I will go back to my other solution.
