### ISSUE TITLE
Without composer 

### ISSUE THREAD

**Issue by rwanito** [spipu/html2pdf#121]
Hi !
I would like to know if is possible to install html2pdf without composer. So, I cannot install composer on my server. Exist it a solution to use it without dependendies : "seems that HTML2PDF dependencies are not installed". Just drag and drop install ?
Thanks you !

**Comment by spipu** [comment]
You have not to install composer on a production serveur, only on your dev environment... You prepare your delivery package on your local composer (including installing lib with composer), and then you send your package delivery on the production server

**Comment by rwanito** [comment]
Ok, i have done it.
I done this : 
git clone https://github.com/spipu/html2pdf.git
cd html2pdf
composer install

I have installed : wamp, composer and git to execute this commands.
where can I retrieve files to integrate into my ftp server?

Thanks you !

**Comment by juchi** [comment]
Hi,
You need to copy the files from your webserver directory (i guess wamp, that's unclear) and copy them to your server.
As this is not related to html2pdf i'll close the issue.

**Comment by WebSpectrum** [comment]
Rediculous we have to go though this all this jumping tbhorugh hoops to get a pacjage - why can;t you offer package without composert - so annoying
