### ISSUE TITLE
Can I set portrait orientation but width bigger?

### ISSUE THREAD

**Issue by mattpass** [spipu/html2pdf#123]
I'm having a problem at the moment - I need to set the layout as portrait, but then print the produced PDF on a label printer, which has landscape labels.

Can HTML2PDF separate page dimensions and page orientation be in some way?

HTML layout I have:
![x](https://cloud.githubusercontent.com/assets/1311155/16087303/73a6880a-331a-11e6-834d-95961a25525a.png)

These labels are correctly laid out above, but I have to specify landscape orientation to get dimensions wider than higher. It means when they are printed they are turned 90 degrees and end up being printed like this (they get turned 90 degrees and scaled to fit):

![y](https://cloud.githubusercontent.com/assets/1311155/16087392/c699644c-331a-11e6-9f11-f0f337cc9385.png)

This is the result I need to achieve:
![z](https://cloud.githubusercontent.com/assets/1311155/16087516/1e0d5896-331b-11e6-978e-813fc597e71f.png)

Any advice much appreciated, many thanks!

**Comment by spipu** [comment]
yes, you can, look at the 2 first parameters of html2pdf :)
