### ISSUE TITLE
Page blanche avec une image exsitante

### ISSUE THREAD

**Issue by jarodxxx** [spipu/html2pdf#124]
Bonjour, 

Je me suis rendu compte que certaine images ne s'affiche pas sur mon PDF pourtant l'image et son chemin sont correcte.
J'ai simplifié le code html pour n'afficher QUE l'image et cela ne marche pas:

`$content = '<page><img src="https://www.ernmt-officiel.com/front/images/uploads/files/arrete_jpg/13047-4.jpg" /></page>';`

Pourtant l'url de l'image est bonne
et avec une autre image cela fonctionne
`
$content = '<page><img src="https://www.ernmt-officiel.com/front/images/uploads/files/arrete_jpg/13047-2.jpg" /></page>';`

**Comment by jarodxxx** [comment]
Je viens de m'apercevoir que le PDf généré fonctionne bien sous firefox , mais pas sous chrome

**Comment by juchi** [comment]
Hi,
As your issue is specific to one image, i'd say this is an issue with the format of your file and not HTML2PDF related.
