### ISSUE TITLE
Page Counting

### ISSUE THREAD

**Issue by perler-at** [spipu/html2pdf#126]
Hi!

I have a problem with [[page_cu]]/[[page_nb]]

My page structure:
`<page pageset="new" backtop="120mm" backbottom="0mm">
    <page_header></page_header>
    <page_footer></page_footer>
    Page [[page_cu]]/[[page_nb]]
</page>
<page pageset="old">
    Page [[page_cu]]/[[page_nb]]
</page>
<page pageset="new" backtop="120mm" backbottom="0mm">
    <page_header></page_header>
    <page_footer></page_footer>
    Page [[page_cu]]/[[page_nb]]
</page>`

expected numbering:
On Page 1: 1/2
On Page 2: 2/2
On Page 1: 1/1

but I got this numbering:
On Page 1: 1/3
On Page 2: 2/3
On Page 1: 3/3

Is this a bug or am I doing something wrong?

Greets, Perler

**Comment by fagundes** [comment]
What version of html2pdf are you using?

**Comment by perler-at** [comment]
v4.03

**Comment by fagundes** [comment]
I suggest you to use the lastest version. 
v4.6.1

**Comment by spipu** [comment]
it is not pageset that you have to use, it is pagegroup="new" !!!
