### ISSUE TITLE
Deprecated: Methods with the same name as their class will not be constructors

### ISSUE THREAD

**Issue by isaacvqz** [spipu/html2pdf#129]
I have a problem with html2pdf when upgrading to php 7

Codeigniter...
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Html2pdf has a deprecated constructor in /application/libraries/Html2pdf.php

**Comment by juchi** [comment]
Hi,
Could you be more specific ? I can't find a PHP4-like constructor in the Html2pdf class. Which version are you using ?

**Comment by spipu** [comment]
you must upgrade your html2pdf version
