### ISSUE TITLE
page_header versus dynamic document

### ISSUE THREAD

**Issue by fagundes** [spipu/html2pdf#13]
I have to create a dynamic document which is changed based on the data from my database. But this document only has a page header starting from the second page. 

I wasn't capable of creating the HTML to solve that problem. Is that possible? How can I do that?

**Comment by fagundes** [comment]
To prevent a page header on the first page, I created a new attribute to page tag called hideheader which accepts a list of page numbers that gonna skip the header.

**Comment by fagundes** [comment]
We already merged commits which solve this problem.
So, we can close.

**Comment by paragajency** [comment]
It is not working though. I have added the hideheader param on my markup. 

<page  backtop="25mm" backbottom="14mm" backleft="14mm" backright="14mm"  hideheader = "1,2" style="font-size: 12pt">
    <page_header></page_header>
</page> 

and if i try to dump the parameters in function, hideheader  paramater is missing.

protected function _tag_open_PAGE($param){
    var_dump($param);
