### ISSUE TITLE
How do I include an external css file?

### ISSUE THREAD

**Issue by danielson317** [spipu/html2pdf#130]
I am including a css file relative to my website's root. How do I include this in the sheet. Currently I'm getting a "No such file or directory". 

Is there a setting that allows me to set the root path for relative urls? 

I have the same issue with images.

**Comment by ebedy** [comment]
Hello. You can not include an external style sheet file your. css style is directemenet written in html code. But you must respect that of html2pdf ..

**Comment by spipu** [comment]
You can include a css file.

Just look at example ;)

**Comment by ebedy** [comment]
Ok thank's

**Comment by graham73may** [comment]
https://github.com/spipu/html2pdf/tree/master/examples

Which example shows external css?

**Comment by csimpi** [comment]
There isn't example about this ... 👎

**Comment by alexandradra** [comment]
Hi ! 
Is it possible to have a clear reply to this question ?
As suggested, I had a look on all the examples and they all have style tags, not an external link... 😅 
Many thanks !

**Comment by dennisheiden** [comment]
Please take a look into [file_get_contents() ](http://php.net/manual/en/function.file-get-contents.php) 
and teach yourself about **absolute paths** in PHP.

Your problem is not Html2PDF related. Retrieve the content of your CSS file via file_get_contents() and add it to your HTML string which you want to parse to a PDF file.

**Comment by lenamtl** [comment]
Hi Denis, 
the only example that show **file_get_contents** is for $content is there a var for CSS?
`$content = file_get_contents(K_PATH_MAIN.'examples/data/utf8test.txt');`

How would you pass it for the CSS is there any existing var for this or we have to create one?
`$stylesheet =file_get_contents(K_PATH_MAIN.'mysite/css/theme.css');`

I think this would be very appreciate if we could have a complete example for this.
We don't use inline CSS anymore so I guess this will be very handy for the community.

**Comment by viciexperts** [comment]
Hello,
I had same issue.

I removed the html tags, meta, title and only let the style sheet link href and the body and  the css style sheet worked.
