### ISSUE TITLE
Use html2pdf without composer

### ISSUE THREAD

**Issue by thierryler** [spipu/html2pdf#132]
Hello,

How can we use html2pdf in a project that does not use Composer ? What would be the best way ?

Thx,
Th.

**Comment by juchi** [comment]
Hi,
You can do it as you'd do for any other project : you get the code and dependencies manually and manage the autoloading process yourself.
Alternatively, you may use version 4.03 which was not supporting composer and embeds the dependencies.

**Comment by lwenke** [comment]
Version 4.4.0 also doesn't require composer and includes TCPDF. I wish the newer versions would do the same.

**Comment by thierryler** [comment]
Hello. Just tried 4.0.3 and 4.4.0 and both are OK.

Thx.
