### ISSUE TITLE
Header and Footer on first page, then content on second page with no header and footer

### ISSUE THREAD

**Issue by simon-brooks** [spipu/html2pdf#136]
I am generating packing slips and am getting a random issue, with certain orders.  95% of them work correctly, 

I am getting the odd one that prints the header and footer and no content on the first page.  Then prints the content on the second page with no header and footer, then from page 3 it is bahaving correctly printing header footer and content on each page.

Attached file 00006015_dispatch.pdf shows the output with this behaviour.

[00006015_dispatch.pdf](https://github.com/spipu/html2pdf/files/455671/00006015_dispatch.pdf)

The following pdf 00006018_dispatch.pdf shows the output that I am expecting.  Generated under the same code base, just a different set of data driving it.  This is how most of them appear.

[00006018_dispatch.pdf](https://github.com/spipu/html2pdf/files/455669/00006018_dispatch.pdf)

Html used to generate the one with problems. Is in the following file html.txt

[html.txt](https://github.com/spipu/html2pdf/files/455680/html.txt)

I am using version 4.01 of HTML2PDF

**Comment by spipu** [comment]
Can you give a simplest example with the usecase ?
