### ISSUE TITLE
Big troubles with images

### ISSUE THREAD

**Issue by villalvilla** [spipu/html2pdf#140]
Hello,

This library has big troubles with image resolution. After analyzing your source code, I finally found that the main problem is that the only information that you get from the image is the width and height of the image in pixels, figuring out that the resolution (DPI or PPI) of the image is standar. This is a common mistake that could be easily fixed adding a php library like Imagick in order to extract DPI/PPI information from the image. This way, it would be much easier to format image in a proper way. I'm working on that now and I could upload a pull request in a couple of hours if you want.

Regards,
Miguel Amez

**Comment by longle-h** [comment]
Hello,

I'm currently working on a webservice where we're using a lot HTML2PDF, have you tried this code : 
`<page format="210x297" backimg="PATH_TO_YOUR_IMG">` ?
This is used for a BackImg, but with dirty minds it can be used to have a correct image format ;)

**Comment by villalvilla** [comment]
Hi longle-h,
No, I haven't. Backimg? mmm... That way is a little bit "dirty", I suspect XD. What I've done to solve this is adapting the ratio between points and pixels in a proper way, figuring out how html2pdf works with images at a "reasonable" dpi quality. I managed to print images clearly to pdf adapting that ratio at 300 dpis, so now every image that I want to include in my documents is perfectly outputted!
Thanks for your help,
Villalvilla

**Comment by dunarri** [comment]
@villalvilla could you share your code to do this?

**Comment by spipu** [comment]
html2pdf does not transform image. it use directly the file that you give to it.
