### ISSUE TITLE
Making 4.6.1 official release version

### ISSUE THREAD

**Issue by vincent-guesnard** [spipu/html2pdf#142]
Hello,

I would like to thanks you for this amazing lib, you did a great job.

I've created a script which force me to watch releases on Github to upgrade my own system and your project is in error since the last version 4.6.1 is not the last declared version (which is 4.5.1).

It would be very appreciated if you fix this.

Thank you very much.

PS : Your library is ready TCPDF 6.2.13 according to my tests.

Best regards,

Vincent

**Comment by spipu** [comment]
soty for this pb.

The next release 5.0.0 will come soon, and will be declared as the last one
