### ISSUE TITLE
Pagebreak support

### ISSUE THREAD

**Issue by heidenmedien** [spipu/html2pdf#143]
Hi,

I'm wondering if pagebreak support is coming, (I didn't find any info about that on the wiki) it is possible and simple to implement:

http://stackoverflow.com/questions/2117788/page-break-in-html2pdf

Html2Pdf v4.03

For example we want to parse a tag DIV:

html2pdf.class.php line 2948:

```
protected function _tag_close_DIV($param, $other='div')
{
    if ($this->parsingCss->value['page-break-after'] == "always")
      $this->_setNewPage(null, '', null, $this->_defaultTop);
      $this->parsingCss->setPosition();
    ...
}
```
parsingCss.class.php Line 114:

//add a new style declaration
```
public function initStyle()
{
    ...
    $this->value['page-break-after'] = null;
}
```
Line 1024 add a new handler to the switch case:

```
case 'page-break-after':
    $this->value[$nom] = $val;
    break;
```
And then for it to work, your html content should contain the break element

 <div style="page-break-after:always; clear:both"></div>

- Thanh Trung

**Comment by spipu** [comment]
You can make a PR on the branch master :)
