### ISSUE TITLE
SVG <path> with smooth curveto

### ISSUE THREAD

**Issue by smierzala** [spipu/html2pdf#146]
Hi everybody,

When I want to include my SVG in my <page> in a <draw>, I got : 

`ERREUR n°0
Fichier : /Users/smierzala/Sites/ongconseil-app/vendor/spipu/html2pdf/_class/myPdf.class.php
Ligne : 919

SVG Path Error : [s] unkown`

In myPdf.class.php, there is no treatment for S,

Do you have any idea for this issue ? 

Thank you all

**Comment by spipu** [comment]
It is not manage yet.

You can make a PR is you want
