### ISSUE TITLE
Problem with justificated texts and margins while breaking a line in a tag

### ISSUE THREAD

**Issue by adrianogoncalves** [spipu/html2pdf#148]
When using justified texts, like in the attached example, and when the line ends with a tag (like `<strong>`, `<span>` or `<em>`), the automatic line breaking becomes crazy. The HTML I used is attached. And this is my HTML2PDF call:

` $html2pdf = new HTML2PDF('L', 'A4', 'pt', true, 'UTF-8', [
            5,
            5,
            5,
            1]);`

**Comment by adrianoprospero** [comment]
[html_w_error.txt](https://github.com/spipu/html2pdf/files/627450/html_w_error.txt)
