### ISSUE TITLE
after converting html to pdf ,how to store that pdf on file server

### ISSUE THREAD

**Issue by parvez301** [spipu/html2pdf#149]
i have converted my html to pdf and now i want to store that pdf on file server and user should get the dynamic link to access that pdf,how can i do it?Actually i'm trying to read a csv file and from each row i'm creating a pdf.
`        if (isset($_POST['submit'])) {
	//Import uploaded file to Database
	$handle = fopen($_FILES['filename']['tmp_name'], "r");
	fgets($handle); 
	while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
		$import="INSERT into orders_table(order_id,purchase_date,buyer_name,sku,product_name,quantity_purchased,currency,recipient_name,ship_address_1,ship_address_2,ship_address_3,ship_city,ship_state,ship_postal_code,ship_country,ship_phone_number) values('$data[0]','$data[1]','$data[2]','$data[3]','$data[4]','$data[5]','$data[6]','$data[7]','$data[8]','$data[9]','$data[10]','$data[11]','$data[12]','$data[13]','$data[14]','$data[15]')";

		mysqli_query($conn,$import) or die(mysqli_error($conn));
		ob_start();
		require_once('custom.php');
		$content = ob_get_clean();
		require_once('/vendor/autoload.php');
		require_once(dirname(__FILE__).'/vendor/spipu/html2pdf/html2pdf.class.php');
		$html2pdf = new HTML2PDF('P','A4','fr');
		$html2pdf->WriteHTML($content);
	}
	fclose($handle);
	print "Import done";
}`

**Comment by fagundes** [comment]
Check `$htmpl2pdf->Output('F')`, more information in the [documentation](html2pdf.fr) or even in the code in the [output implementation](https://github.com/spipu/html2pdf/blob/v4.03/html2pdf.class.php#L327-L346).
