### ISSUE TITLE
Footer in main part of the page

### ISSUE THREAD

**Issue by Jean-Dom** [spipu/html2pdf#150]
I am new on HTML2PDF, using it through a software (Ogust) provided by Sikyo.
I do not know which release I use. I do not know, either, which are the margin values, for instance.

I have a WISIWYG editor (seems to be the same than on Joomla), with 2 extra fields for header & footer.
I have problem with pages conversion and, since the support team begins to answer "the problem comes from HTML2PDF", I become a bit upset.

I have a problem with the baseline, when I switch the font. For instance, when I begin the line with "Times new roman, 10" (label), then switch to "Courier new, 12" (for the data), the baseline of the courier new is higher than the one of the times new roman.
If I use a table, changing the cell when changing the font, the baseline is correct but the table (3 rows) goes into the main part of the page instead of being in the footer.
If I go back to standard paragraph, with only 1 font on each line and < strong > < / strong >, I have no problem... But the style in the < hr > is not processed correctly (width, height...)

Here is the code I use (I insert spaces in the tags to avoid process by this bug reporter):
< p style="line-height: 14px; font-family: times new roman,times; font-size: 13px; text-align: center;" >
< hr style="width: 50%; color: black; height: .25px;" / >
Client : < strong >{codeClient#defaut}< / strong > - Facture : < strong >{numeroFacture#defaut}< / strong > - TVA : {tvaintracommunautaire#defaut} - SIRET : {siretSociete#defaut} - NAF : 9609Z< BR >
Banque : {Domiciliation#defaut} - {libribiban#defaut} {ribiban#defaut} - {ribibanbicdom#defaut}< BR >
{libelleCourtSociete#defaut} - {adresseSociete#adresseLigne} - SARL au capital de {capitalEts#defautEuro} - {rcssociete#defaut}< / p >

Thanks for your help... if any :-).

**Comment by Jean-Dom** [comment]
No answer, no solution, no clue?
Is it a bug? Is it solved?
Nearly 2 years later, the problem is closed without any reason…

**Comment by spipu** [comment]
Hi,
there is no html2pdf version, no complete example with the pb. 
And also, most of the time, WYSIWYG generate HTML code that is not totally compatible with HTML2PDF.
If there is an error on the integration of HTML2PDF with Ogust, then Sikyo has to open an issue with more technical pbs..
i could not help directly...
