### ISSUE TITLE
Missing file from repo

### ISSUE THREAD

**Issue by carlos-jondon** [spipu/html2pdf#152]
File is missing.
`require_once(dirname(__FILE__).'/../vendor/autoload.php');`

**Comment by fagundes** [comment]
Did you install it from composer? This file is generated by composer.

**Comment by juchi** [comment]
Hi,
As pointed out by @fagundes, please follow the install step on the readme file in order to get going.

**Comment by carlos-jondon** [comment]
I can't get composer to work in my windows PC.
How can I get all the files required?
