### ISSUE TITLE
errror when i run the code

### ISSUE THREAD

**Issue by fatima-abo** [spipu/html2pdf#153]
i have this error . please can you tell  me the problem.
Warning: require_once(D:\htdocs\html2pdf-4.5.1\examplesD:/../vendor/autoload.php): failed to open stream: No such file or directory in D:\htdocs\html2pdf-4.5.1\examples\about.php on line 15

Fatal error: require_once(): Failed opening required 'D:\htdocs\html2pdf-4.5.1\examplesD:/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in D:\htdocs\html2pdf-4.5.1\examples\about.php on line 15

**Comment by fagundes** [comment]
Check #152 .

**Comment by spipu** [comment]
you must use composer
