### ISSUE TITLE
datas with special characters é, è, à ... not dispalyed in the pdf file

### ISSUE THREAD

**Issue by Gecko62** [spipu/html2pdf#154]
Hi,
I have some datas containing special charaters (é è à ï) in a SQL table (interclassment latin 1_swedish_ci)

These datas are not displayed on the html File (cf attached file Ex1.jpg)

I have tried following solutions with no changes. 

```
$pdf = new HTML2PDF('L', 'A4', 'fr', false, 'ISO-8859-1', array(10, 10, 10, 10));
$pdf = new HTML2PDF('L', 'A4', 'fr', false, 'utf-8', array(10, 10, 10, 10));
$pdf = new HTML2PDF('L', 'A4', 'fr', false, 'ISO-8859-15', array(10, 10, 10, 10));
```

Do somebody have an idea ?

Thanks a lot for your answer

Gecko

![ex1](https://cloud.githubusercontent.com/assets/24946431/21700848/b4a76d28-d3a2-11e6-8b14-d394ca6ba9df.jpg)

**Comment by dsd0informtica** [comment]
I solved the same issue by modifying some code.
Starting from 4.4, the line 239 of the file parsingHtml.class.php includes this code:
`if ($spaces) $txt = preg_replace('/\s+/isu', ' ', $txt);`
Replace it with (that is, remove the letter 'u'):
`if ($spaces) $txt = preg_replace('/\s+/is', ' ', $txt);`
I don't know why but it worked for me.

**Comment by lekoaf** [comment]
@dsd0informtica  u = unicode

`u modifier: unicode. Pattern strings are treated as UTF-16. Also causes escape sequences to match unicode characters`

**Comment by spipu** [comment]
Your database use latin 1_swedish_ci => does not use libs that use UTF-8 :)

using latin 1_swedish_ci is bad...
