### ISSUE TITLE
New section for page numbers

### ISSUE THREAD

**Issue by poitierjohan** [spipu/html2pdf#155]
Hi,

Is it possible to do this : 
- create multiple section (number of pages) in the same pdf document ?

I'he this : 
```
<page>
Page [[page_cu]] of [[page_nb]]
</page>

<page>
Page [[page_cu]] of [[page_nb]]
</page>

<page>
Page [[page_cu]] of [[page_nb]]
</page>
```

Thank your for yours ansmers (sorry for my english, I speek french)

**Comment by spipu** [comment]
you can do it, you have just to look at the examples ;)

https://github.com/spipu/html2pdf/blob/master/examples/res/groups.php

**Comment by poitierjohan** [comment]
Thank you very much for you fast answer !
I will try it and confirm that it works correctly !

**Comment by poitierjohan** [comment]
All is right ! Thank you !!
