### ISSUE TITLE
To long to convert datas

### ISSUE THREAD

**Issue by Gecko62** [spipu/html2pdf#156]
High,

Do somebody knows a solution to avoid this message

`Fatal error: Maximum execution time of 30 seconds exceeded in C:\Program Files (x86)\EasyPHP\data\localweb\swsytest\html2pdf\vendor\tecnickcom\tcpdf\include\tcpdf_static.php on line 1568`

I want to extract approximately 15000 records from a database

Thanks a lot for your ideas

Best regards 

Gecko62

**Comment by jerrywham** [comment]
Try to up the time limit of php with `set_time_limit(90)` for example.
