### ISSUE TITLE
Collaboration Improvement

### ISSUE THREAD

**Issue by Pierozi** [spipu/html2pdf#157]
Helle there,

This project is in nomads land since a while and I can still see many new PR arrived frequently.
If @spipu you had no time to handle this, maybe could you define other maintainers can assist you.

Special ping to recent owner of PR : @kstenschke @mlocati @salemgolemugoo @juchi

**Comment by kstenschke** [comment]
After having tried some performance improvements, html2pdf still couldn't cover our needs in speed. We eventually finally used a server-sided headless browser (wkhtmltopdf) instead, which proved to be a whole lot faster (plus html5 / css3 compatible). (Please note: i am not in any way related to the wkhtml2pdf project)
Especially if development on html2pdf halted, extending the information provided in the readme with a recommendation to a more timely solutions e.g. like the above mentioned (for sufficiently able audiences)  would make sense?

**Comment by spipu** [comment]
i had no time  since some month for html2pdf project, 

but now, i have time :)
