### ISSUE TITLE
Table > tfoot > subtotal

### ISSUE THREAD

**Issue by poitierjohan** [spipu/html2pdf#159]
Hi, 
Is that possible to have a subtotal of a column in the tfoot of each page ?

thanks for your answers.

**Comment by saidmoya12** [comment]
In my case i do a "controller" with all computed data, list and total. then in a "template" i have that results.

I recomend you handle separatly the html generated and the operations

**Comment by poitierjohan** [comment]
Hi Said, thank you for your answer.
Do you have any snippet to propose ?
Thanks :)
