### ISSUE TITLE
html2pdf create empty page when i use div

### ISSUE THREAD

**Issue by fatima-abo** [spipu/html2pdf#160]
hallo.
this is a part of my program when i use div an empty page create in the pdf. when i replaced with span it work perfect. but i need div in this part what i have to do what is the problem??
<div  contentEditable="true" id="letterText" >
<?php  echo $te; ?>
</div>

**Comment by spipu** [comment]
can i have a example ?

**Comment by fatima-abo** [comment]
hallo
which exampe do you want?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by spipu** [comment]
A little html to reproduce the issue :)

**Comment by fatima-abo** [comment]
I am really really sorry,  i didn't find the code.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
