### ISSUE TITLE
Save PDF file in server

### ISSUE THREAD

**Issue by mohamedtijani** [spipu/html2pdf#164]
The 'F' option of the Output () method to save to the server does not work
version html2pdf 4.5.1

**Comment by ChangezKhan** [comment]
Yeah, same issue in version 4.5.0 also. Throwing 500 error.

**Comment by titostoerfall** [comment]
Workaround for this is:
[ ... ]
`$html2pdf->writeHTML($content);`
`$pdfTest = $html2pdf->Output('', true);`
`file_put_contents('test.pdf', print_r($pdfTest, true));`
[/...]

regards

**Comment by spipu** [comment]
what is exactly the error ?

**Comment by spipu** [comment]
it has been fixed on master branch.

It was a TCPDF error with relative path. I add some protection to avoid it
