### ISSUE TITLE
How Integrate html2PDF with Magento-2

### ISSUE THREAD

**Issue by mehul-dhinoja** [spipu/html2pdf#165]
I have requirement to generate the PDF for my custom module. Kindly assist me with the solution to integrate the html2PDF in Magento-2.

**Comment by saidmoya12** [comment]
Do you must create a bridge bitween the API and the html2PDF Library.

We need some code to help you

**Comment by spipu** [comment]
you add html2pdf throw  composer
you create a block attached to a template
you render the block with the toHTML method
you send this html to html2pdf
