### ISSUE TITLE
Inline CSS Issue

### ISSUE THREAD

**Issue by crow1796** [spipu/html2pdf#166]
Try running this code:

`$content = '<page><div style="display: block; width: 100%; color: #000000; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: #ffffff; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; background-color: transparent; background-size: cover; background-image: ; background-repeat: no-repeat; "><div style="width: 25%; display: inline-block; color: #000000; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; border-style: solid; border-color: rgba(131, 30, 30, 1); margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 15px; padding-right: 15px; padding-bottom: 15px; padding-left: 15px; background-color: transparent; background-size: cover; background-image: ; background-repeat: no-repeat; "><p style="display: block; width: 100%; color: #000000; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: #ffffff; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; background-color: transparent; background-size: cover; background-image: ; background-repeat: no-repeat; "><p>Test</p></p></div><div style="width: 33.333333333333336%; display: inline-block; color: #000000; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; border-style: solid; border-color: rgba(104, 71, 71, 1); margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 15px; padding-right: 15px; padding-bottom: 15px; padding-left: 15px; background-color: transparent; background-size: cover; background-image: ; background-repeat: no-repeat; "><p style="display: block; width: 100%; color: #000000; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: #ffffff; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; background-color: transparent; background-size: cover; background-image: ; background-repeat: no-repeat; "><p>TEst 2</p></p></div><div style="width: 33.333333333333336%; display: inline-block; color: #000000; border-top-width: 1px; border-right-width: 1px; border-bottom-width: 1px; border-left-width: 1px; border-style: solid; border-color: rgba(117, 23, 23, 1); margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 15px; padding-right: 15px; padding-bottom: 15px; padding-left: 15px; background-color: transparent; background-size: cover; background-image: ; background-repeat: no-repeat; "><p style="display: block; width: 100%; color: #000000; border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px; border-style: none; border-color: #ffffff; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; padding-top: 0px; padding-right: 0px; padding-bottom: 0px; padding-left: 0px; background-color: transparent; background-size: cover; background-image: ; background-repeat: no-repeat; "><p>Test 4</p></p></div></div></page>';`
`$html2pdf = new HTML2PDF('P', 'Legal', 'en', true, 'UTF-8', array(10, 10, 10, 10));`
`$html2pdf->WriteHTML($content);`
`$html2pdf->Output('ex_dir/example.pdf', 'F');`

Output:

![image](https://cloud.githubusercontent.com/assets/12120770/22578296/b49bd1e0-ea02-11e6-98b6-b6c42d93241d.png)

Expected Output: 

![image](https://cloud.githubusercontent.com/assets/12120770/22578316/d15f032e-ea02-11e6-922a-ce623fcf78ef.png)

**EDIT:**

Also float and inline-block properties are not working.

**Comment by mlbd** [comment]
According to this pages instruction http://demo.html2pdf.fr/examples/pdf/about.pdf

Floats are only handled for img markups by the class in html2pdf

it would be a great feature if it also supports other elements as well.

**Comment by spipu** [comment]
It will not. try to make a simplest html... and do not use display block on P tag... it is not for that. Use div

**Comment by christophbee** [comment]
But how to create multi-column layout then if float on div is not supported?

**Comment by mike-pin1** [comment]
You create multi-column layout by using... TABLES :)

**Comment by sivanagak** [comment]
`<strong>` tag making entire pdf in strong, how to avoid it?
