### ISSUE TITLE
html2pdf trouble with style-sheed definition like td:nth-child, td:first-child, last-child and so on

### ISSUE THREAD

**Issue by bbmessing** [spipu/html2pdf#168]
To create the pdf from my tables html workes fine. but i try to define some borderstyles with css nth-child, last-child, first-child and so on. It seems to be not supported. I don 't want to use inline-styles because of performance. Has anybody an idea?

**Comment by shawe** [comment]
Same problem for me, I was looking for this because I don't find any CSS rule that is working with it.

Maybe a counter for even and odd can do the trick in my case.

**Comment by shawe** [comment]
Otherwise, it also have problems with border-radius and background-color ignoring the border on the background.

And also is very slow compared to other similar system, but not loading from HTML template.

**Comment by spipu** [comment]
virtual css elements are not supported by html2pdf, you have to apply directly the good class name to the tags
