### ISSUE TITLE
Error on html2pdf.class.php

### ISSUE THREAD

**Issue by Alexis6307** [spipu/html2pdf#171]
This error occurs with this simple code in second line:

`require_once(DIR_WWW.'lib/html2pdf-4.5.1/html2pdf.class.php');<br/>`
`    $html2pdf = new HTML2PDF('P','A4','fr');`
`    $html2pdf->WriteHTML($content);`
`    $html2pdf->Output('exemple.pdf');`

`Fatal error: Uncaught Error: Class 'HTML2PDF_locale' not found in /var/www/html/lib/html2pdf-4.5.1/html2pdf.class.php:132 Stack trace: #0 /var/www/html/lab/test.php(181): HTML2PDF->__construct() #1 /var/www/html/lab.php(12): include('/var/www/html/l...') #2 /var/www/html/_router.php(41): include('/var/www/html/l...') #3 {main} thrown in /var/www/html/lib/html2pdf-4.5.1/html2pdf.class.php on line 132`

Can anyone help me?

**Comment by majred** [comment]
You need to include your `vendor/autoload.php` in the root of your project. In our case (CodeIgniter) we needed to add the following require statement into `htdocs/index.php`

```
require(dirname(__FILE__).'/../vendor/autoload.php');
```

Hope that helps!

**Comment by Alexis6307** [comment]
I already have this include, now it returns:

`Fatal error: Cannot declare class HTML2PDF, because the name is already in use in /var/www/html/lib/html2pdf-4.5.1/html2pdf.class.php on line 14`

**Comment by fagundes** [comment]
You need to what @theRTC204 said and you don't need include or require nothing more. You are probably including this file `html2pdf.class.php` again. So you will including this twice.

**Comment by spipu** [comment]
you must use composer and its autoloader, nothing else
