### ISSUE TITLE
css "text-overflow: ellipsis" don't work. Other possibility ???

### ISSUE THREAD

**Issue by poitierjohan** [spipu/html2pdf#172]
Hi all,

I've a problem with a text in a TD of a table

My text is too long for the width of my cell. Thus, I've multiple lines.

Is that posible to have only 1 line with, for example : "This my text and ..."
I know tha the css style text-overflow: ellipsis exist. But this property don't work with HTML2PDF.

Thank you in advance for you answers...

**Comment by spipu** [comment]
it is not manage by html2pdf

you can make a PR if you want
