### ISSUE TITLE
CSS letter-spacing

### ISSUE THREAD

**Issue by framakers** [spipu/html2pdf#175]
When i implement
$html2pdf->addFont('abelregular', 'regular', 'www/font/Abel-Regular.php');

i have a huge letter-spacing. Does html2pdf ignore the CSS setting letter-spacing?
Can't find the setting in the parsingHtml.class.php

**Comment by spipu** [comment]
it does not implement it yet.

but you can make a PR :)

**Comment by fabianmossberg** [comment]
This would be really useful.

**Comment by patpat34** [comment]
Hi everyone, 
This could be very usefull indeed !
do u think it's possible for doing this ? i know this issue is open since few years but, maybe could find a solution..
