### ISSUE TITLE
Extra cleaning of font name (PR available)

### ISSUE THREAD

**Issue by mvachette** [spipu/html2pdf#176]
I have a small issue with font-family extraction.

It works fine if the parsed HTML is 100% correct, but in my case, I enter some text with TinyMce WYSIWIG editor, and the generated HTML look like this : `<p><span style="font-family: 'comic sans ms', sans-serif;">Lorem Ipsupm...</span></p>`
(TinyMce add some quotes to the font-familly attributes)

CSS parser does not handle this case, and consequently the setFont() methods is call with a font named `'comic sans ms'` that does not exists

I could propose a PR to fix that, by cleaning caracters like quotes when extracting font-family in `\HTML2PDF_parsingCss::analyse` method (by adding characters to be trimmed in the existing call to `trim` function)

**Comment by spipu** [comment]
it has been fixed on master branch here : https://github.com/spipu/html2pdf/blob/master/src/Parsing/Css.php#L684
