### ISSUE TITLE
Google Chrome: Failed to load PDF

### ISSUE THREAD

**Issue by sultanboss** [spipu/html2pdf#178]
I have upgraded to new version (v4.6.0) using composer and after successful setup, it works great in Firefox, IE, Adobe Acrobat except Google Chrome browse. Every time it shows 'Failed to load PDF document'.

![image](https://cloud.githubusercontent.com/assets/4982921/24773039/5cbdedb4-1b35-11e7-8cf3-8b04d513ad6a.png)

**Comment by spipu** [comment]
hum, have you a link to test the error ?

and if you force download, is it working ?

**Comment by RWAP** [comment]
I too have this issue - although on a test site - try:

https://77.68.89.64/print/address?userId=lorain+%5BUser%5D&orderId=150-944-9208&googleTest=true

(ignore the security certificate warning) .

This gives the choice of printing an address label using various formats - the on screen google chrome viewer shows the correct output, but then any attempt to right click and Save As (or open in Adobe Acrobat instead) gives Failed to load PDF document.

Could it be the certificate setting?  It works fine in other browsers.

**Comment by spipu** [comment]
maybe the cert. did you try in http instead of https ?

**Comment by RWAP** [comment]
Ah yes - it does seem to be down to the invalid certificate setting (there is no problem in http) - once we have the website up and running it should therefore be resolved !

**Comment by spipu** [comment]
Ok ! I close the issue
