### ISSUE TITLE
Undefined property: HTML2PDF_myPdf::$numpages in /home/www/portalv2/spas3/html2pdf/_tcpdf_5.0.002/tcpdf.php on line 2621

### ISSUE THREAD

**Issue by puterafx** [spipu/html2pdf#180]
Hello,

I have an issu with html2pdf.  My pdf was not generated whenever i got above errors. 

can anyone help  or facing the same issue?

**Comment by spipu** [comment]
this old version of html2pdf is not supported any more, tcpdt 5 is very very old

try to go on a newer version of html2pdf
