### ISSUE TITLE
Some characters of serbian alphabet dosesn't work

### ISSUE THREAD

**Issue by maxgag51** [spipu/html2pdf#181]
I have an input field with this text: "[Osnovica PDV] [PDV: 20%] [Ne podleže obračunu PDV shodno članu 24, stav 1, tačka 7, zakona o PDV]"
When I create a PDF whit this text this is the result: "[Osnovica PDV] [PDV: 20%] [Ne podleže obra?unu PDV shodno ?anu 24, stav 1, ta?ka 7, zakona o PDV]" 
the character "č" is not correctly printed.
This is the PHP header of the script: 	header("Content-Type: text/html;charset=UTF-8");	
This the param of HTML2PDF: 		$html2pdf = new HTML2PDF('P', 'A4', 'it', true, 'utf-8');
How can I do?
Suggestions?
Thanks in advance

**Comment by spipu** [comment]
You must use a UTF8 font. Look at the utf8 example
