### ISSUE TITLE
Header and footer not rendering properly.

### ISSUE THREAD

**Issue by joao-s-neves** [spipu/html2pdf#182]
I'm having issues when converting html2pdf specially with the header and footer part.

![screenshot from 2017-04-18 11-52-11](https://cloud.githubusercontent.com/assets/17318575/25127381/7eed21ba-242d-11e7-99fc-f4f0a3c3a0ca.png)

This is the behavior i expected to have and this one below is what i get:

![screenshot from 2017-04-18 11-51-58](https://cloud.githubusercontent.com/assets/17318575/25127401/92ba6bee-242d-11e7-83a8-2584f4da7ab4.png)

i'll attach my content file below in a .txt file.

Thanks in advance
[content.txt](https://github.com/spipu/html2pdf/files/928803/content.txt)

**Comment by spipu** [comment]
you use position absolute with float left ?!

You have to clean your css and html. Try to make a simplest html

**Comment by SuN-80** [comment]
Add a div with a negative margin in your header:
```
    <page_header>
      <div style="margin:-10px"></div>
    </page_header>
```
It should output what you want.

**Comment by dennisheiden** [comment]
Sehr geehrte Kundin,
sehr geehrter Kunde,


leider bin ich zur Zeit wegen Urlaub verhindert.

Ich stehe Ihnen voraussichtlich wieder am 07.06. zur Verfügung.


Mit freundlichen Grüßen

Dennis Heiden

straightvisions - enhancing the web

Berlin Friedrichshain Dennis Heiden - Pettenkoferstraße 16-18 - 10247 Berlin - Phone +49 (0)30 / 8939 - 8450
Hamburg City Matthias Reuter - Ballindamm 39 - 20095 Hamburg - Phone +49 (0)40 / 99999 - 3020
Hamburg Nord Matthias Reuter - Hasselwisch 11a - 22397 Hamburg - Phone +49 (0)40 / 1817 - 3958
