### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by marco-uccellini** [spipu/html2pdf#184]
I am having issues trying to include an svg for the company logo.

I get the following error: **ERROR n°6 : Impossible to load the image**

I am using the following **example** markup:

`<img src="http://www.mywebsite.com/checkbox.svg" alt="icephorm" width=100 />`

It works perfectly for a PNG file :)

Can I check if SVG is supported?

Thanks

**Comment by spipu** [comment]
have you look at the examples, you have a specific tag svg.
