### ISSUE TITLE
Class html2pdf not found

### ISSUE THREAD

**Issue by RasJammin** [spipu/html2pdf#187]
I followed the install instruction: I used ''composer require spipu/html2pdf'' 
I'm using laravel so I created a controller to use html2pdf which begins by 

"namespace App\Http\Controllers;
require_once dirname(__FILE__).'/../../../vendor/autoload.php';
use \vendor\spipu\html2pdf\html2pdf;"

but this returns me a fatable Throwable error : 'class html2pdf not found' (the autoload.php file seems to be correctly required). I tried severals ways for the last line but no one works. 
Is there a solution?

**Comment by spipu** [comment]
Be carefull to CamelCase for the classname

https://github.com/spipu/html2pdf/blob/master/doc/install.md

**Comment by RasJammin** [comment]
It doesn't change anything... I tried several times with or without Upper letters

**Comment by spipu** [comment]
have you try with a stand-alone file ? (look at the first-test part in https://github.com/spipu/html2pdf/blob/master/doc/install.md)

**Comment by Lin07ux** [comment]
I get the some problem. Check the version of Html2pdf. If you installed Html2pdf by Composer, the version is 4.6.1, not the master(^5.0.0), which is not support PSR-4.

When I install the master branch like `composer require spipu/html2pdf 5.0.0`, a error is show:

```
Problem 1
    - The requested package spipu/html2pdf 5.0.0 exists as spipu/html2pdf[4.5.x-dev, 4.6.x-dev, dev-master, dev-parsing, dev-svg, v4.4.0, v4.5.0, v4.5.1, v4.6.0, v4.6.1] but these are rejected by your constraint.
```

**Comment by spipu** [comment]
try with

```
composer require spipu/html2pdf=dev-master
```

**Comment by Lin07ux** [comment]
It's don't work and stuck:

```
$ composer require spipu/html2pdf=dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Removing spipu/html2pdf (v4.6.1)
  - Installing spipu/html2pdf (dev-master 4bd4904): 
```

**Comment by RasJammin** [comment]
Finally I try dompdf which has a better integration for laravel
