### ISSUE TITLE
Urgent: spipu/html2pdf dev-master requires php ~5.4 || 7.0 -> your PHP version (7.0.16) does not satisfy that requirement.

### ISSUE THREAD

**Issue by mreiche** [spipu/html2pdf#188]
Your composer definition semes to be broken.
It requires exactly PHP 7.0.

**Comment by mreiche** [comment]
We've used "dev-master" several days before, because we are requiring autoloading and therefore we can't switch back to 4.6.0!

**Comment by spipu** [comment]
Sorry for the mistake...

I'm not at home, could you make a PR ?

Thanks !

**Comment by mreiche** [comment]
You fixed this in bd822932a76d8c078c12bd1681e865e16913e5fc
