### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by aliosmanyuksel** [spipu/html2pdf#191]
Fatal error: Uncaught exception 'Spipu\Html2Pdf\Exception\HtmlParsingException' with message 'Tags are closed in a wrong order for [td]' in C:\xampp\htdocs\asdf\vendor\spipu\html2pdf\src\Parsing\Html.php:189 Stack trace: #0 C:\xampp\htdocs\asdf\vendor\spipu\html2pdf\src\Parsing\Html.php(94): Spipu\Html2Pdf\Parsing\Html->getTagAction(Object(Spipu\Html2Pdf\Parsing\Token), Array) #1 C:\xampp\htdocs\asdf\vendor\spipu\html2pdf\src\Html2Pdf.php(529): Spipu\Html2Pdf\Parsing\Html->parse(Array) #2 C:\xampp\htdocs\asdf\index.php(39): Spipu\Html2Pdf\Html2Pdf->writeHTML('<HTML>\n <HEA...') #3 {main} thrown in C:\xampp\htdocs\asdf\vendor\spipu\html2pdf\src\Parsing\Html.php on line 189

**Comment by dennisheiden** [comment]
Please provide the HTML-Code you try to parse.

**Comment by aliosmanyuksel** [comment]
For example;

`require __DIR__.'/vendor/autoload.php';
use Spipu\Html2Pdf\Html2Pdf;
$htmlFile = "http://www.cnnturk.com/"; 
$buffer = file_get_contents($htmlFile); 
$pdf = new HTML2PDF('P', 'mm', 'TR');
$pdf->WriteHTML($buffer); 
$pdf->Output('my.pdf', 'F');
`
Output:
`Fatal error: Uncaught exception 'Spipu\Html2Pdf\Exception\HtmlParsingException' with message 'Tags are closed in a wrong order for [div]' in C:\xampp\htdocs\asdf\vendor\spipu\html2pdf\src\Parsing\Html.php:189 Stack trace: #0 C:\xampp\htdocs\asdf\vendor\spipu\html2pdf\src\Parsing\Html.php(94): Spipu\Html2Pdf\Parsing\Html->getTagAction(Object(Spipu\Html2Pdf\Parsing\Token), Array) #1 C:\xampp\htdocs\asdf\vendor\spipu\html2pdf\src\Html2Pdf.php(529): Spipu\Html2Pdf\Parsing\Html->parse(Array) #2 C:\xampp\htdocs\asdf\index.php(50): Spipu\Html2Pdf\Html2Pdf->writeHTML('<!DOCTYPE html>...') #3 {main} thrown in C:\xampp\htdocs\asdf\vendor\spipu\html2pdf\src\Parsing\Html.php on line 189`

**Comment by spipu** [comment]
The html of your page is not valid.

look at the html2pdf documentation : 

> It allows the conversion of **valid** HTML in PDF format
> You have to write you HTML for Html2Pdf, and not trying to convert directly an already existing html page.

**Comment by ogaip** [comment]
so, it's the same to another lib about pdf generator?
i thought this lib can let me take a HTML page that i get on my directory and convert to PDF
sorry for my English it's not my first language

**Comment by gagaltotal** [comment]
I found a fix with the following code :
$ html2pdf-> setTestTdInOnePage (false);
