### ISSUE TITLE
how to automatically add an extra page when the pdf has an odd number of pages

### ISSUE THREAD

**Issue by africatwinfan** [spipu/html2pdf#192]
I merge pdf files into one big file to make printing less time consuming for the user of the application.
Every merged file has to start on a new recto page. So if the previous file has only 3 pages, the next will be printed on the backside of the first.

How can I let html2pdf add an extra page automatically when there are for example 3 pages on the pdf?
 I added this on the end of my code:
	if($page_cu == $page_nb) 
	{
		?>
		&lt;PAGE pagegroup="new"	&gt;
		&lt;/PAGE	&gt;
		<?php
	}
This works, but adds a blank page on every pdf. When I try using 
if ($page_nb == 3 OR $page_nb == 5) it does nothing...

Please help

**Comment by spipu** [comment]
after each writeHtml of each little html to convert, you can make a test on the current page of the pdf, and add a page if needed

**Comment by africatwinfan** [comment]
Hi
Can you please add a code example?

Van: Laurent MINGUET [mailto:notifications@github.com]
Verzonden: woensdag 31 mei 2017 15:22
Aan: spipu/html2pdf <html2pdf@noreply.github.com>
CC: Eiko Van Thillo <info@eiko.be>; Author <author@noreply.github.com>
Onderwerp: Re: [spipu/html2pdf] how to automatically add an extra page when the pdf has an odd number of pages (#192)


after each writeHtml of each little html to convert, you can make a test on the current page of the pdf, and add a page if needed

**Comment by spipu** [comment]
```
    if ($html2pdf->pdf->getPage() % 2) {
        $html2pdf->writeHTML('<page pageset="old"></page>');
    };
```

**Comment by spipu** [comment]
as it is not a issue, i close it
