### ISSUE TITLE
 PHP Fatal error:  Class 'spipu\\html2Pdf\\Html2Pdf' not found, in Windows Environment

### ISSUE THREAD

**Issue by gadget00** [spipu/html2pdf#193]
Im using the WAMPstack from Bitnami, and downloaded and used Composer to install the libraries in the folder.  But it simply doesnt work.  This is the error that I get in the error log:

` PHP Fatal error:  Class 'spipu\\html2Pdf\\Html2Pdf' not found in C:\\Bitnami\\wampstack-5.6.28-1\\apache2\\htdocs\\app\\imprimir-forma.php on line 526`

This is how I declare the code in my php file:

```
require_once 'vendor/autoload.php';
   
 use spipu\html2Pdf\Html2Pdf;

$html2pdf = new Html2Pdf('P', 'Letter', 'es');
$html2pdf->writeHTML($html);
$html2pdf->Output("informacion-de-riesgo-$nombre-$apellido.pdf");
```

Am I missing something? or is there a "special setting" for Windows servers?

Thanks in advance for reading this

**Comment by spipu** [comment]
hum, try to use directly the master branche (version : dev-master)

**Comment by spipu** [comment]
the `use` namespace is not good :) it must be in CamelCase

> use Spipu\Html2Pdf\Html2Pdf;
