### ISSUE TITLE
non editable pdf

### ISSUE THREAD

**Issue by sumitkumardey91** [spipu/html2pdf#205]
how can i make non editable  text box or checkbox  at pdf.

**Comment by sumitkumardey91** [comment]
html2pdf/examples/forms.php
 in this example,i want to make non edible textbox and radio button

**Comment by spipu** [comment]
Hum, i think i have not implemented it.
if it is not editable, why doing a form ?

**Comment by sumitkumardey91** [comment]
thanks,
You are right.
but when user fills a form with radio,checkbox,text box etc..
so here want to display user as pdf ,what ever he filled ..
