### ISSUE TITLE
DIV superimposed

### ISSUE THREAD

**Issue by LittleBigFox** [spipu/html2pdf#207]
Hi!

I've a little bug on a PDF:

![superposition](https://user-images.githubusercontent.com/7079779/27729288-963810a0-5d85-11e7-8514-075564f513ae.png)

The structure is:
```
...
<tr><td>- chaufferie : 1</td></tr>
</tbody>
</table>
<div>2 - VMC HYGRO B</DIV>
<table>
<THEAD><TR><TH>Ouvrage</TH> 
...
```
And the CSS is:
```
table   {border-collapse:collapse;width:100%;}
TD      {font-size:3mm;padding-left:1mm;padding-right:1mm;}
TH      {font-size:4mm;padding-left:1mm;padding-right:1mm;}
```
I've found a workaround: deleting font-size on TD/TH put the html in order, but i guess it's not a true solution...
I've try replacing the DIV tag by H1, but no improve.

Have you any hint for resolving?

**Comment by spipu** [comment]
i can not reproduce the pb:

```
<style type="text/css">
table   { border-collapse:collapse;width:100%;}
TD      {font-size:3mm;padding-left:1mm;padding-right:1mm;}
TH      {font-size:4mm;padding-left:1mm;padding-right:1mm;}
</style>
<page>
    <table>
        <THEAD>
            <TR><TH>Ouvrage</TH></TR>
        </THEAD>
        <tbody>
            <tr><td>- chaufferie : 1</td></tr>
        </tbody>
    </table>
    <div>2 - VMC HYGRO B</DIV>
    <table>
        <THEAD>
            <TR><TH>Ouvrage</TH></TR>
        </THEAD>
        <tbody>
            <tr><td>- chaufferie : 1</td></tr>
        </tbody>
    </table>
</page>
```
can you give me a html example with the pb ?

**Comment by LittleBigFox** [comment]
Hi Spipu!

I'd removed the padding for resolving this bug, so i can't give you an exemple now... 

I'll do if i have another bug like this!

Regards,
LBF

**Comment by spipu** [comment]
ok !
i close this issue
