### ISSUE TITLE
5.0 won't install.   

### ISSUE THREAD

**Issue by lwoods** [spipu/html2pdf#208]
I am NOT that versed in Composer but I entered "composer require spipu/html2pdf" and, along with other errors I get the following:
 Problem 1
    - The requested package spipu/html2pdf No version set (parsed as 1.0.0) is satisfiable by spipu/html2pdf[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Now, I don't know what the not about "commits" is all about---and can't find it in the Composer doc, without reading it cover to cover---so I didn't do anything there.  
Since the "install" didn't work I did a "computer update" and it ran to completion, with LOTS of "Installs".
Now, things kinda' work.  Most of the examples work.  Surprisingly, the "examples" folder is INVISIBLE (thru Desktop Server).  I had to move everything to another folder to test the examples.
Anyway, any ideas?  Oh, yes.  I am running under Windows 10.

**Comment by spipu** [comment]
The pb could be your minimum stability in your composer.json file. Can you put here its content ?

What is your PHP version ?

**Comment by lwoods** [comment]
5.5.24

{
    "name": "spipu/html2pdf",
    "type": "library",
    "description": "Html2Pdf is a HTML to PDF converter written in PHP5 (it uses TCPDF). OFFICIAL PACKAGE",
    "keywords": ["html", "pdf", "html2pdf"],
    "homepage": "http://html2pdf.fr/",
    "license": "OSL-3.0",
    "authors": [
        {
            "name": "Spipu",
            "homepage": "https://github.com/spipu",
            "role": "Developer"
        }
    ],
    "require": {
        "php": "~5.4 || ~7.0",
        "tecnickcom/tcpdf": "~6.2"
    },
    "require-dev": {
        "phpunit/phpunit": "~4.0 || ~5.0",
        "phake/phake": "~2.0",
        "squizlabs/php_codesniffer": "~2"
    },
    "suggest": {
        "fagundes/zff-html2pdf": "if you need to integrate Html2Pdf with Zend Framework 2 (zf2)",
        "ext-gd": "Allows to embed images into the PDF"
    },
    "autoload": {
        "psr-4": {
            "Spipu\\Html2Pdf\\": "src/"
        }
    },
    "config": {
        "bin-dir": "bin"
    }
}

**Comment by spipu** [comment]
this is the content of HTML2PDF composer.json, not the content of your composer.json project.

how did you get html2pdf ? 

if you download it or clone it, it is not the good solution.

You must start a new project before, with the command composer init. (look at https://getcomposer.org/doc/03-cli.md#init)

Then, you could add the spipu/html2pdf library

**Comment by lwoods** [comment]
OK.  Now I have a folder with "vendor" in it.  In 'vendor' there are 3 folders; tecnickcom, spipu, and composer.  In spipu I see the examples, test, src, etc. folders.  What level of folders do I move to another site in order to have a functioning set of files for your tool?  The 'html2pdf' folder or the higher leve 'spipu' level?

**Comment by lwoods** [comment]
OK.  So I drug all of the files in 'html2pdf' into the root, where the 'vendor' folder is, and then renamed 'examples' to 'xxx' and the examples work.  The server couldn't even find 'examples' so that is the reason that I had to rename it.  Things seem to be working just fine now.  What am I missing?

**Comment by spipu** [comment]
You have not to move any files, you have just to use the composer autoloader, like in any modern php project.

You may really read composer documentation...

**Comment by dennisheiden** [comment]
Sehr geehrte Kundin,
sehr geehrter Kunde,


leider bin ich zur Zeit verhindert. Ich stehe Ihnen voraussichtlich wieder am 10.07. zur Verfügung.

In Notfällen steht Ihnen Matthias Reuter gerne zur Verfügung:

matthias-reuter@straightvisions.com


Mit freundlichen Grüßen

Dennis Heiden

straightvisions - enhancing the web

Berlin Friedrichshain Dennis Heiden - Pettenkoferstraße 16-18 - 10247 Berlin - Phone +49 (0)30 / 8939 - 8450
Hamburg City Matthias Reuter - Ballindamm 39 - 20095 Hamburg - Phone +49 (0)40 / 99999 - 3020
Hamburg Nord Matthias Reuter - Hasselwisch 11a - 22397 Hamburg - Phone +49 (0)40 / 1817 - 3958

**Comment by lwoods** [comment]
Please help me, Spipu.  Why do I have to use the "composer autoloader" in order to become "modern?"  You applications run just fine without it.

**Comment by lwoods** [comment]
One thing that I didn't specify that might affect this.  Your code will be running on a public hosting site (GoDaddy) and the routines are being called from other PHP scripts.  This is the reason that I needed to know what to pick up.  I don't think that Composer fits in this environment.  And, yes, I will read the Composer doc.

**Comment by spipu** [comment]
my application does not work without it. If you look at examples, you will see that it uses the composer autoloader
