### ISSUE TITLE
Html2Pdf doesn't recognize width of table

### ISSUE THREAD

**Issue by nasrithamer** [spipu/html2pdf#209]
the width of first table is correct but the second table is not 

   <style type="text/css">
	table {
		width: 100%;
		
	}
	.header td{
		width: 50%;
		vertical-align: top;
		padding: 10px;
	}
	.header {
		border-collapse: separate; 
		border-spacing: 20px;
	}
	.text-left{
		text-align: left;
	}
	.text-right{
		text-align: right;
	}
	.text-center{
		text-align: center;
	}
	.separator{
		height: 30px;
		width: 100%;
	}
	.content{
		width: 1400px !important;
		border-collapse: collapse;
	}
	.content td{
		border-right: solid 1px #000;
		border-bottom: solid 1px #000;
		border-left: solid 1px #000;
		padding: 5px;
	}
	.content th{
		border-right: solid 1px #000;
		padding: 5px;
		background-color: #e6e6e6;
		color: #000;
	}
	.tdwithoutborder{
		border: none;
	}
</style>

<page backtop="5mm" backright="10mm" backbottom="5mm" backleft="10mm">
	
	<table class="header">
		<tr>
			<td  class="text-left">
				<h1> Logo</h1>
			</td>
			<td  class="text-right">
				<h1>
					{% if etat == "B" %}
						{% set type_doc = "Brouillon" %}
					{% elseif etat == "D" %}
						{% set type_doc = "Devis" %}
					{% elseif etat == "C" %}
						{% set type_doc = "Bon de Commande" %}
					{% elseif etat == "F" %}
						{% set type_doc = "Facture" %}
					{% endif %}
					
					{{ type_doc }}
				</h1>
			</td>
		</tr>
		<tr>
			<td class="text-right" colspan="2">
				
				<br> {{ type_doc }} : {{ devis.id }}
				<br> Client ID : {{ devis.client.id|default('') }}
				<br> Date de Commande : {{ devis.dateCommande|date('d-m-Y') }}
			</td>
		</tr>
		<tr>
			<td class="text-left">Émetteur</td>
			<td class="text-left">Adressé à</td>
		</tr>
		<tr>
			<td class="text-left" style="background-color: #e6e6e6; border-collapse: separate; border-spacing: 20px;" >
				<h3>{{ company.name }}</h3>
				<br> {{ company.address }}
				<br> {{ company.zip }} {{ company.city }} {{ company.country }}
				<br><br> Accueil : {{ company.phone }}
				<br> Service Clients : {{ company.phone2 }}
				<br> Email : {{ company.email }}
				<br> Web : {{ company.url }}
			</td>
			<td class="text-left" style="background-color: #fff; border: 1px solid #000;">
				<h3>{{ devis.client.name|default('') }}</h3><br>
				{{ devis.client.address|default('') }}<br>
				{{ devis.client.city|default('') }} {{ devis.client.zip|default('') }}<br>{{ devis.client.phone|default('') }}
			</td>
		</tr>
	</table>
	
	<table class="content" width="1400px">
		<thead>
			<tr>
				<th colspan="6" style="background-color: white; border: none; text-align: right;" width="200px">Montants exprimés en Euros</th>
			</tr>
			<tr>
				<th class="text-left" style="border-bottom: solid 1px #000;" width="200px">REF</th>
				<th class="text-center" style="border-bottom: solid 1px #000;" width="200px">Description</th>
				<th class="text-center" style="border-bottom: solid 1px #000;" width="200px">Qté</th>
				<th class="text-center" style="border-bottom: solid 1px #000;" width="200px">Prix Unitaire</th>
				<th class="text-center" style="border-bottom: solid 1px #000;" width="200px">Remise</th>
				<th class="text-right" style="border-bottom: solid 1px #000;" width="200px">Total</th>
			</tr>
		</thead>
		<tbody>
			{% set HT = 0 %}
			{% set TTC = 0 %}
			{% set TTVA = 0 %}
			{% set total = 0 %}
			{% for dd in details_devis %}
			
			<tr>
				<td width="200px">{{ dd.product.refInt|default('') }}</td>
				<td width="200px">{{ dd.product.lable|default('') }}</td>
				<td width="200px">{{ dd.qte }}</td>
				<td width="200px">{{ dd.priceht }}</td>
				<td width="200px">{{ dd.remise }} %</td>
				<td width="200px">
					{% set total = dd.totalht - ((dd.totalht * dd.remise)/100) %}
					{{ total }}
				</td>
			</tr>
			{% set HT = HT + total %}
			{% set TTVA = TTVA + dd.totaltva %}
			
			{% set total = 0 %}
			{% endfor %}
			<tr>
				<td class="text-left tdwithoutborder" colspan="4" width="800px"><b>Date de livraison :</b></td>
				<td class="text-right tdwithoutborder">Total Ht</td>
				<td class="text-right tdwithoutborder">{{ HT }}</td>
			</tr>
			<tr>
				<td class="text-left tdwithoutborder" colspan="4" width="800px"><b>Conditions de règlement :</b> {{ devis.condition }} </td>
				<td class="text-right tdwithoutborder">Total Tva</td>
				<td class="text-right tdwithoutborder">{{ TTVA }}</td>
			</tr>
			<tr>
				<td class="text-left tdwithoutborder" colspan="4" width="800px"><b>Règlement TTC par chèque à l'ordre de Connect envoyé à</b></td>
				<td class="text-right tdwithoutborder">Total</td>
				<td class="text-right tdwithoutborder">
					{% set TTC = HT + TTVA %}
					{{ TTC }}
				</td>
			</tr>
			<tr>
				<td class="text-left tdwithoutborder" colspan="4" width="800px">{{ company.address }} {{ company.zip }} {{ company.city }} {{ company.country }}</td>
				<td class="text-right tdwithoutborder"></td>
				<td class="text-right tdwithoutborder"></td>
			</tr>
			<tr>
				<td class="text-left tdwithoutborder" colspan="4" width="800px"><b>Règlement par virement sur le compte bancaire suivant:</b></td>
				<td class="text-right tdwithoutborder"></td>
				<td class="text-right tdwithoutborder"></td>
			</tr>
			<tr>
				<td class="text-left tdwithoutborder" colspan="4" width="800px">
				Banque:  Banque nom
				</td>
				<td class="text-right tdwithoutborder"></td>
				<td class="text-right tdwithoutborder"></td>
			</tr>
			<tr>
				<td class="text-left tdwithoutborder" colspan="4" width="800px">
				Banque:  Banque nom
				</td>
				<td class="text-right tdwithoutborder"></td>
				<td class="text-right tdwithoutborder"></td>
			</tr>
			
		</tbody>
	</table>
	
</page>

**Comment by LittleBigFox** [comment]
Hi!

Each of yours 6 cells of your second table do 200px, but your table width 1400px... Try putting it to 1200px first.

Secondly, the best way, I think, of not having problems with the width of the table is to declare the width of each cell. I use a class for each column in my case. I don't have more bug with PDF generating since a while like this.

Regards.
LBF

**Comment by orl99** [comment]
Are you sure that just by putting the width in the cells by class fix the problem? Can I just by a tag css selector do it?

**Comment by PROMX2** [comment]
hi
