### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by ooisootuck** [spipu/html2pdf#210]
How can I add watermark in a document.

The watermark is light colored image on the same printing page

**Comment by LittleBigFox** [comment]
Hi ooisootuck!

You can add a background image to your <PAGE> tag. It work like a charm for me.

Kind of example:
`<page pagegroup="new" pageset="new" backimg="water.jpg" backimgx="center" backimgy="middle" backimgw="50%" orientation="P" format="A4" backleft="5mm" backright="5mm" backbottom="5mm" backtop="5mm">`

**Comment by dankrauf** [comment]
For transprent backimg?
Thx before.

**Comment by Samerkassem** [comment]
@LittleBigFox 
What I need to add a watermark TEXT, not image?

**Comment by LittleBigFox** [comment]
@Samerkassem I've never tried, but don't think it's possible yet. Perhaps a feature?
