### ISSUE TITLE
Many tables in the same line

### ISSUE THREAD

**Issue by florianmerle** [spipu/html2pdf#212]
Hi, 

I would like to know how put many tables side by side with HTML2PDF.
It's a really a problem for me...

Thanks in advance for your reponse.
Have a good day, 
Florian

**Comment by LittleBigFox** [comment]
Hi!

If i understand well your question, you can put a table for wrapping other tables in cells... Just don't forget to declare the wrapping table cell width!

**Comment by spipu** [comment]
exactly : use tables to wrap other tables :)
