### ISSUE TITLE
Convert complete html page into pdf

### ISSUE THREAD

**Issue by christophbee** [spipu/html2pdf#213]
Hi!

I want to use html2pdf within a custom TYPO3 plugin. Therefore I pass some variables from my controller to a view template where content is rendered and output in browser as html.

Is it possible to convert that complete page into pdf? By this I mean not with passing the plain html-tags with ->writeHtml($content) to my html2pdf object but I want to convert the complete html page (including all styling) into pdf. 

In fact I need that feature that is shown with the 2 screenshots on your homepage (https://html2pdf.fr/en/home). 

Many thanks and best regards,
Christoph

**Comment by LittleBigFox** [comment]
Hi!

I had the same request, the workaround i found was to send the HTML & CSS content via ajax to generate the PDF... Be sure the content is clean before!

**Comment by christophbee** [comment]
Thanks for the hint!
Do you have a code example how you did this?

**Comment by LittleBigFox** [comment]
I write it from memory, but it's a trick like that ... With JQuery ... But very simplified here!

**HTML**
```
<div id="convert_html">
    <style>
        .rule1{...}
        .rule2{...}
        .rule3{...}
    </style>

    Lorem ipsum dolor sit amet, consectetur adipiscing elit...
</div>
<a href="javascript:goPDF();">Click for pdf</a>
```
**Javascript**
```
function goPDF() {
    $.ajax({
        dataType:"text",
        async:false,
        cache:false,
        type:"POST",
        data:{content:$("#convert_html").html()},
        url: "/pdf/conv.php?call=prepare",
        error: function (jqXHR,text,error){alert(error+" "+text);},
        success: function (data,text,obj){
            document.location.href="/pdf/conv.php?call=show";
        },
    });
}
```
**PHP**
```
<?
require_once dirname(__FILE__).'/../vendor/autoload.php';

use Spipu\Html2Pdf\Html2Pdf;
use Spipu\Html2Pdf\Exception\Html2PdfException;
use Spipu\Html2Pdf\Exception\ExceptionFormatter;

$path = '/var/tmp/test.pdf';

switch($_GET["call"]){
    case "prepare":
        $html2pdf = new Html2Pdf('P', 'A4', 'fr');
        $html2pdf->setDefaultFont('Arial');
        $html2pdf->writeHTML($_POST["content"]);
        $html2pdf->output(path);
        break;
    case "show":
        header("Content-type: application/pdf");
        header("Content-Disposition: inline; filename=test.pdf");
        @readfile(path);
        break;
}

```

**Comment by christophbee** [comment]
Thank you! I will try that way if necessary!
