### ISSUE TITLE
Html2pdf 5.0 issue. TCPDF error: Data has already been output to browser...

### ISSUE THREAD

**Issue by abdeljabarferdjani** [spipu/html2pdf#214]
English Version below ( I would prefer an answer in French but it's ok if you answer in english :) )

---------------------------------------------------------

Salut tout le monde,

C'est la première fois que j'utiliser la librairie HTML2pdf et pour ce faire j'ai essayer de suivre a la lettre les instructions donnees sur le site du developeur. Apres avoir installe Composer et fais toutes les procedures necessaire a l'utilisation de la bibliotheque, Je me retrouve dans le dossier de mon site Internet Avec un dossier Composer dans lequel j'ai le dossier vendor, mes 2 fichiers Composer ( Composer.json et Composer.lock ) et ma page de test php que j'ai appele hello.php.

Dans cette page de test, j'ai entre precisement le code suivant ( Avec les balises php bien sur ) :

----------------------

require __DIR__.'/vendor/autoload.php';

use Spipu\Html2Pdf\Html2Pdf;

$html2pdf = new Html2Pdf();
$html2pdf->writeHTML('<h1>HelloWorld</h1>This is my first test');
$html2pdf->output('test.pdf');

----------------------

et quand je teste cette page sur mon navigateur, j'ai plusieurs Warning de ce type : "  Warning: date(): It is not safe to rely on the system's timezone Settings ... " et surtout j'ai ce warning la : " Warning: Cannot modify header information - headers already sent by (Output... " et cette fatal error qui est detecte : "  Fatal error: Uncaught exception 'Exception' with message 'TCPDF ERROR: Some data has already been output to browser, can't send PDF file' in C:\UwAmp\www\my-app\Composer\vendor\tecnickcom\tcpdf\tcpdf.php on line 2927 ".

Apres avoir cherche la solution dans de nombreux forums, je me tourne vers vous car j'ai encore et toujours le meme Probleme qui persiste.

J'ai compris l'erreur mais ne sait pas la corriger, j'espere que vous saurez m'aider.

Merci d'avance !

PS: Desole pour les accents que je n'ai pas mis dans mon message, mon clavier est en allemand, ca complique les choses.

-----------------------

Hi everyone !

It's the first time that I use html2pdf and in order to install it, I followed every steps that was specified by the developer. After installing Composer and the packages, I found my self with a Folder in my Website called Composer. In this Folder, we can find the vendor Folder, 2 Composer files ( Composer.json and Composer.lock ) and my test that I called hello.php.

In the hello.php file there is exactly this code ( with the php balise of course ) : 

----------------------
require __DIR__.'/vendor/autoload.php';

use Spipu\Html2Pdf\Html2Pdf;

$html2pdf = new Html2Pdf();
$html2pdf->writeHTML('<h1>HelloWorld</h1>This is my first test');
$html2pdf->output('test.pdf');
?>

----------------------

After running it, I had a few warning Messages and an error.

Warnings about the date like this : " Warning: date(): It is not safe to rely on the system's timezone Settings ... " but also warning like this : " Warning: Cannot modify header information - headers already sent by (Output... ". Moreover, I have this fatal error : " Fatal error: Uncaught exception 'Exception' with message 'TCPDF ERROR: Some data has already been output to browser, can't send PDF file' in C:\UwAmp\www\my-app\Composer\vendor\tecnickcom\tcpdf\tcpdf.php on line 2927 ".

After looking for a solution in several forums, I am asking you today to help me on that one because I cannot solve it even if I understood the Problem.

I hope that you will be able to help me,

Thanks in advance,

Best regards !

**Comment by dennisheiden** [comment]
Hi, I don't want to be rude, but writing and asking for answers in a language other than English is unfair to other programmers and help-seeking people. Specially if you are from France, it's not that difficult.

Bien cordialement.

**Comment by abdeljabarferdjani** [comment]
That's exaxtly why I put the same message in english... and as I said above, I'm also ok with an answer in english.

**Comment by spipu** [comment]
Hi,

It is not a html2pdf issue, it is a php configuration issue...

The first link on google gives the solution :

https://stackoverflow.com/questions/16765158/date-it-is-not-safe-to-rely-on-the-systems-timezone-settings

Best regards,

**Comment by dennisheiden** [comment]
Thanks to spipu for the answer.

@abdeljabarferdjani 

Yeah I got that, but you encourage people to write in French which is bad for others with the same problem. Just IMHO.

**Comment by abdeljabarferdjani** [comment]
Thanks for your answers both of you. Especially spipu, it works perfectly now !
