### ISSUE TITLE
Text is overlapping on the first site on the right margin, if using a big div.

### ISSUE THREAD

**Issue by mysecondworld** [spipu/html2pdf#216]
Thank you for the great PDF-Creator, but we are facing a little problem:
The text is overlapping on the first site on the right margin, if you use a big div, which is bigger than one page.

Just compare the attached two files:

[examples.zip](https://github.com/spipu/html2pdf/files/1211187/examples.zip)

The div has got a yellow background. We already tried the latest version!

Thank you!

Btw: We need the DIV only to assign a CSS-Class to the whole Doc. Maybe there is a way to solve this in that direction ... ?!

**Comment by LittleBigFox** [comment]
Hi!

Have you try to put style="width:100%;" on your div?

In Html2PDF, all work better if you put explicitely your width...

**Comment by mysecondworld** [comment]
Hey ;)
Thank you for your reply!
We tried it: Same problem.
That's the output with style="width:100%;":
- https://www.e-shepherd.de/system/_pdf_working.php
- https://www.e-shepherd.de/system/_pdf_problem.php

**Comment by guicara** [comment]
Hello,

I face the same problem, that drive me crazy!
Do you have any idea on how to resolve it?

Thanks,

**Comment by spipu** [comment]
Hi,
a div, like a td or th, can now be greater that a page, it will not work with html2pdf
