### ISSUE TITLE
bullet size in list

### ISSUE THREAD

**Issue by dezomer** [spipu/html2pdf#222]
Hello

is there a way to  change the size of the bullets in list ( the default is too big)

if its not configurable by  .listStyle  is the a way to change the default

Regards & THX in advance

Francois

**Comment by spipu** [comment]
look at example 12, you can use the image that you want, with the css list-style-image

**Comment by octarine-solutions** [comment]
Hi,
I know that this discussion is pretty old but I just had the same issue ...
1/ Set the ul padding and font size to place and size the bullet
2/ Set the size of the text inside the li using any selector (I used span)

`<style type="text/css">`
`<!--`
`.goal-list {`
` font-size: 6pt;`
`  padding-left: -12px;`
`}`

`.goal {`
`  margin-left: 3px;`
`  font-size: 9pt;`
`}`
`-->`
`</style>`

`<ul class="goal-list">`
`  <li><span class="goal">My first goal</span></li>`
`  <li><span class="goal">My second goal</span></li>`
` </ul>`

Hope this help

**Comment by SequelONE** [comment]
Without intervention in the code, nothing will work. I had to replace all the bullets en masse with pictures. The code works well in **Laravel**.

File: `vendor/spipu/htnl2pdf/src/Html2Pdf.php`

On line 4414 `protected function _tag_open_UL($param, $other = 'ul')` code add:
```
        $param['style']['list-style-image'] = 'url(' . public_path() . '\assets\img\bullet.png)';
        $param['cellspacing'] = 0;
```

On line 4515 `protected function _tag_open_LI($param)` code replace:
```
        $inf = $this->_listeGetLi();
        if ($inf[0]) {
            if ($inf[0] === 'zapfdingbats') {
                // ensure the correct icon is used despite external css rules
                $paramPUCE['style']['text-transform']  = 'lowercase';
            }
            $paramPUCE['style']['font-size']       = '4pt';
            $paramPUCE['style']['font-family']     = $inf[0];
            $paramPUCE['style']['text-align']      = 'li_right';
            $paramPUCE['style']['list-style']      = 'none';
            $paramPUCE['style']['width']           = $this->_listeGetWidth();
            $paramPUCE['style']['padding-right']   = $this->_listeGetPadding();
            $paramPUCE['txt'] = $inf[2];
        } else {
            $paramPUCE['style']['font-size']       = '4pt';
            $paramPUCE['style']['padding-top']     = '0';
            $paramPUCE['style']['text-align']      = 'li_right';
            $paramPUCE['style']['list-style']      = 'none';
            $paramPUCE['style']['width']           = $this->_listeGetWidth();
            $paramPUCE['style']['padding-right']   = $this->_listeGetPadding();
            $paramPUCE['src'] = $inf[2];
            $paramPUCE['sub_li'] = true;
        }
```
