### ISSUE TITLE
Tiff image converted into JPG

### ISSUE THREAD

**Issue by bhavin-technobrave** [spipu/html2pdf#223]
Hello,

We are working on High-resolution pdf. in that we use tiff images instead of png with transparency. But it will convert all tiff files into Jpeg files with background and its look not good.

Can you please suggest us what can we do to resolve this problem? You can see the images in the attached file.
[3x4-Photoboard-2(6).pdf](https://github.com/spipu/html2pdf/files/1260233/3x4-Photoboard-2.6.pdf)

**Comment by spipu** [comment]
I think tiff format is not working with TCPDF... PNG can not realy be used ?
