### ISSUE TITLE
Integration with Fusioncharts

### ISSUE THREAD

**Issue by juliocorral** [spipu/html2pdf#224]
Hi,

I'm trying to integrate a chart image generated on the fly with Fusionchart library. Image is generated but, now the problem is add this images to HTML that is converted to PDF with HTML2PDF library. It seems that image is not still saved when HTML call it to import so the first time I run the program the image is not included in the PDF file. Second time image is already on server so is included in the PDF.

Could you help me with this issue? I need to include the image at the same time it is generated and saved in the server.

Thank you in advance

**Comment by spipu** [comment]
try to generate it before, and then generate the html and convert it to PDF
