### ISSUE TITLE
download pdf without preview

### ISSUE THREAD

**Issue by Izmaelo** [spipu/html2pdf#225]
Hi. Im trying to download my pdf archive, but i can.
I use this code:
$content=" HTML CODE........";
    require_once(dirname(__FILE__).'//html2pdf/html2pdf.class.php');
  $archivo = $RFCCliente.'_'.date("d-m-Y").'.pdf';
    $html2pdf = new HTML2PDF('P','A4','fr');
    $html2pdf ->pdf->SetDisplayMode('fullpage'); 
    $html2pdf->WriteHTML($content);
    $html2pdf->pdf->IncludeJS('print(TRUE)');
    $html2pdf->Output($archivo);
----------------------------------------------------------
I have seen that if the file is small it's downloaded without problem.
If i remove last line ($html2pdf->Output($archivo);), it download a empty pdf.

I need to download invoices and this html is very large.
Is there a code for this? maybe like $html2pdf->Download or something like that?
Please help me.

**Comment by spipu** [comment]
look at the doc :p 

https://github.com/spipu/html2pdf/blob/master/doc/output.md
