### ISSUE TITLE
Problem with new line in TD

### ISSUE THREAD

**Issue by poitierjohan** [spipu/html2pdf#226]
Hi,

I have a problem with a TD. My text is in 1 line, but html2pdf put a new line in my cell (TD)
See this picture. The concerned text is in yellow.
![image](https://user-images.githubusercontent.com/19634091/30102259-6e93f7c2-92ef-11e7-906e-91b3ef52111a.png)

How can I resolve this problem ?

Thank you for your help.

**Comment by spipu** [comment]
can you provide an html example ?

**Comment by poitierjohan** [comment]
Hi,

There is an html example :
`<td class="padding" style="width: 30%">
                        <b>{{ inscription.user.completeName }}</b>
                        <br>
                        {{ inscription.user.birthday|date("d-m-Y") }} ({{ inscription.user.ageAt(academicYear|date('Y') ~ "-12-31") }})
                    </td>`

The problem is that the text is too long, I suppose and create a backreturn.
Is it possible to resolved this problem ?
Or... Can I have this : "My name is to..." in place of "My name is too long"
Adapt the text in function of the width of the TD.

Thank you for your following.

(i speek french, better than english)

**Comment by spipu** [comment]
Hello
pour ce qui est de raccourcir le texte, ce sera plus à toi de le préparer la valeur en amont.
par contre, ca m'aurait intéressé d'avoir un exemple complet d'HTML causant le pb (saut de ligne qui en fin de compte n'est pas affiché)
