### ISSUE TITLE
The CSS property "line-height" not apply on table

### ISSUE THREAD

**Issue by marcoshenzel** [spipu/html2pdf#227]
[This feature](https://github.com/spipu/html2pdf/blob/4ca14c01a188e1e88c72eafc1b42a8f9d989f8b4/CHANGELOG.md#320---2009-04-06) was applied on 2009-04-06, but, is broken..

`table { line-height: 10px; }`

**Comment by rajnishcoder** [comment]
**Post HTML code with CSS or try this**
`table tr th, table tr td { line-height: 10px; }`

**Comment by spipu** [comment]
does it fix the pb ?
