### ISSUE TITLE
$kPathUrl not defined

### ISSUE THREAD

**Issue by thomasbethmont** [spipu/html2pdf#23]
Hello,

in tcpdfConfig.php, on line 66, $kPathUrl is set only if $_SERVER['HTTP_HOST'] is not empty. 
then K_PATH_URL constant is defiened that way : 
define('K_PATH_URL', $kPathUrl); 
(line 80)

But $_SERVER['HTTP_HOST'] is not always set (during a CRON, for exemple), resulting in a notice : 
PHP Notice:  Undefined variable: kPathUrl in /var/www/sites/bazarchicv4/library/external/html2pdf/_class/tcpdfConfig.php on line 80

**Comment by juchi** [comment]
Hi,
This bug was fixed some time ago in commit 7bb0990. You can use the latest version of HTML2PDF (currently 4.4.0) and you shouldn't have any trouble about this.
Regards
