### ISSUE TITLE
Table - Break long word doesn't works

### ISSUE THREAD

**Issue by csimpi** [spipu/html2pdf#232]
Hi, thank you for this awesome library!

I would like to generate a table with many contents. 
If a cell size is smaller than a word, the word overflows, through an another cell.

The whole table overflows, the page is smaller than the table:
http://screenshot.co/#!/a8af913a02
>                <style>
>                     table{border-collapse: collapse; word-wrap:break-word; word-break: break-all;table-layout: fixed;width: 210mm;}
>                     td,th{word-wrap:break-word;word-break: break-all;border: 1px solid #000;padding:2px;}
>                </style>

I tried add width to cells also,
The table is fits to the page, BUT the long words overflow in this case:
http://screenshot.co/#!/c45b0bf95d
>                <style>
>                     table{border-collapse: collapse; word-wrap:break-word; word-break: break-all;table-layout: fixed;width: 210mm;}
>                     td,th{word-wrap:break-word;word-break: break-all;border: 1px solid #000;padding:2px;width: 10%}
>                </style>

I'd like this:
![2017-09-27_05-51-46](https://user-images.githubusercontent.com/6192067/30895078-1a9b1790-a348-11e7-8730-29d0f61a4561.png)

Thank you :)

**Comment by spipu** [comment]
I think you will have pbs any way, you try to display too much data on your table...
and dependeing on the lenth of the names, emails, ... it will never works...

**Comment by markfb** [comment]
Was this ever fixed? It's a real shame as the rest of the library works very well but this shortcoming makes it unusable for me.

**Comment by CedLP** [comment]
moi aussi j'ai le même problème
