### ISSUE TITLE
Japanese not work

### ISSUE THREAD

**Issue by nhantam** [spipu/html2pdf#235]
I am working export content to PDF by Japanese. But content not show japanese
Could you help me how do I setting to show Japanese ?

Thanks & Regards

**Comment by LittleBigFox** [comment]
Hello!
According to Google Search, many fonts do not allow the Japanese ... I found that "cid0jp" allows it, many devs use it for TCPDF.
Regards,
LBF

**Comment by spipu** [comment]
exactly : just use the good font :)
