### ISSUE TITLE
css is not interpreted as a browser do

### ISSUE THREAD

**Issue by gdidelot** [spipu/html2pdf#236]
Hello,

I have a full template page which integrate is own css. The generated pdf is not as the html in chrome.
Why ? 

The php :

$template = "path_to_the_html";
$html2pdf = new \Spipu\Html2Pdf\Html2Pdf('P', 'A4', 'fr');
$html2pdf->setDefaultFont("helvetica");
$html2pdf->writeHTML($template);
$html2pdf->output(sprintf('%s', $name), 'F');

The html : 

[freelance-bill.zip](https://github.com/spipu/html2pdf/files/1359779/freelance-bill.zip)

Regards

**Comment by gdidelot** [comment]
For example the following template is properly displyed on Chrome, but the library to generate the pdf file doesn't care about some css properties : 
[freelance-bill.zip](https://github.com/spipu/html2pdf/files/1395064/freelance-bill.zip)

**Comment by LittleBigFox** [comment]
Hello!
Html2Pdf is made to facilitate PDF creation, but cannot respect all CSS & HTML rules ...
For example, I have never managed to apply two css classes on the same element, or good old rules like:
 
`.table > caption + thead > tr:first-child > th`

You need to create simpler rules for your html.
You should also specify the width of your table cell, either relative or absolute:

```
.QTT{width:10%}
.DESCRIPT{width:50%}
...
```

Regards,
LBF

**Comment by gdidelot** [comment]
Hi,

Ok, it will be an significant improvement, I understand the actual project state and I enjoy this package !
Good luck !

Regards
