### ISSUE TITLE
"The output document name [] is not a PDF name"

### ISSUE THREAD

**Issue by khalyomede** [spipu/html2pdf#238]
Following the example : https://github.com/spipu/html2pdf/blob/master/doc/output.md#retrieve-the-contents-of-the-pdf-and-then-do-whatever-you-want

I used this full code :

```php
require(__DIR__ . '/vendor/autoload.php');

use Spipu\Html2pdf\Html2pdf;

$html2pdf = new Html2pdf('P', 'A4', 'en');
$html2pdf->writeHTML('<h1>HelloWorld</h1>This is my first test');
$pdfContent = $html2pdf->output('', 'S');
print_r($pdfContent);
```

And I got the following error :

```
The output document name [] is not a PDF name
```

The exception trace specify that the error comes from the file `/src/Html2Pdf.php` one line 497 :
```
if (strtolower(substr($name, -4))!='.pdf') {
  throw new Html2PdfException('The output document name ['.$name.'] is not a PDF name');
}
```

So I guess your example should precise we need a file name to output the content of the pdf ?

**Comment by spipu** [comment]
you are right, i will fix the doc :)
