### ISSUE TITLE
Table generation takes a very long time

### ISSUE THREAD

**Issue by jbstaebler** [spipu/html2pdf#242]
Generating pdf with a lot of table takes a very long time.

**Comment by spipu** [comment]
how many tables do you have ? and how many pages ?

**Comment by masdim** [comment]
actually i have same issue, i am trying to create 301 row and 6 page look like this attachment 
[asdasd.pdf](https://github.com/spipu/html2pdf/files/1650403/asdasd.pdf)

**Comment by jbstaebler** [comment]
With a 15x5 table on each page, I can generate olny 5 pages before the server times out (2 minutes). 
This is a script generating bus timetables, with a page for each bus stop. 
See attachment. 
[FH.pdf](https://github.com/spipu/html2pdf/files/1651113/FH.pdf)
