### ISSUE TITLE
get twig global exception error: Call to undefined function Spipu\Html2Pdf\mb_convert_case() 

### ISSUE THREAD

**Issue by perisaner** [spipu/html2pdf#243]
I have isolated that the problem appears in this call:
$html2pdf->writeHTML($content);
Where $content is the result of this call:
$content = $twig->render("progressNote_pdf_page.twig", $renderArray);
If I echo the content, the error appears at the bottom of the first rendered page on the browser.
Here is the code:
[the yah(...) lines print to the error_log, they are not the probem]

$renderArray = array('page'                           => $page,
                         'cur_note'                       => $note
                        );
    $content = $twig->render("progressNote_pdf_page.twig", $renderArray);
    echo $content;
    $html2pdf = new Html2Pdf('P', 'LETTER', 'en');
    yah("86");  **This line prints to error_log**
    $html2pdf->writeHTML($content);
    yah("88"); **this line does not print and everything below it does not run**
    ob_clean();
    $client = $note->getClientObject();
    yah("comcareParseNoteRequest===>".$dirname."/".$client.getFullNameForPDF()."_".$note->getDoSForPDF());
    $html2pdf->output($dirname."/".$client.getFullNameForPDF()."_".$note->getDoSForPDF()."pdf", 'F');

**Comment by perisaner** [comment]
OKAY, my  husband ROCKS! The problem is, apparently, 
<ul>
  <li>
    Some text
  </li>
</ul>
When that code is commented out, the pdf gets made. I'll redefine how I list that data.
In addition, the fieldsets and legends to not print properly on the pdf either. Again, no problem, I will redefine the html there too.  Otherwise, this is a GREAT product! Thank you so much for it!

**Comment by spipu** [comment]
you muse have the mbstring php extension to use html2pdf

`sudo apt-get install php7.0-mbstring`
