### ISSUE TITLE
How to add a image in header or footer?

### ISSUE THREAD

**Issue by mamingxing** [spipu/html2pdf#244]
I'd like to add a image into the header. It seems support any of the html in this section. 
Anyone can help to give a tip?
Best!

**Comment by h10n** [comment]
hi
just put the <img> tag inside the <page_header> or <page_footer> tag

**Comment by mamingxing** [comment]
Thank you for your comment.
We still have some problem when using the images in the page header or footer. When we put the img tag in that section, only the img path showed.
Our code like this:
$image = new \Think\Image();
$image->open(/Public/Home/img/logo.png);
$execStr_personal = 'html2pdf/h2p --page-size A4 --header-spacing 5 --header-left "$image" --header-right "Personalized Gene Test Report" --header-line --margin-top 1.5cm --footer-line --footer-center "[page]/[toPage]" http://'.$_SERVER['HTTP_HOST'].U('Home/Inspection/showPdfHtml',array('code'=>$code_num,'p_type'=>'personal','e_code'=>$e_code)).$filePathTop.'/Pdfpersonal/'.$code_num.'.pdf';
Could you please kind give a simple demo code on how to add the image?
Thank you so much!

**Comment by spipu** [comment]
it seems that you are not on the good project :)
