### ISSUE TITLE
Use common sidebar

### ISSUE THREAD

**Issue by sumantacn** [spipu/html2pdf#246]
I am very happy to use this plugin. If you can help me in this issue it would be great and thankful.

How I can use common sidebar for every page. I have seen HTML2PDF have page_header and page_footer for common header and footer but what I need to do to use common sidebar.

Check this example http://digitalrevolver.com/product/understanding-cisco-cloud-fundamentals-cldfnd-v1-1/?wcppdf_export=pdf. If content is fit to single page, PDF is fine.

**Comment by spipu** [comment]
you can put the sidebar in you page_header tag, and do wnat you want :)
