### ISSUE TITLE
how to open in new tab?

### ISSUE THREAD

**Issue by nadeem14375** [spipu/html2pdf#248]
Can anyone guide me how to open / output the pdf to a new tab?

**Comment by spipu** [comment]
this is not about html2pdf. It just about how to open a link in a new tab in html...
look at the target attribute of you **a** tag.

**Comment by reinhardjung** [comment]
I do not use an html-TAG :-(
What am i doing wrong?


$html2pdf->WriteHTML($htmlPDF);
$html2pdf->output($myFileName_SAVE.'.pdf');

$html2pdf = new Html2Pdf('P', 'A4', 'de', true, 'UTF-8');
$html2pdf->pdf->SetDisplayMode('real');
$html2pdf->pdf->SetAuthor($theClient_['name']);
$html2pdf->pdf->SetTitle($myFileName_SAVE.'.pdf');
$html2pdf->pdf->SetSubject($theClient_['info']);
$html2pdf->setDefaultFont('Helvetica'); // fixme rju 2019-12-10: Calibri noch nach installieren

include 'templates/header.php';
include 'templates/receipt.php';
include 'templates/footer.php';

$html2pdf->WriteHTML($htmlPDF);
$html2pdf->output($myFileName_SAVE.'.pdf');

**Comment by reinhardjung** [comment]
:-(((

https://stackoverflow.com/questions/39080285/html2pdf-target-blank

**Comment by reinhardjung** [comment]
Does anyone can help me please with this?
I know that i can use a "target" in a LINK, but i do not use a Link/HREF
So i do not know how to open the PDF in a new tab :-(

https://github.com/spipu/html2pdf/blob/master/doc/output.md
So until now i use: $html2pdf->output($myFileName_SAVE.'.pdf','I');
