### ISSUE TITLE
Joomla 3.X

### ISSUE THREAD

**Issue by nicouby** [spipu/html2pdf#249]
Hi,

How Can I use it in Joomla 3.x ?

**Comment by dennisheiden** [comment]
There many ways to use it in Joomla, like installing as a Joomla library.
I prefer a simpler implementation:

1) Create a plugin, module or component.
2) Copy the html2pdf files to a folder within you component like "pdf_printer".
3) Follow the instructions here: https://github.com/spipu/html2pdf/blob/master/doc/install.md
4) Create a printer class or call html2pdf like in the documentation:

`
// Version 1.0.2

defined('_JEXEC') or die;

// http://html2pdf.fr/de/example
require_once(__DIR__.'/printer/vendor/autoload.php');

use Spipu\Html2Pdf\Html2Pdf;
use Spipu\Html2Pdf\Exception\Html2PdfException;
use Spipu\Html2Pdf\Exception\ExceptionFormatter;


class printer{
    
    private $p = false;
    private $header = false;
    private $footer = false;
    
    function __construct() {

        $oben=15;    //mT
        $unten=15;   //mB
        $links=25;   //mL
        $rechts=25;  //mR http://wiki.spipu.net/doku.php?id=html2pdf:de:v4:6_margins
        
        $this->p = new \HTML2PDF('P', 'A4', 'de', true, 'UTF-8', array($links, $oben, $rechts, $unten));
        $this->header = ZEUS::$params->component->get('pdf_header'); 
        $this->footer = ZEUS::$params->component->get('pdf_footer'); 
        
    }
    
    public function print_to_file($body,$name){
        
        return $this->printPDF($body,$name,'F');
        
    }
    
    public function print_to_output($body,$name){
        
        return $this->printPDF($body,$name,false);
        
    }
    
    public function printer_clean(){
        
    }
    
    private function printPDF($html,$pdf_name,$option = 'F'){
        
        $pdf_name = str_replace('.pdf','',$pdf_name);
        $css = '<style>'.file_get_contents(JPATH_COMPONENT_ADMINISTRATOR.'/assets/css/printpdf.css').'</style>';
        $path = JPATH_COMPONENT_ADMINISTRATOR.'/data/tmp/'.$pdf_name.'.pdf';
      
        try
        {
            
            // $html2pdf->setModeDebug();
            // ADD HEADER & FOOTER
            //http://stackoverflow.com/questions/35985904/i-want-to-set-header-and-footer-in-pdf-using-mpdf
            
            //$this->p->SetHTMLHeader($this->header,'E');
           // $this->p->SetHTMLFooter($this->footer,'F');
            
            $this->p->setDefaultFont('Arial');
            // http://wiki.spipu.net/doku.php?id=html2pdf:de:v4:5_page
   
            
            $pages = explode('<pagebreak>',$html);
            $html = array();
            foreach($pages as $p){
                
                if(empty($p))continue;
                
                $html[] =   '<page backtop="55mm" backbottom="25mm"  >'
                        .'<page_header>'
                            .$this->header
                        .'</page_header>'
                        .'<page_footer>'
                            .$this->footer
                        .'</page_footer>'
                         .$css
                         .$p
                    .'</page>';
                
            }
            
            $html = implode('',$html);
                
            $this->p->writeHTML($html, isset($_GET['vuehtml']));
     
            $file = $this->p->Output($path, $option);
            
        } 
        catch(HTML2PDF_exception $e) {
            
            // write to logfile
            ZEUS::logR('error','PRINTING PDF IN PRINTER.CLASS: '.$e);

        }
        
        return ($option == 'F') ? $path : $file;
        
    }
}`


I hope this gives you an idea how to use it in Joomla, there are surely other better / simpler solutions  available. For me, I am going to create a html2pdf-Joomla library for my next projects in the future, then I'm able to use it across my components / plugins.
