### ISSUE TITLE
TCPDF ERROR: Some data has already been output, can't send PDF file

### ISSUE THREAD

**Issue by eved42** [spipu/html2pdf#25]
Bonjour à tous,

merci de continuer à faire vivre ce projet, je ne connaissais pas du tout et après quelques recherches sur le net, je suis tombée dessus.

Quand j'essaie d'utiliser votre class, j'ai cette erreur : 
*TCPDF ERROR: Some data has already been output, can't send PDF file*

Voici mon code : 
```
$html2pdf = new HTML2PDF('P', 'A4', 'fr', true, 'UTF-8');
$html2pdf->setDefaultFont('Helvetica');
$html2pdf->pdf->SetDisplayMode('fullpage');
$html2pdf->WriteHTML($tpl);     // $tpl est ma chaine html
$html2pdf->Output('test.pdf');
```
J'utilise votre class sur un projet en local pour le moment avec Wamp. Une idée d'où ça peut venir ?
Merci.
________________________________________

When I try to use your class, I have this error : 
*TCPDF ERROR: Some data has already been output, can't send PDF file*

Here is my code : 
```
$html2pdf = new HTML2PDF('P', 'A4', 'fr', true, 'UTF-8');
$html2pdf->setDefaultFont('Helvetica');
$html2pdf->pdf->SetDisplayMode('fullpage');
$html2pdf->WriteHTML($tpl);     // $tpl is my html string
$html2pdf->Output('test.pdf');
```
I use your php class on a local project with Wamp. Any idea where it comes from ?
Thanks.

**Comment by eved42** [comment]
Cela marche si je change j'enregistre le PDF sur le serveur : 
```
$html2pdf->Output('../resources/pdf/test.pdf', 'F');
```
Ce n'est pas exactement ce que je voulais mais bon, ça marche.
___________________________________
It works if I save the pdf on the server : 
```
$html2pdf->Output('../resources/pdf/test.pdf', 'F');
```
It isn't what I expected but it works.

**Comment by boussou** [comment]
TCPDF ERROR: Some data has already been output, can't send PDF file 

ce n'est pas une erreur TCPDF.
ca veut simplement dire que la page en question contient des caractères **AVANT** le code de output()

il faut aucun echo, ni ligne vide ;-)

**Comment by eved42** [comment]
Merci pour la réponse, mais c'est totalement impossible dans mon projet lol. J'ai tout un traitement de fait sur les données que j'affiche, je saute des lignes pour que mon code soit visible...

En gros, il faudrait que ce code soit dans un fichier à part ?
```
// Conversion en PDF
$html2pdf = new HTML2PDF('P', 'A4', 'fr', true, 'UTF-8');
$html2pdf->setDefaultFont('Helvetica');
$html2pdf->WriteHTML($tpl);
$html2pdf->Output($file);
```

**Comment by boussou** [comment]
tu ne peux renvoyer qu'un seul type de contenu à la fois.
 - soit du texte
 - soit un pdf

les données que t'affiche, envoie les dans un fichier texte (un log)
parce que je suppose que le but de ta fonction est de renvoyer un PDF.

une astuce: tu peux utiliser ob_start() au debut de ta page (sans aucun code html avant!)
mais ca ne doit pas t'empecher de nettoyer les messages affichés

**Comment by boussou** [comment]
il faudrait fermer ce cas, car ce n'est pas un bug de html2pdf

**Comment by eved42** [comment]
Tant pis je vais rester sur le fonctionnement qui consiste à ouvrir le pdf dans un nouvel onglet. L'utilisateur pourra toujours l'enregistrer sur son pc.

En gros, les gens remplissent un formulaire, j'enregistre des données en bdd et je génère le pdf qui affiche les données. Pour le pdf, j'utilise un template tout prêt que je remplis dynamiquement avec mes variables et j'utilise déjà ob_get_contents(); pour récupérer le code html de ce template pour l'intégrer dans le pdf.

Donc voilà, c'est un peu compliquer de faire fonctionner les deux ensemble mais ça marche bien avec cette méthode donc je pense rester là-dessus.

Merci pour vos précisions.
