### ISSUE TITLE
Chinese is not supported

### ISSUE THREAD

**Issue by bitores** [spipu/html2pdf#250]
Chinese is not supported？

**Comment by 52down** [comment]
插个中文字体进去，就支持了

**Comment by eroy4u** [comment]
如何插？

**Comment by spipu** [comment]
just by reading the doc ;)
https://github.com/spipu/html2pdf/blob/master/doc/font.md

but you may also need to give me a local csv file that i will add in the next release in this folder : https://github.com/spipu/html2pdf/tree/master/src/locale
