### ISSUE TITLE
is it possible to show html2pdf output in iframe or DIV?

### ISSUE THREAD

**Issue by Mayco-Andrey-Ranghetti** [spipu/html2pdf#251]
Hi.

I will like to show PDF in an iframe or a div or another way . today, I only can  to see in full tab.

**Comment by Pitoyable** [comment]
Hi, with this you'll create an iframe with the preview of the pdf :

var pdf = new  jsPDF();
var source = document.body;

html2pdf(source, pdf, function(pdf) {
                var iframe = document.createElement('iframe');
                iframe.setAttribute('style', 'position:absolute;right:0;top:0;bottom:0;height:100%;width:50%;');
                document.body.appendChild(iframe);
                iframe.src = pdf.output('datauristring');
}

**Comment by Mayco-Andrey-Ranghetti** [comment]
Thanks.

**Comment by 37ch4** [comment]
I get the same error **Cannot read property 'inner' of null ....**
