### ISSUE TITLE
barcode EAN13

### ISSUE THREAD

**Issue by yangweijie** [spipu/html2pdf#254]
![image](https://user-images.githubusercontent.com/1614114/33306569-0c9e2dda-d44e-11e7-8e35-34db201fc706.png)

how to generate a barcode like pci above? number  longer than  bar?

**Comment by spipu** [comment]
Hi,
HTML2PDF does not implement barcode directly, it use the barcode generator of TCPDF.
And it seems that TCPDF does not support this one.

you can find the list of the supported barcodes here : https://github.com/spipu/html2pdf/blob/master/doc/barcode.md
