### ISSUE TITLE
how to handle widows and orphans?

### ISSUE THREAD

**Issue by orphi** [spipu/html2pdf#255]
dear all,

is there any way to handle widows and orphans in long text pdf's? 

thank you so much!

**Comment by spipu** [comment]
what do you mean ?

**Comment by orphi** [comment]
When I have a long text over a lot of pages, I want to handle how paragraphs break. Sometimes there is just 1 row on the next site, I want it to have at least 2 rows. In CSS you can handle it with orphans and widows, but it doesn't work with html2pdf. Is there another workaround for it?

**Comment by spipu** [comment]
it is not implemented, sorry
