### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by rakening** [spipu/html2pdf#256]
Hi,

Work in PHP : 7.1.11
Dont work in PHP : 7.2

Warning: count(): Parameter must be an array or an object that implements Countable in C:\...\vendor\spipu\html2pdf\src\Locale.php on line 78

Idea ?

Best regard

**Comment by JeanOctave** [comment]
the issue, it updgrade of php of 7.1.11 to 7.2 for solved this issues in locale.php, in place of:
`$line = fgetcsv($handle);
            if (count($line)!=2) {
                continue;
            }`
add : 
`$line = fgetcsv($handle);
            if (null != $line && count($line)!=2) {
                continue;
            }`
and why this issue? i don't know but this solution work, good luck :)

**Comment by ecolotero** [comment]
Me funciono, de la siguiente manera:
// $line = fgetcsv($handle); if (count($line)!=2) { continue; }
    $line = fgetcsv($handle); if (null != $line && count($line)!=2) { continue; }
Gracias.!

**Comment by peter450** [comment]
👍  Fonctionne parfaitement dans PHP 7.2 et 7.1 
// $line = fgetcsv($handle); if (count($line)!=2) { continue; }
$line = fgetcsv($handle); if (null != $line && count($line)!=2) { continue; }
Merci !

**Comment by MicheleAnnunziata** [comment]
I heve the same issue after the migration to php 7.2, spipu/html2pdf v5.2 don't work  
`// get the positions of the end of the table
            $x = self::$_tables[$param['num']]['curr_x'] + self::$_tables[$param['num']]['width'];
            if (count(self::$_tables[$param['num']]['height'])>1) {
                $y = $this->_margeTop+self::$_tables[$param['num']]['height'][count(self::$_tables[$param['num']]['height'])-1];
            } elseif (count(self::$_tables[$param['num']]['height']) == 1) {
                $y = self::$_tables[$param['num']]['curr_y']+self::$_tables[$param['num']]['height'][count(self::$_tables[$param['num']]['height'])-1];
            } else {
                $y = self::$_tables[$param['num']]['curr_y'];
            }`

Any idea?
Best regads

**Comment by MicheleAnnunziata** [comment]
> I heve the same issue after the migration to php 7.2, spipu/html2pdf v5.2 don't work
> `// get the positions of the end of the table $x = self::$_tables[$param['num']]['curr_x'] + self::$_tables[$param['num']]['width']; if (count(self::$_tables[$param['num']]['height'])>1) { $y = $this->_margeTop+self::$_tables[$param['num']]['height'][count(self::$_tables[$param['num']]['height'])-1]; } elseif (count(self::$_tables[$param['num']]['height']) == 1) { $y = self::$_tables[$param['num']]['curr_y']+self::$_tables[$param['num']]['height'][count(self::$_tables[$param['num']]['height'])-1]; } else { $y = self::$_tables[$param['num']]['curr_y']; }`
> 
> Any idea?
> Best regads

In PHP 7.2  count() method count all elements in an array, or something in an object (Countable) . To solve this issue i have been added this control:
`if ( (is_array(self::$_tables[$param['num']]['height']) || self::$_tables[$param['num']]['height'] instanceof Countable) && count(self::$_tables[$param['num']]['height'])>1)`

To get a solution i combined  is_array method and instanceof Countable interface control. I'm not sure that is the best solution if anyone have another please tell us

**Comment by danisetg** [comment]
Hi, I am facing this same issue on php 7.2.9. Have this been solved in any recent version of the vendor? I'm not really fan of modifying a vendor.

**Comment by LittleBigFox** [comment]
Hi!

I'm in PHP 7.2 / 7.3, i don't have this bug, with the last version...

Regards,
LBF

**Comment by Eufronio** [comment]
After fixing with the code line mentioned above, now when I generate the pdf it gives me an error.

in PHP version 7.3.2

"TCPDF ERROR: Some data has already been output, can't send PDF file"

**Comment by LittleBigFox** [comment]
Hi!

This message occurs when something is sent before the PDF generation, don't you have an "echo" or a warning/error sent? 

Try to comment the html2pdf output method for seeing, or look at yours logs.

Regards,
LBF

**Comment by Eufronio** [comment]
the error was before generating the pdf, but I think it was the way I started the ob_start ();
, also modifying the line, in locale.php
$ line = fgetcsv ($ handle); if (null! = $ line && count ($ line)! = 2) {continue; }

So, I'm resolved in the following way
<? php
ob_start ();

$ html = '';
echo $ html;
$ html = ob_get_clean ();
require_once ('html2pdf / html2pdf.class.php');

$ mipdf = new HTML2PDF ('P', 'A4', 'is', 'true', 'UTF-8');
$ mipdf-> pdf-> SetDisplayMode ('full page');
$ mipdf-> writeHTML (

'<page footer = "page; date;">

<h1> hello world!</ h1>
</ page> ');
$ mipdf-> Exit ('packing.pdf');
?>


thank you!

**Comment by ahmdjazuli** [comment]
> the issue, it updgrade of php of 7.1.11 to 7.2 for solved this issues in locale.php, in place of:
> `$line = fgetcsv($handle); if (count($line)!=2) { continue; }`
> add :
> `$line = fgetcsv($handle); if (null != $line && count($line)!=2) { continue; }`
> and why this issue? i don't know but this solution work, good luck :)

Nice :v it's work for me :) thanks youuuu

**Comment by zabithnm** [comment]
> (is_array(self::$_tables[$param['num']]['height']) || self::$_tables[$param['num']]['height'] instanceof Countable)

Thanks for the tip. it worked
