### ISSUE TITLE
How can I protect my generated pdf and prevent it from being modified? and if there is any way for the pdf to come out as an image instead of editable text

### ISSUE THREAD

**Issue by juliorm98** [spipu/html2pdf#257]
como puedo proteger mi pdf generado y evitar que pueda ser modificado? y si hay alguna manera de que el pdf salga como imagen en vez de texto editable Editar

How can I protect my generated pdf and prevent it from being modified? and if there is any way for the pdf to come out as an image instead of editable text

**Comment by LittleBigFox** [comment]
Hi!

You can use the last argument of HTML2PDF constructor, it's for the use of PDFa (set to true)

Regards,
LBF

**Comment by spipu** [comment]
but event if you try to do this, it is always possible to rebuild a PDF without this protection...
