### ISSUE TITLE
Margins not working properly

### ISSUE THREAD

**Issue by hscorrea** [spipu/html2pdf#258]
Some words are off the limits I've set (```30, 33.9, 20, 12.8```).
It only happens when paragraphs are justified.

Version 4.03

![image](https://user-images.githubusercontent.com/7349960/34410452-9b70121e-ebb7-11e7-9004-a63d7bf73b10.png)

**Comment by spipu** [comment]
hi, do you have a ligh html example ?
it seams to appen when the last word is in a different tag

**Comment by hsangalli** [comment]
Hi, @spipu . This was the piece of code which gave me that problem:
``` html
<p class="Contrato" style="text-align: justify;"> <strong>4.3 </strong>A decretação de falência ou o deferimento de pedido de recuperação judicial de qualquer das <strong>Partes</strong> implicará rescisão automática e de pleno direito deste contrato, devendo o(s) <strong>Equipamento(s) </strong>ser restituído(s) à <strong>OMITTED</strong>, nas condições em que foram recebidos pela <strong>COMODATÁRIA</strong>.</p>
```
Thank you for developing and maintaining this project!

**Comment by eliemarjunior** [comment]
Hi @hscorrea, I've "solved" this issue putting &nbsp; between elements and forcing a new line. You can try do this. I hope that it's help you.

**Comment by hscorrea** [comment]
Thank you so much for your input @eliemarjunior 😃 , but at that time I solved the issue with the help of another library. There were too many different documents and they were generated automatically, so it was not viable to take this approach.

**Comment by spipu** [comment]
it will be fixed in the next release
