### ISSUE TITLE
Can i use tags like <strong> <b> for html2pdf?

### ISSUE THREAD

**Issue by sivanagak** [spipu/html2pdf#259]
If i use any of those tags in html. Entire pdf coming as strong or bold letteres. Please help me with this!

**Comment by ryandgetz** [comment]
Broken tag? Double check to make sure every opening tag has a closure in the correct position in the hierarchy.

**Comment by spipu** [comment]
can you give an html example ?

**Comment by gtamborero** [comment]
`<strong>text</strong>` works correctly!
