### ISSUE TITLE
format parameter should not be converted to lowercase

### ISSUE THREAD

**Issue by MaksOta** [spipu/html2pdf#260]
I found that if you set the parameter: format=A3 it gets ignored when TCPDF tries to set the format.
That is because line 2700 of Html2Pdf.php changes the format to a3. 
 
            $format = null;
            if (isset($param['format'])) {
                $format = strtolower($param['format']);
                if (preg_match('/^([0-9]+)x([0-9]+)$/isU', $format, $match)) {
                    $format = array(intval($match[1]), intval($match[2]));
                }
            }

Then when setPageFormat method on tcpdf tries to find the size of the format

`$pf = TCPDF_STATIC::getPageSizeFromFormat($format);`

the lookup array ignores `'A3'=> array(  841.890,  1190.551),`
and returns the default since it is looking for a3 instead of A3.

**Comment by spipu** [comment]
hi, i will fix it :)

**Comment by spipu** [comment]
Hi,
it will be fixed in the next release
