### ISSUE TITLE
locale.class.php error

### ISSUE THREAD

**Issue by midaco** [spipu/html2pdf#263]
Hi , 

I think i have a little problem when i try to output pdf file . 
![unbenannt](https://user-images.githubusercontent.com/35540955/35062328-3fd72c54-fbc4-11e7-811e-3261be5db0d3.jpg)

Here its the line code from file 
`        // load the file
        self::$_list = array();
        $handle = fopen($file, 'r');
        while (!feof($handle)) {
            $line = fgetcsv($handle);
            if (count($line)!=2) continue;
            self::$_list[trim($line[0])] = trim($line[1]);
        }
        fclose($handle);
    }
And line 68 its this one 
            if (count($line)!=2) continue;

Thanks in advance for your help

**Comment by LittleBigFox** [comment]
Hi!

I've had the same issue when i passed to PHP7.2. 

For overridding this, i had add a test:

```
// load the file
self::$list = array();
$handle = fopen($file, 'r');
while (!feof($handle)) {
     $line = fgetcsv($handle);
     $line = is_array($line)?$line:[];  // <----- This line
     if (count($line)!=2) {
         continue;
     }
     self::$list[trim($line[0])] = trim($line[1]);
}
fclose($handle);
```

Regards,
LBF

**Comment by midaco** [comment]
working like a charm .... thanks mate .

**Comment by LittleBigFox** [comment]
@spipu If you want to use it in php7.2
