### ISSUE TITLE
Does not generate pdfs and throws 500 errors

### ISSUE THREAD

**Issue by neoproyects** [spipu/html2pdf#264]
Good evening
I have a problem, I have created a tab in HTML. The export to PDF in local does it perfectly but after uploading the files (folder vendor, etc) to production the same information with which I generate the content of the pdf Fail. At all times I gave 500 failures (internal server).
I do not understand exactly what happens since I have been removing elements from the HTML file and I generated the pdf well but after adding the rest of the information does not work. I insist, in my local it works perfectly.

Both on the server and in the local I use php 5.6

What explanation can be given to it?

**Comment by amiles93** [comment]
How many pages are you trying to make - I can't seem to get more than 20

**Comment by neoproyects** [comment]
Good morning.
Thx for your answere, i'm making 2 but when i looked the error i remove 1 page and some parts of first page (i did this for check the error). Also, i changed some tags of html because in the moment is parse HTML to PDF i supposed that the problem is for some tag, like: table -> tr -> td -> div -> table -> tr ->td ->span
At the moment i don´t  understand why in local is working and production dosen't print the page.

Thx for you help.

**Comment by LittleBigFox** [comment]
Hi!

If you can access to your "apache / nginx / other" errors logs, you should have the exact error? It can be useful...

**Comment by neoproyects** [comment]
In the apache logs there is no information on why the 500 error. What I have been testing is, within my template, to show the blocks of information that I need one by one. I've noticed that:
Case 1:
* Print the information in a single html (div) tag, the result is that it is printed up to a certain point since when adding the next information element, the 500 error is generated.

Case 2:
* Print the information with the original structure of the template HTML, only allows me to add certain blocks of information (less quantity than case 1), after that limit throws 500 error.
* To the point where I can see the pdf I am alternating the block of information that I want and I can see the pdf.

I thought it could be due to some label that has not closed well but it is not like that. I think it's because the information load (of the first page) can not be processed in its entirety and it gets to render a point and it is cut.

what is exactly de problem? Memory server, setup php.in?

thx

**Comment by LittleBigFox** [comment]
Hi!

It may be because you have an unclosed tag (like a </TR></TD> for example).
Or it may be because you use a non-implemented tag (like <CENTER>...).
You could export the HTML to a file before create your pdf, and post the generated file?

Regards,
LBF

**Comment by neoproyects** [comment]
Good Morning

Thank, at the end i could resolve my problem. Memory system php.

**Comment by mittultechnobrave** [comment]
Hi @neoproyects  I am following your thread and I have around 23 pages and I am having the same problem 500 Internal Error once the page gets lot of html pages. If I generate HTML its working fine but once I convert it to PDF, its giving me 500 error. 

I have also tried to increase my php memory limit .. maximum execution time by setting it to -1 in my WHM panel .. made all the changes but yet it does not work so far. 

Can you guide me what should I do now ?

**Comment by mittultechnobrave** [comment]
> Hi!
> 
> It may be because you have an unclosed tag (like a for example).
> Or it may be because you use a non-implemented tag (like
> ...).
> You could export the HTML to a file before create your pdf, and post the generated file?
> 
> Regards,
> LBF



> Hi!
> 
> It may be because you have an unclosed tag (like a for example).
> Or it may be because you use a non-implemented tag (like
> ...).
> You could export the HTML to a file before create your pdf, and post the generated file?
> 
> Regards,
> LBF

I guess unclosed tag will/should give PHP exception error (which actually is giving) instead of giving 500 Internal server error.

**Comment by neoproyects** [comment]
Good afternoon

Another error I had found was: use the tags to add html content in the header and footer. In one of them has launched the information that produces a jump on the second page, at that time the closing of the label was on the other page and I generated an error 500 (it was no longer a memory-related issue).
I hope it helps.

Thank you.

**Comment by mittultechnobrave** [comment]
@neoproyects  Thanks for the prompt reply. 
Not sure whether this is causing an issue or not. As I am generating PDF section wise. 
The thing is, I am neither getting PHP error nor APACHE LOG ERROR. 
Hence I am unable to find the chunk of code which is causing this. Same thing working fine for me in local server. So I am confused how to solve.
