### ISSUE TITLE
Maximum pages?

### ISSUE THREAD

**Issue by amiles93** [spipu/html2pdf#265]
Hello,

It seems I can't generate more than 20 pages. 

Is there a workaround to this. I still am running the 2016 march version - has this been addressed since then? I need to create a document of around 40 pages

**Comment by LittleBigFox** [comment]
Hi!

I had already generate a more than fifty pages doc, but you have to use the less table you can... Table building is quite slow on html2pdf...

**Comment by amiles93** [comment]
Unfortunately there are tables on each page :/ Would upgrading increase the pages i could generate ?

**Comment by amiles93** [comment]
Using 4.5.1 currently - but I am weary about upgrading and causing potential issues

**Comment by LittleBigFox** [comment]
Hi!

I don't think upgrading now will increase speed... But you could use a pdf merger like this one or other:

https://github.com/hanneskod/libmergepdf

You could generate smallers PDF, then merge them... It might do the trick?

Regards,
LBF
