### ISSUE TITLE
Word Wrapping

### ISSUE THREAD

**Issue by andrewhawk1ns** [spipu/html2pdf#266]
Is this something that is supported yet ? I have tried word-break: break-all, word-wrap:break-word, on spans / the wrapping td, with content that is inside a width defined td to no avail.

I have dynamic content so using PHP's wordwrap() function isn't very convenient.

![image](https://user-images.githubusercontent.com/7673581/35349473-030ed91c-0109-11e8-909e-9021437a9fb2.png)

**Comment by jhonNumpaque** [comment]
http://php.net/manual/es/function.wordwrap.php

**Comment by spipu** [comment]
sorry, wordwrapping is not implemented.
