### ISSUE TITLE
Table TD Styles

### ISSUE THREAD

**Issue by DanielZambranoC** [spipu/html2pdf#267]
It's possible to handle table/td styles via <style> tag?

Trying to show a table with some rows and cols but cant handle td width via style tag.

This is important because we're trying to save info that user store using any rich text editor, we need that tables width 100% of the page and their columns at least auto set.

**Comment by LittleBigFox** [comment]
Hi!

There is no problem for using table, td, th or others css in html2pdf. Some CSS aren't allowed, but very few.

Some rules must be used: for each TD/TH, use a width (%, mm, px), etc. Try not to use "#table>TR>TD" or other recent CSS rules, or nested  ".table_test .tr_test .td_test", they might not be calculated.

If you have graphical errors, give us your html result and CSS, this may help.

Regards,
LBF
