### ISSUE TITLE
Question mark as some special characters

### ISSUE THREAD

**Issue by MannySVK** [spipu/html2pdf#268]
Hello, thanks for wonderful library.

However, i've found some bug with font or unicode - some characters like "č" are not showed properly. HTML2PDF draws them as "?" (question mark). I don't know why, because other characters like "š" are working great. I am using the latest version of HTML2PDF and default font. The problem is also with character "ň" for example. What can I do about it to show it properly? Thanks for any kind of help, i am stacked.

**Comment by lfjimenez** [comment]
Hi, I have the same problem with a money simbol, did you find a way to change the character? in my case is the 
Símbolo | ₡
-- | --

**Comment by LittleBigFox** [comment]
Hi!

Have you try to change the charset? UTF-8 seems to have these...

http://www.utf8-chartable.de/unicode-utf8-table.pl?start=256&unicodeinhtml=dec

`$html2pdf = new Html2Pdf('P', 'A4', 'fr', true, 'UTF-8', array(15, 5, 15, 5));`

**Comment by phantam9x** [comment]
I tried but failed

**Comment by spipu** [comment]
it works for me, try to manipulate the utf8.php example

**Comment by Tofandel** [comment]
The default font doesn't work with some characters, setting style="font-family: freeserif;" to the <page> fixed it for me

**Comment by Albob** [comment]
> The default font doesn't work with some characters, setting style="font-family: freeserif;" to the fixed it for me

That worked for me ! Thanks @Tofandel
