### ISSUE TITLE
Change tag versioning pattern

### ISSUE THREAD

**Issue by fagundes** [spipu/html2pdf#27]
Hi @spipu,

It seems Packagist doesn't recognize the current tag parttern like `v4.03`. 
Should be `v4.0.3` or `v4.3`. Or without the prefix 'v', like `4.0.3` or `4.3`.

Could you change it? Or could you keep both parttern?

References:

[Packagist](https://packagist.org/about#managing-package-versions)
[Semantic Versioning](http://semver.org/)

**Comment by garak** [comment]
:+1:

**Comment by fagundes** [comment]
Version `4.4.0` was released so im closing this.
