### ISSUE TITLE
create pdf from joomla fabrik module

### ISSUE THREAD

**Issue by peppe57** [spipu/html2pdf#275]
Hello to all,
from a fabrik module present in joomla, I want to create a pdf.
I connect to a database and I want to create the pdf by taking the fields in the database table.
in my pdf I would like to get the following result:

My name is ___________ born in __________

Then continue to insert the database fields in the specific points I want.

Is there already some tutorial or example?

Thanks in advance to all of you

**Comment by dennisheiden** [comment]
```
$data = your_function_to_get_data_as_array();

ob_start();
include(__DIR__.'/path_to_your_template_pdf/pdf_template.php');
$output	= ob_get_contents();
ob_end_clean();
```

**pdf_template.php**

`<p>My name is <?php echo $data['name'];?> born in <?php echo $data['city_of_birth'];?>`

$output is the parsed HTML with your inserted data, which you can now send to the pdf parser.

**Comment by peppe57** [comment]
Hello
thanks in advance for the answers.
I tried to follow the tutoril but I still can not.

my site http://www.plabruzzo.it/index.php/permesso-orario
from the fabrik form if you click on the pdf icon a pdf is generated, not suitable.

as described in the first post I would like to create a pdf inserting the fields in the form in a php file.

Which procedure should I follow?
Thanks again.

**Comment by peppe57** [comment]
this is the procedure I followed:

- I downloaded the zip file
- I unzipped the folder
- I transferred the folder via ftp to the root directory
- I created the php file with this code

<Head>
<title> Documento senza titolo </ title>
<meta http-equiv = "Content-Type" content = "text / html; charset = utf-8" />

}

</ Head>

<? Php
$ data = your_function_to_get_data_as_array ();

ob_start ();
includes (__ DIR __. '/ file% 20modelli / stampa_permesso_orario2.php');
$ output = ob_get_contents ();
ob_end_clean ();
?>

<Body>
<p style = "text-align: left;"> The undersigned <span style = "font-weight: bold;"> <? php echo $ data ['a_permesso_orrio ___ cognome'];?> </ span> <span style = "font-weight: bold;"> <? php echo $ data ['a_permesso_orrio ___ nome']; ?> </ Span>
          <P> & nbsp; </ p>
</ Body>
</ Html>

in the form I inserted the link that opens the file stampa_permesso_orario2.php to generate the pdf.

Nothing happens, nothing.
How should I set up?
Thank you all

**Comment by peppe57** [comment]
this is the procedure I followed:

- I downloaded the zip file
- I unzipped the folder
- I transferred the folder via ftp to the root directory
- I created the php file with this code

```
<Head>
<title> Documento senza titolo </ title>
<meta http-equiv = "Content-Type" content = "text / html; charset = utf-8" />

}

</ Head>

<? Php
$ data = your_function_to_get_data_as_array ();

ob_start ();
includes (__ DIR __. '/ file% 20modelli / stampa_permesso_orario2.php');
$ output = ob_get_contents ();
ob_end_clean ();
?>

<Body>
<p style = "text-align: left;"> The undersigned <span style = "font-weight: bold;"> <? php echo $ data ['a_permesso_orrio ___ surname'];?> </ span> <span style = "font-weight: bold;"> <? php echo $ data ['a_permesso_orrio ___ nome']; ?> </ Span>
          <P> & nbsp; </ p>
</ Body>
</ Html>
```

in the form I inserted the link that opens the file stampa_permesso_orario2.php to generate the pdf.

Nothing happens, nothing.
How should I set up?
Thank you all

**Comment by spipu** [comment]
Follow the install doc of html2pdf : use composer to install it !

**Comment by peppe57** [comment]
thank you
I did a search on the wiki, but I can still install using composer.

I downloaded the zip folder.
now how should I proceed?

**Comment by spipu** [comment]
Tou must not download the zip file !
Follow the install doc ...

**Comment by peppe57** [comment]
this I have to follow?
https://getcomposer.org/download/

**Comment by peppe57** [comment]
if I have to follow this procedure,

"Download and run Composer-Setup.exe - it will install the latest composer version whenever it is executed."

which .php file should I install?

**Comment by spipu** [comment]
i think you did not understand how composer works... you meay read its doc

https://getcomposer.org/doc/00-intro.md

this is not a html2pdf issue.
