### ISSUE TITLE
Textarea php variable (wrap="hard")

### ISSUE THREAD

**Issue by imux98** [spipu/html2pdf#276]
Hello, I've tried to fix this issue but I did not have any idea, please help me.

I put a textarea with wrap="hard" property in order to create an automatic multiline when user writes inside, textarea Works fine, multiline is ok, I assigned the value in the textarea to a php variable, but: if text in textarea is limited to 1 line, the PDF (by using the HTML2PDF) is correctly generated, but, if text in mutitarea is 2 or more lines, when i try to generate the PDF nothing happens. I did a test by removing the wrap property for the same lenght of text (which with wrap="hard" uses 2 lines), and Works perfectly, the PDF is generated!! So, in this way, I realice that when variable have a multiline, it affects the behaviour of html2pdf, because nothing happens, no error messages, no crashes, no PDF generated with null variables, nothing... I used too the trim() function in order to delete the \n or \r from the string, but nothing happens neither. I print the variable in the screen and apparently is the same in both cases (for Wrap="hard" and for no wrap activated), however with wrap="hard" html2pdf do nothing. I am really interested in implement the wrap="hard" to textarea because the text typed by user is a 330 max length, and if wrap="hard" is absent, the text in textarea, the text will be written in one line and is moving going until the edge of 330 position.

**Comment by spipu** [comment]
if you do not need that the user change the value in the PDF, why using a textarea ? just use a div
