### ISSUE TITLE
The html tag [section] is not known by Html2Pdf

### ISSUE THREAD

**Issue by ishtiyaqhu** [spipu/html2pdf#278]
Html2Pdf Error [1]
The html tag [section] is not known by Html2Pdf. You can create it and push it on the Html2Pdf GitHub project.
File: /vendor/spipu/html2pdf/src/Html2Pdf.php
Line: 1404
Invalid Tag: section
Html Line: 1

**Comment by spipu** [comment]
the section tag is like a div tag => use div

**Comment by entepe85** [comment]
Or you could just not be a prick and allow for semantic HTML.

**Comment by devnix** [comment]
Almost 3 years later, html2pdf is not compatible with HTML. **GG**
