### ISSUE TITLE
SVG parameter display="none"

### ISSUE THREAD

**Issue by ZAJDAN** [spipu/html2pdf#28]
Hello,
I am sorry, but forum is not online, so I will ask here:
is possible render PDF from SVG which contains multiple layers and a few has parameter display="none" ...? Will html2pdf accept such parameter?

Thank You

**Comment by spipu** [comment]
no, it does not accept it. If you do not want to display a part, juste do not ask for it to html2pdf :)

**Comment by ZAJDAN** [comment]
The reason is, that the SVG is interactive and user can change it on website and for example some part make hidden. And the customized SVG is send to render in PDF. Now you understand me why I need the possibility hide some part/layer ...?
