### ISSUE TITLE
Problems with page_header/page_footer

### ISSUE THREAD

**Issue by esteban-turnocheck** [spipu/html2pdf#283]
Hi!
Great work! Thanks!
When you set the page_headers and/or page_footers with some content that is bigger than the value of the backtop or backbottom values from the page, then te contents of the page itself, overlaps with them.
To reproduce the problem, I have modified your /examples/res/exemple03.php. Copied/pasted the TR of the header so it has 8 rows instead of 1. Same with the footer. And made a longer table as the content of the page.
Attached is the result.
Seems to me that the check's you do to determine when to create a new page, before rendering content, is based on the bottom margin of the pdf page, but there is no consideration of the height that the header and the footer are taking. I could change that in the source code, but i wanted to be sure i'm not making a mistake, and if it has to be changed, could you please provide me some guidance (which parameter/s should I check in each one of the parts on the code when you do that check, and what if the header/footer can be of different heights for different pages)
Thanks again!
[exemple03.pdf](https://github.com/spipu/html2pdf/files/1736658/exemple03.pdf)

EDIT:
I see there's a similar issue here #81 , but if I implement the solution you mention there, then the header/footer must have a preestablished and fixed height, which is not possible in my case.

**Comment by spipu** [comment]
the header and the footer must have a fixed height, like in word, or lots of others tools : when you specify a bottom-top, if the header take more space, then the content overlaps with the header.

https://github.com/spipu/html2pdf/blob/master/doc/page.md
=> it will not be changed.

why do you not have a fixed height on your header ? maybe using the header is not a good solution
