### ISSUE TITLE
Error Required

### ISSUE THREAD

**Issue by franciscovefago** [spipu/html2pdf#284]
Hi, I did the composer setup, on the site it works, but on the server it gives errors of required:
`require_once (Spipu \ Html2Pdf \ Html2Pdf.php): failed to open stream: No such file or directory`
`Fatal error: require_once(): Failed opening required 'Spipu\Html2Pdf\Html2Pdf.php' `

**Comment by spipu** [comment]
1. do you only require the composer autoloader file ? and how ?
2. did you have all the files on the vendor folder ?
