### ISSUE TITLE
inputs are not shown in PDF

### ISSUE THREAD

**Issue by maiermic** [spipu/html2pdf#285]
When I render the [forms-example](https://github.com/spipu/html2pdf/blob/v4.6.1/examples/res/forms.php) no inputs are shown:

---
![image](https://user-images.githubusercontent.com/8530117/36435889-234416b0-1663-11e8-9f98-4bdaf214b289.png)

---
I expect that inputs like radio and checkbox button are shown/printed.

**Comment by tozman** [comment]
Inputs are not rendered in firefox for example. Acrobat reader is fine for forms.

**Comment by maiermic** [comment]
Seems like forms are not well supported across PDF readers :disappointed:
Fortunately, my PDF is only for printing. Therefore I can use CSS to style my input elements as needed, but I cann't use `input` tags because their borders are not shown. But that is not a major problem.

**Comment by tozman** [comment]
You can use mPDF library, it has a nice way to render for elements, but you can't interact with them. At least it prints nicely.

**Comment by gtamborero** [comment]
I'm using divs with borders + paddings + absolute positioning for that purpose. This is an example: [http://www.iproject.cat/wp-content/uploads/2018/html2pdf-example-with-div.jpg](url)

html2pdf is good but it doesn't work as you expect with floats, input and other elements. You have to try every code :( But it's faster way than using FTPDF or similar libraries I think
