### ISSUE TITLE
Lost format of reports.

### ISSUE THREAD

**Issue by bustamantecesar** [spipu/html2pdf#286]
Hello, I have an application using bootstrap and here I use html2pdf to generate all the reports, since 2014 it worked very well, but a couple of weeks ago I realized that now the reports lost the formats and now all the texts are shown attached to the left side, nothing is centered everything is unformatted. Nothing has been changed in the application and the webhosting continues with the same version of PHP. What will be the problem since I am 100% sure that nothing has changed. Thank you.

**Comment by dennisheiden** [comment]
First thing you should check is if the CSS is valid and loaded.

**Comment by spipu** [comment]
what it the version of you html2pdf ?

**Comment by wings77** [comment]
I have the same problem with version 5.1.0, which is the version that accepts all the tags?

**Comment by spipu** [comment]
be careful, bootstrap is not supported by html2pdf
