### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by cheppy32** [spipu/html2pdf#287]
sorry if the writing is less understood English
I want to ask
I downloaded html2pdf4.4.0 and installed scoude `code`

`<? php
$ content = '
<page>

    <h1> test </ h1>

</ page>;'
require_once ('../ assets / html2pdf / html2pdf.class.php');
$ html2pdf = new HTML2PDF ('P', 'A4', 'en');
$ html2pdf-> WriteHTML ($ content);
$ html2pdf-> Output ('example.pdf');
?>'

then I test the results as follows

Warning: count (): Parameter must be an array or an object that implements Countable in C: \ xampp \ htdocs \ app \ assets \ html2pdf \ _class \ locale.class.php on line 68

Warning: count (): Parameter must be an array or an object that implements Countable in C: \ xampp \ htdocs \ app \ assets \ html2pdf \ _class \ locale.class.php on line 68
TCPDF ERROR: Some data has already been output, can not send PDF file

please guidance, I just learned

**Comment by spipu** [comment]
The 4.x.x version is not supported any more

You must use the 5.x.x version

And do la t download it manually. Read the install doc
