### ISSUE TITLE
Can't load pictures

### ISSUE THREAD

**Issue by ber036** [spipu/html2pdf#288]
Suddenly I get an error that pictures can not be opened.

Fatal error: Uncaught <span style="color: #AA0000; font-weight: bold;">Fout nr6</span><br>Bestand : /home/xxx/domains/xxx.nl/private_html/includes/html2pdf.class.php<br>Regel : 1319<br><br>Kan afbeelding niet laden: <b>https://www.xxx.nl/images/logo.png</b> thrown in /home/xxx/domains/xxxx.nl/private_html/includes/html2pdf.class.php on line 1319

What can I do to solve this problem. Nothing was changed in the scripts. Images are in the right directory and accessable through internet.

**Comment by spipu** [comment]
Why getting the image throw a url if it is on your server ? Try to use a relative or an absolute path

**Comment by ber036** [comment]
I alreadty placed the image as an absolute path: <img src="https://www.partyrentalmere.nl/images/logo-ptva-partyrent.png" width="350" border="0" align="center"> 

 

This gave the error.

 

Van: Laurent MINGUET [mailto:notifications@github.com] 
Verzonden: woensdag 21 februari 2018 17:32
Aan: spipu/html2pdf <html2pdf@noreply.github.com>
CC: ber036 <ber@partyrentalmere.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [spipu/html2pdf] Can't load pictures (#288)

 

Why getting the image throw a url if it is on your server ? Try to use a relative or an absolute path

**Comment by spipu** [comment]
not absolute URL, but absolute path : /var/www/..../images/logo-ptva-partyrent.png
