### ISSUE TITLE
Install without composer

### ISSUE THREAD

**Issue by mr-pack** [spipu/html2pdf#290]
How to install/use without composer?
I hate composer

**Comment by LittleBigFox** [comment]
According to #262, you can't.

**Comment by spipu** [comment]
you hate composer ? it means that you don't know what it does... some arguments ?

**Comment by mr-pack** [comment]
1. It takes time (cost money).
2. Composer really solves nothing
3. I already have working project using my own autoloader and dont want wasted code
4. Decided to use "dompdf" (4477 stars + has simple installation) instead of "html2pdf" (only 544 stars)
5. Unstar from me

**Comment by spipu** [comment]
1. it saves times...
2. autoload, lib dependencies, repo, ...
3. composer is more than a autoloader
4. wasted code ??? really ? 
=> i think you may lean more about composer...

bye :p
