### ISSUE TITLE
Background images not always rendering?

### ISSUE THREAD

**Issue by inctor** [spipu/html2pdf#292]
Hey,

We've been struggling a bit in dealing with "backimg" property for the <page> tag.
- The background image is correctly rendered when you open the finished PDF in Chrome.
But in Internet Explorer and many other PDF Viewers, the background image on <page> is not being shown, and we just see a white background.

Not entirely sure where the issue/error is happening.

- Is it just referring to the image as a background, or actually embedding the image to the PDF?

**Comment by spipu** [comment]
the image is embedding in the PDF.

can you give me an example ?

**Comment by inctor** [comment]
I've attached 2 reports, one of them it works fine, and the other one it only shows the background in Chrome, but not in other readers.

Works fine: [onboarding_rapport_capital-markets_13032018.pdf](https://github.com/spipu/html2pdf/files/1806471/onboarding_rapport_capital-markets_13032018.pdf)

Broken: 
[onboarding_rapport_capital-markets_13032018 (1).pdf](https://github.com/spipu/html2pdf/files/1806472/onboarding_rapport_capital-markets_13032018.1.pdf)

The only difference is that one of the images is PNG, the other one is JPG. But both should work?

**Comment by spipu** [comment]
it is because TCPDF (used by HTML2PDF), always convert the images to PNG, and if the JPG format is invalid, you can have a white image.
it is not a html2pdf issue
