### ISSUE TITLE
Does not work in production

### ISSUE THREAD

**Issue by morulopez** [spipu/html2pdf#296]
In local works perfectly but in production in siteground it does not work I need help please

**Comment by spipu** [comment]
Whitout any details, we can’t help ...

**Comment by morulopez** [comment]
I have installed the file in publichtml in the hosting (vendor, composer.json, composer.lock)
but this error throws me
Fatal error: require (): Failed opening required '/vendor/autoload.php' (include_path = '.: / Usr / local / php70 / pear') in /home/territo0/public_html/samplepdf.php on line 3

Try installing it with the composer that has the default hosting but does not work either

**Comment by spipu** [comment]
did you have the autoload.php file in your vendor folder ?
and also, try do include it with a absolute path (using the __DIR__ const) instead of a relative path

**Comment by morulopez** [comment]
I am using
require_once (__DIR__ .'phpmyadmin / vendor / autoload.php ');
require_once (__DIR __. 'phpmyadmin / vendor / spipu / html2pdf / html2pdf.class.php');
but it still does not work.
Is there a post or tutorial to see how it is installed in hosting ???
I do not know what to do, I'm desperate
thanks for answering

**Comment by dennisheiden** [comment]
missing slash after __DIR__, remove spaces:

```
require_once (__DIR__ ./'phpmyadmin/vendor/autoload.php');
require_once (__DIR __. /'phpmyadmin/vendor/spipu/html2pdf/html2pdf.class.php');
```

**Comment by spipu** [comment]
1. when using the composer autoloader, you **must not** include classes manually...

https://getcomposer.org/doc/01-basic-usage.md#autoloading
https://www.php-fig.org/psr/psr-4/

2. using phpmyadmin on a production server is **bad**, for security reasons...

**Comment by morulopez** [comment]
It still does not work ...
in my hosting I have already installed by default the files vendor and composer.json and composer.lock
in the phpmyadmin folder
in the .json file I added "spipu / html2pdf": "5.1.0"
and from my file I call require '/vendor/autoload.php';
but it gives me the error Fatal error: Class 'spipu \ Html2Pdf \ Html2Pdf' not found in /home/territo0/public_html/samplepdf.php on line 5

I do not know if I have to add the vendor files where I have all my project in the hosting or what to do, I have desperate this

**Comment by morulopez** [comment]
I have tried like this
require_once( '__DIR__./vendor/autoload.php');
require_once ('__DIR__./vendor/spipu/html2pdf/html2pdf.class.php');

AND THIS ERROR COMES OUT
Fatal error: require_once(): Failed opening required 'phpmyadmin/vendor/spipu/html2pdf/html2pdf.class.php' (include_path='.:/usr/local/php56/pear') in /home/territo0/public_html/samplepdf.php on line 4

**Comment by spipu** [comment]
did you read the html2pdf doc ? and did you read my previous comment ???

i close this issue, it is not a html2pdf issue, it is a composer lack of understanding
