### ISSUE TITLE
watermark with html2pdf?

### ISSUE THREAD

**Issue by riannre** [spipu/html2pdf#299]
how to make watermark with html2pdf?
please

**Comment by spipu** [comment]
you mean, how to put a image in background, or on the front of the page ?

**Comment by scumbagblues** [comment]
I want to put a image to simulate a watermark I think it will be on the front but as it will be a PNG image there will be able to see the text on the background

**Comment by spipu** [comment]
Look at the doc ;)

https://github.com/spipu/html2pdf/blob/master/doc/page.md

Try the backimg property on the page tag

**Comment by scumbagblues** [comment]
Thanks!
