### ISSUE TITLE
Impression A5

### ISSUE THREAD

**Issue by theo71000** [spipu/html2pdf#300]
Bonjour, savez vous comment faire pour que le pdf généré s'imprime directement au format A5. Mon imprimante a plusieurs bac mais il sélectionne automatiquement le A4 mais imprime en A5. voici mon code. try{
    $pdf= new HTML2PDF('148x210','A5','fr');
    $pdf->writeHTML($cara);
    $pdf->Output('produit.pdf');
}
catch(HTML2PDF_exeption $e){

die($e);}
?>
merci d'avance.

**Comment by spipu** [comment]
1. vous utilisez une vieille version (v4.x) qui n'est plus supportée. Vous devriez upgrader vers la dernière verison v5.x
2. attention, le premier paramètre n'est pas la taille de la page mais son orientation.
3. même si le pDF est en A5, si vous sélectionnez le bac de feuille A4, ca imprimera dessus. Ceci n'est pas lié à html2pdf mais à comment vous imprimez.

**Comment by theo71000** [comment]
ok je vais essayer merci à vous.
