### ISSUE TITLE
Problems in hosting

### ISSUE THREAD

**Issue by morulopez** [spipu/html2pdf#301]
Hello the other day I sent a question because in my hosting (sitegorund) the library does not work
I have it in the directory of my installed project and it throws me this error

Fatal error: Uncaught exception 'Exception' with message 'TCPDF ERROR: Some data has already been output, can not send PDF file' in /home/territo0/public_html/vendor/tecnickcom/tcpdf/tcpdf.php:2927 Stack trace: # 0 /home/territo0/public_html/vendor/tecnickcom/tcpdf/tcpdf.php(7626): TCPDF-> Error ('Some data has a ...') # 1 / home / territo0 / public_html / vendor / spipu / html2pdf / src / Html2Pdf.php (549): TCPDF-> Output ('document.pdf', 'I') # 2 /home/territo0/public_html/samplepdf.php(57): Spipu \ Html2Pdf \ Html2Pdf-> output () # 3 {main} thrown in /home/territo0/public_html/vendor/tecnickcom/tcpdf/tcpdf.php on line 2927

The ones at site ground tell me to talk to a professional developer.
Do you know what can happen ??

**Comment by LittleBigFox** [comment]
Hi!
This message append when you have have sent something to the browser before the PDF. You have to check the output without the PDF first, clean the output/buffer, then send the PDF.
Regards,
