### ISSUE TITLE
 The html tag [colgroup] is not known by Html2Pdf

### ISSUE THREAD

**Issue by huaiguoguo** [spipu/html2pdf#303]
Spipu\Html2Pdf\Exception\HtmlParsingException: The html tag [colgroup] is not known by Html2Pdf. You can create it and push it on the Html2Pdf GitHub project. in D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php:1404
Stack trace:
#0 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1356): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#1 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(5687): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#2 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1402): Spipu\Html2Pdf\Html2Pdf->_tag_open_TD(Array)
#3 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1356): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#4 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(3251): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#5 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1402): Spipu\Html2Pdf\Html2Pdf->_tag_open_DIV(Array)
#6 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1370): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#7 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(3251): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#8 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1402): Spipu\Html2Pdf\Html2Pdf->_tag_open_DIV(Array)
#9 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1370): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#10 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(3251): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#11 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1402): Spipu\Html2Pdf\Html2Pdf->_tag_open_DIV(Array)
#12 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1370): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#13 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(564): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#14 D:\deve\www\wenchaofei\xuexin\backend\controllers\SchoolrollController.php(233): Spipu\Html2Pdf\Html2Pdf->writeHTML('<page>\r\n<div cl...')
#15 [internal function]: backend\controllers\SchoolrollController->actionTest()
#16 D:\deve\www\wenchaofei\xuexin\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#17 D:\deve\www\wenchaofei\xuexin\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#18 D:\deve\www\wenchaofei\xuexin\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('test', Array)
#19 D:\deve\www\wenchaofei\xuexin\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('schoolroll/test', Array)
#20 D:\deve\www\wenchaofei\xuexin\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#21 D:\deve\www\wenchaofei\xuexin\backend\web\index.php(17): yii\base\Application->run()
#22 {main}

**Comment by LittleBigFox** [comment]
Duplicate #306

**Comment by spipu** [comment]
it will be added in the next release
