### ISSUE TITLE
yii\base\ErrorException: Undefined offset: 2 in D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php:2604

### ISSUE THREAD

**Issue by huaiguoguo** [spipu/html2pdf#304]
yii\base\ErrorException: Undefined offset: 2 in D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php:2604
Stack trace:
#0 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(2604): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', 'D:\\deve\\www\\wen...', 2604, Array)
#1 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(5158): Spipu\Html2Pdf\Html2Pdf->_calculateTableCellSize(Array, Array)
#2 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1402): Spipu\Html2Pdf\Html2Pdf->_tag_close_TABLE(Array)
#3 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1362): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#4 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(3251): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#5 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1402): Spipu\Html2Pdf\Html2Pdf->_tag_open_DIV(Array)
#6 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1370): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#7 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(5687): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#8 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1402): Spipu\Html2Pdf\Html2Pdf->_tag_open_TD(Array)
#9 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1356): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#10 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(3251): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#11 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1402): Spipu\Html2Pdf\Html2Pdf->_tag_open_DIV(Array)
#12 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1370): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#13 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(3251): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#14 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1402): Spipu\Html2Pdf\Html2Pdf->_tag_open_DIV(Array)
#15 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1370): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#16 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(3251): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#17 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1402): Spipu\Html2Pdf\Html2Pdf->_tag_open_DIV(Array)
#18 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(1370): Spipu\Html2Pdf\Html2Pdf->_executeAction(Object(Spipu\Html2Pdf\Parsing\Node))
#19 D:\deve\www\wenchaofei\xuexin\vendor\spipu\html2pdf\src\Html2Pdf.php(564): Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode()
#20 D:\deve\www\wenchaofei\xuexin\backend\controllers\SchoolrollController.php(233): Spipu\Html2Pdf\Html2Pdf->writeHTML('<page>\r\n<div cl...')
#21 [internal function]: backend\controllers\SchoolrollController->actionTest()
#22 D:\deve\www\wenchaofei\xuexin\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#23 D:\deve\www\wenchaofei\xuexin\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#24 D:\deve\www\wenchaofei\xuexin\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('test', Array)
#25 D:\deve\www\wenchaofei\xuexin\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('schoolroll/test', Array)
#26 D:\deve\www\wenchaofei\xuexin\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#27 D:\deve\www\wenchaofei\xuexin\backend\web\index.php(17): yii\base\Application->run()
#28 {main}

**Comment by spipu** [comment]
it is because your table is not well formatted. Be careful to your td and tr counts with the rowspan and colspan attributes
