### ISSUE TITLE
The html tag [colgroup] is not known by Html2Pdf. You can create it and push it on the Html2Pdf GitHub project.

### ISSUE THREAD

**Issue by huaiguoguo** [spipu/html2pdf#306]
The html tag [colgroup] is not known by Html2Pdf. You can create it and push it on the Html2Pdf GitHub project.

![image](https://user-images.githubusercontent.com/1888094/38137564-ee63ab78-3457-11e8-8978-1cc06d94c5e1.png)

**Comment by LittleBigFox** [comment]
Hello!
Yes, this tag is not created in HTML2PDF, nor the COL tag. You can try to implement it, but I have to warn you that tables are the most sophisticated part of HTML2PDF, it can be very difficult.
Regards,

**Comment by spipu** [comment]
the col tag is already implemented.
the colgroup tag will be added in the next release
