### ISSUE TITLE
pdf is generated but CSS is not working

### ISSUE THREAD

**Issue by imran88** [spipu/html2pdf#307]
Hi,
I tried to generate pdf, it works but CSS is not working, I debugged and verified it loads CSS and set the values in CSS variable in html2pdf class. 

Verified CSS by using echo print_r($this->CSS) after this statement $this->ReadCSS($html);

Here is the URL
http://www.carriage.citytop.com.pk/util/reports/report.php?token=VTBRajA2OGxPMkYwMHEwbDB6MDA&source=TzBrYzBYNDZwOHgwMDMwZzFSMDA 

Using this method to get html content

function curl_get_file_contents($URL)
    {
        $c = curl_init();
        curl_setopt($c, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($c, CURLOPT_URL, $URL);
        $contents = curl_exec($c);
        curl_close($c);
        if ($contents) return $contents;
            else return FALSE;
	}

	$strContent = curl_get_file_contents($source);

Can someone please help to fix this out? It would be great help. Thanks!

**Comment by LittleBigFox** [comment]
Hi!
Can you give us the css content, and the HTML content? It may be a corrupted heritage..?
Regards.
