### ISSUE TITLE
Spipu\Html2Pdf\Tag\Svg\Path::drawSvg not working correctly

### ISSUE THREAD

**Issue by laszlokorte** [spipu/html2pdf#308]
The path is processed incorrectly if it contains a `Z` action followed by an `M` action not separated by a space. like so: `d="M10,10L0,10L0,0ZM20,0L20,10L0,20Z"` Then the ZM is interpreted as a single (unexpected) action and results in an exception.

**Comment by spipu** [comment]
hi
it will be fixed in the next release
