### ISSUE TITLE
Html2Pdf Error [1]

### ISSUE THREAD

**Issue by Anouchka25** [spipu/html2pdf#309]
Hi
Please help me. 
I have this error : 

> Html2Pdf Error [1]
Too many tag closures found for [page]
File: C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\Facturation_generale\vendor\spipu\html2pdf\src\Parsing\Html.php
Line: 228
Invalid Tag: page
Html Line: 48

This is my code HTML/PHP:
`<style type="text/css">
table{width: 100%; border-collapse:collapse; font-size:18px}
.header td{width: 50%; vertical-align: top, background-color: #57B223}
.text-left{text-align: left}
.text-right{text-align: right}
.text-center{text-align: center}
.separator{height: 150px; width: 100%}
.content td{border:solid 1px #CFD1D2; padding: 5px;}
.content th{border:solid 1px #000000; padding: 5px; background-color: #000000; color: #FFFFFF}
.ligne1Content{background-color:#57B223}
.couleurgris{background-color:#DDDDDD; height:200px}
</style>
<page backtop="20mm" backright="10mm" backbottom="20mm" backleft="10mm">
  <?php
  require_once 'connexion.php';

  $resFC1=$base->prepare("SELECT * FROM infosfacture WHERE num= ?");
  $resFC1->bindValue(1, $id, PDO::PARAM_INT);
  $resFC1->execute(array($_GET['num']));

  $resFC = $base->prepare('SELECT infosfacture.num, infosfacture.client, infosfacture.datefacture, infosfacture.facturede, infosfacture.conditions, facturation.designation, facturation.quantite, facturation.prixht
  FROM infosfacture
  INNER JOIN facturation
  ON infosfacture.num=? AND facturation.fk_facturation_id=infosfacture.id');
  $resFC->execute(array($_GET['num']));
  ?>
  <?php foreach ($resFC1 as $req): ?>
  <table class="header">
    <tr>
      <td class="text-left">
        <b>Facturé à : <?php echo $req['client'] ?></b>
        <br>
      </td>
      <td class="text-right">
        <b>Facture de : <?php echo $req['$facturede'] ?></b>
        <br>
      </td>
    </tr>
  </table>
  <div class="separator"></div>
<table>
  <tr>
  <td class="text-left">N° de facture: <?php echo $req['num'] ?>  </td>
  <td class="text-right">Date: <?php echo $req['datefacture'] ?></td>
  </tr>
 </table>
 <?php endforeach; ?>
<br/><br/>
  <table class="content">
    <thead>
    <tr class="ligne1Content">
      <td class="text-left">PRESTATION</td>
      <td class="text-center">NOMBRE DE JOURS</td>
      <td class="text-center">TARIF JOURNALIER</td>
      <td class="text-right">TOTAL HT</td>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($resFC as $req): ?>
  <tr class="couleurgris">
      <td class="text-left"><?php echo $req['designation'] ?></td>
      <td class="text-center"><?php echo $req['$quantite'] ?></td>
      <td class="text-center"><?php echo $req['$prixht'] ?></td>
      <td class="text-right"><?php echo $req['quantite'] * $req['prixht'] ?></td>
  </tr>
  <?php endforeach; ?>
 </tbody>
 <tfoot>
 </tfoot>
  </table>
</page>
`

**Comment by dennisheiden** [comment]
Sehr geehrte Kundin,
sehr geehrter Kunde,


leider stehe ich Ihnen heute nicht zur Verfügung.

In Notfällen steht Ihnen -mit Einschränkungen- ein anderer Mitarbeiter zur Seite:

info@straightvisions.com


Mit freundlichen Grüßen

Dennis Heiden

straightvisions - enhancing the web

Berlin Friedrichshain Dennis Heiden - Pettenkoferstraße 16-18 - 10247 Berlin - Phone +49 (0)30 / 8939 - 8450
Hamburg City Matthias Reuter - Ballindamm 39 - 20095 Hamburg - Phone +49 (0)40 / 99999 - 3020
Hamburg Nord Matthias Reuter - Hasselwisch 11a - 22397 Hamburg - Phone +49 (0)40 / 1817 - 3958

**Comment by LittleBigFox** [comment]
Hi,
Can you edit your message with the CODE tag svp? We can't help you there...
Regards.

**Comment by Anouchka25** [comment]
I added this code in top my file : `date_default_timezone_set('Europe/Berlin');`
I have now this error :

> Fatal error: Uncaught <span style="color: #AA0000; font-weight: bold;">ERREUR n°3</span><br>Fichier : /homepages/0/d513201601/htdocs/Facturation_generale/html2pdf/_class/parsingHtml.class.php<br>Ligne : 117<br><br>Code HTML non valide, une balise est fermée en trop : <b>&lt;page&gt;</b><br><br>HTML : ...tr&gt; &lt;/tfoot&gt; &lt;/table&gt; &lt;/page&gt;... thrown in /homepages/0/d513201601/htdocs/Facturation_generale/html2pdf/_class/parsingHtml.class.php on line 117

I never touched the html2pdf/_class/parsingHtml.class.php file. Why this error please !

**Comment by LittleBigFox** [comment]
Hi!
The error doesn't happen because you have change something in html2pdf, but because the PAGE tag is closed too often in the HTML. Try to give us the `$content = ob_get_clean();` . 

Furthermore, In your php code, you have two calls to html2pdf and other:
```
// require_once dirname(__FILE__).'/vendor/autoload.php';
// require('html2pdf/html2pdf.class.php');
require_once dirname(__FILE__).'/vendor/autoload.php';
require_once(dirname(__FILE__).'/vendor/spipu/html2pdf/html2pdf.class.php');
```
You can comment the two first lines, like the example.

**Comment by LittleBigFox** [comment]
And if you have installed html2pdf with composer, you might comment the fourth line too.

**Comment by Anouchka25** [comment]
I understand nothing, here is my new code and it still does not work. I re-installed html2pdf with composer. Help me please !
`<?php
date_default_timezone_set('Europe/Berlin');
/*
 * Générer un PDF à partir d'une base de données
 */


/*
 * Début de la temporisation de sortie
 */
ob_start();
?>
<page backtop="20mm" backright="10mm" backbottom="20mm" backleft="10mm">
<style type="text/css">

</style>

  <?php
  require_once 'connexion.php';

  $resFC1=$base->prepare("SELECT * FROM infosfacture WHERE num= ?");
  $resFC1->bindValue(1, $id, PDO::PARAM_INT);
  $resFC1->execute(array($_GET['num']));

  $resFC = $base->prepare('SELECT infosfacture.num, infosfacture.client, infosfacture.datefacture, infosfacture.facturede, infosfacture.conditions, facturation.designation, facturation.quantite, facturation.prixht
  FROM infosfacture
  INNER JOIN facturation
  ON infosfacture.num=? AND facturation.fk_facturation_id=infosfacture.id');
  $resFC->execute(array($_GET['num']));
  ?>
  <?php foreach ($resFC1 as $req): ?>
  <table class="header">
    <tr>
      <td class="text-left">
        Facturé à :<br/> <b><?php echo $req['client'] ?></b>
        <br>
      </td>
      <td class="text-right">
        Facture de :<br/><b> <?php echo $req['facturede'] ?></b>
        <br>
      </td>
    </tr>
  </table>
  <div class="separator"></div>
<table>
  <tr>
  <td class="text-left">N° de facture: <b><?php echo $req['num'] ?></b>  </td>
  <td class="text-right">Date: <b><?php echo $req['datefacture'] ?></b></td>
  </tr>
 </table>
 <?php $tva = $req['tva'] ?>
 <?php $conditions = $req['conditions'] ?>
 <?php endforeach; ?>
<br/><br/>
  <table class="content">
    <thead>
    <tr class="ligne1Content">
      <td class="text-left couleurgris"><b>DESIGNATION</b></td>
      <td class="text-center couleurmoinsgris"><b>QUANTITE</b></td>
      <td class="text-center couleurgris"><b>PRIX HT</b></td>
      <td class="text-right couleurverte"><b>TOTAL HT</b></td>
    </tr>
  </thead>
  <tbody>
    <?php $somme = 0;?>
    <?php foreach ($resFC as $req): ?>
  <tr class="couleurgris">
      <td class="text-left couleurgris"><?= $req['designation'] ?></td>
      <td class="text-center couleurmoinsgris"><?= $req['quantite'] ?></td>
      <td class="text-center"><?= $req['prixht'] ?></td>
      <td class="text-right couleurverte"><?= $req['quantite'] * $req['prixht'] ?></td>
  </tr>
  <?php $somme += $req['prixht'] * $req['quantite']; ?>
  <?php endforeach; ?>
 </tbody>
 <tfoot>
   <tr>
     <td colspan="3" class="text-right tht">TOTAL HT</td>
     <td class="tht"><?= $somme; ?></td>
   </tr>
   <tr>
     <td colspan="3" class="text-right taxe">TAXE à <?php echo $tva; ?>% </td>
     <td class="taxe"><?= $somme * $tva/100; ?></td>
   </tr>
   <tr>
     <td colspan="3" class="text-right ttc">TOTAL TTC</td>
     <td class="ttc"><?= $somme + $somme*$tva/100; ?></td>
   </tr>

   <tr>
     <td colspan="4"><h3>Conditions et moyens de paiement:</h3><br/><?= $conditions ?></td>
   </tr>

 </tfoot>
  </table>
</page>
<?php

/*
 * $content récupére toutes les données mises en mémoire.
 */

$content = ob_get_clean();

require_once dirname(__FILE__).'/vendor/autoload.php';

use Spipu\Html2Pdf\Html2Pdf;

//require_once(dirname(__FILE__).'/vendor/spipu/html2pdf/html2pdf.class.php');



/*
 * On instancie notre constructeur
 * On affiche le contenu
 * On génére notre PDF
 */

$pdf = new HTML2PDF('P','A4','fr','true','UTF-8');
$pdf->writeHTML($content);
//$pdf->pdf->IncludeJS('print(true)');
$pdf->Output('facture.pdf');

?>
`

**Comment by LittleBigFox** [comment]
I sent you a mail for helping you.
Regards.

**Comment by LittleBigFox** [comment]
It was the `require_once 'connexion.php';` . Once put at top of the file, all works fine.

**Comment by mirjiskani** [comment]
Hi  i am getting issue in script tag would you resolve this issue pls

**Comment by alfred-saker** [comment]
bgn

**Comment by BiswajitBera2021** [comment]
![image](https://user-images.githubusercontent.com/87976127/179943964-d59d3a73-fe33-4f50-aa39-857292de7922.png)
