### ISSUE TITLE
Header font

### ISSUE THREAD

**Issue by piernik** [spipu/html2pdf#311]
I have problem with header font - It has now special chars (`SPRZEDAŻY`):

![html2pdf-header](https://user-images.githubusercontent.com/420691/38408182-b4a5d9cc-397c-11e8-98c5-7044db2113a7.png)

Here is my initial code:

```
$html2pdf = new Html2Pdf('P', 'A4', 'pl', true, 'UTF-8', [0, 0, 0, 0]);
$html2pdf->setDefaultFont('freesans');
```

**Comment by LittleBigFox** [comment]
Hi! It's a TCPDF bug, you may have a look on 
https://stackoverflow.com/questions/5333702/tcpdf-utf-8-lithuanian-symbols-not-showing-up
Regards.

**Comment by piernik** [comment]
I think it's not the case. I get polish chars but only in body - not header.
Problem is that in header You have default font - not that set in `$html2pdf->setDefaultFont('freesans');`

**Comment by spipu** [comment]
how did you implement your header ?

**Comment by piernik** [comment]
@spipu I used other lib and don't remember how I did it.
