### ISSUE TITLE
Problème avec page break automatique

### ISSUE THREAD

**Issue by sane79** [spipu/html2pdf#312]
Bonjour,
j'écris en Français car j'ai vu que Spipu est FR.
J'ai un problème lorsque je génère un pdf avec plusieurs tableaux à l'intérieur.
J'ai des `<table>` dans des `<div>` et j'ai un tableau en fin de page qui occupe plusieurs page en l’occurrence (une et demie exactement).
html2Pdf me rajoute automatiquement un nouvelle page à la suite, du coup, je me retrouve avec une page vierge (avec entêtes et pieds de page).
C'est embêtant car j'ai la numérotation des pages en plus, du coup, en bas de chaque page j'ai "1/4, 2/4, ..." et la 4ème page est vide.
Est-ce qu'il y a une solution pour que lorsqu'un élément prend plusieurs page, cela ne créé pas une nouvelle page ?
(d'ailleurs si je met un élément à la suite de ce tableau, il sera forcément sur cette nouvelle page, et non à la suite de la demie page restante)

merci à vous pour tout ce travail remarquable.

**Comment by LittleBigFox** [comment]
Bonjour,
Avez vous donner une hauteur a vos div? style="height:260mm" ou un truc du genre?
Ou vos div qui contiennent les tables sont-elles elles mêmes dans une table?

**Comment by sane79** [comment]
bonjour,
le `div` entoure le `table` (pour pouvoir faire des `page-break-before`, moi-même lorsque je le souhaite).
il n'a pas de `height` définie car les tables sont dynamiques (je ne connais pas la hauteur à l'avance)

**Comment by LittleBigFox** [comment]
Ok. 
Alors si ca peut aider, dans ce cas, j'utilise une array pour mettre les tables au lieu de div autour de celle-ci, et je l'implode comme ca:

`$str = implode('<div style="page_break_before:always"><BR></div>', $arrTable);`

En général, ça enlève pas mal de pb de page blanche.

Sinon une autre solution est de rajouter un tag <page> entre chaque table, mais ça peut être problématique, j'en ai eu l'experience.

**Comment by sane79** [comment]
Je viens de faire un premier test, et le fait de sortir mes tables des div et de mettre un div vide qui a le page-break-before entre elles, et ça à l'air de bien fonctionner.
Merci pour votre aide.
Je vous tiens au courant si c'est concluant

**Comment by LittleBigFox** [comment]
Ah excusez, GH a fait sauter le tag de ma deuxième solution.

> Sinon une autre solution est de rajouter un tag `<page>` entre chaque table, mais ça peut être problématique, j'en ai eu l'experience.

Sinon oui le `<div><BR></DIV>` entre chaque table fonctionne pas mal.

**Comment by sane79** [comment]
Et voilà, vous venez de solutionner 2 jours de recherches et de prises de tête.
J'ai appliqué tout ça dans tout mon code. Merci à vous.
