### ISSUE TITLE
How convert bootstrap template in PDF with HTML2PDF ? 

### ISSUE THREAD

**Issue by Anouchka25** [spipu/html2pdf#314]
Hi

Excuse-me to post many questions. Please what is practical method to convert bootstrap template in PDF with HTML2PDF.
I founded a good bootstrap template for my project. 

Thanks

**Comment by lenamtl** [comment]
Hi,

Have you managed it?

I'm new to HTML2PDF
I'm not using table but only div / col with Bootstrap.

**Comment by spipu** [comment]
it will not.
bootstrap is for browser, not for static PDF page
