### ISSUE TITLE
List margin

### ISSUE THREAD

**Issue by piernik** [spipu/html2pdf#317]
By default lists has left margin set.
How can I get rid of it?
```
ul {
margin:0;
padding:0;
}
li {
margin:0;
padding:0;
}
```
This is not working:/

**Comment by oisoftware** [comment]
Hi @piernik, did you find a solution to this? I'm having the same problem.

**Comment by piernik** [comment]
No I used different library `mpdf/mpdf`

**Comment by gajan-cyber** [comment]
I think that the margins are generated by html2pdf please check this there is an array which have default array margin 
'marges'      => array(5, 5, 5, 8), // margins by default, in order (left, top, right, bottom)
 I think this might work,
$html2pdf = new HTML2PDF('P', 'A4', 'en', true, 'UTF-8', array(0, 0, 0, 0));

**Comment by gersonlimadev** [comment]
To fix it, I've added a negative margin to all lists, like this:
```css
ul { margin-left: -20px; }
```
