### ISSUE TITLE
Empty page !

### ISSUE THREAD

**Issue by Anouchka25** [spipu/html2pdf#318]
Hi
Please, help me, i get a empty page when i generate my pdf with html2pdf. I don't understand where come this bug, help me. 
This is my code, thanks:

```
<?php
require_once 'connexion.php';
date_default_timezone_set('Europe/Berlin');
require_once dirname(__FILE__).'/vendor/autoload.php';
require_once 'connexion.php';

use Spipu\Html2Pdf\Html2Pdf;
ob_start();
$str = '
    <page backtop="20mm" backright="10mm" backbottom="20mm" backleft="10mm">
    <style type="text/css">
    <!--
    table{width: 100%; border-collapse:collapse; font-size:18px}
    .header td{width: 50%; vertical-align: top}
    .text-left{text-align: left}
    .text-right{text-align: right}
    .text-center{text-align: center}
    .separator{height: 50px; width: 100%}
    .content td{border:solid 1px #CFD1D2; padding: 5px;}
    .content th{border:solid 1px #000000; padding: 5px; background-color: #000000; color: #FFFFFF}
    .ligne1Content{background-color:#57B223}
    .couleurgris{background-color:#DDDDDD; height:auto;}
    .tht, .taxe, .ttc{font-size: 1.2em;}
    .ttc{color:#57B223}
    .couleurverte{background-color: #57B223}
    .couleurmoinsgris{background: #EEEEEE;}
    .taille1{width:30%;}
    .taille2{width:15%;}
    .taille3{width:25%; }
    .taille4{width:20%;}
    .taille5{width:10%;}
    .header1{width:50%}
    .header2{width:50%}
    .tailleligne{height:200px}
    .taille1, taille2, taille3, taille4, taille5{height:auto;}
    -->
    </style>
';

$resFC1=$base->prepare("SELECT * FROM infosfacture WHERE num= ?");
$resFC1->bindValue(1, $id, PDO::PARAM_INT);
$resFC1->execute(array($_GET['num']));

$resultat1= $resFC1->fetch(PDO::FETCH_ASSOC);

//var_dump($resultat1);

//foreach ($resultat1 as $req){
    //$conditions = $req['conditions'];
//var_dump($resultat1['facturede']);
//var_dump($req['client']);
//var_dump($req['num']);
//var_dump($req['datefacture']);
    $str .= '
        <table class="header">
            <tr>
                <td class="text-left"></td>
                <td class="text-right"><b>'.$resultat1['facturede'].'</b><br></td>
            </tr>
        </table>
        <div class="separator"></div>
        <table class="header">
            <tr>
                <td class="text-left"><b>'.$resultat1['client'].'</b><br></td>
                <td class="text-right"></td>
            </tr>
        </table>
        <div class="separator"></div>
        <table>
            <tr>
                <td class="text-left header1">N° de facture: <b>'.$resultat1['num'].'</b>  </td>
                <td class="text-right header2">Date: <b>'.$resultat1['datefacture'].'</b></td>
           </tr>
        </table>

    ';
//}

$str .= '
    <br/><br/>
    <table class="content">
    <thead>
    <tr class="ligne1Content">
        <td class="text-left couleurgris taille1"><b>DESIGNATION</b></td>
        <td class="text-center couleurmoinsgris taille2"><b>QUANTITE</b></td>
        <td class="text-center couleurgris taille3"><b>PRIX HT</b></td>
        <td class="text-center couleurgris taille5"><b>TAXE</b></td>
        <td class="text-center couleurverte taille4"><b>TOTAL HT</b></td>
    </tr>
    </thead>
    <tbody>
';

$resFC = $base->prepare('SELECT infosfacture.num, infosfacture.client, infosfacture.datefacture, infosfacture.facturede, infosfacture.conditions, facturation.designation, facturation.quantite, facturation.prixht, facturation.taxe
    FROM infosfacture
    INNER JOIN facturation
    ON infosfacture.num=? AND facturation.fk_facturation_id=infosfacture.id');
$resFC->execute(array($_GET['num']));

$resultat= $resFC->fetchAll(PDO::FETCH_ASSOC);

$somme = 0;
foreach ($resultat as $req):
    $str .= '
        <tr class="couleurgris">
          <td class="text-left couleurgris taille1">'.$req['designation'].'</td>
          <td class="text-center couleurmoinsgris taille2">'.$req['quantite'].'</td>
          <td class="text-center taille3">'.$req['prixht'].'</td>
          <td class="text-center taille5">'.$req['taxe'].'</td>
          <td class="text-center couleurverte taille4">'.($req['quantite'] * $req['prixht']).'</td>
        </tr>
    ';
$sommeht += $req['prixht'] * $req['quantite'];
endforeach;

$str .= '
    </tbody>
    <tfoot>
        <tr>
        <td colspan="4" class="text-right tht">TOTAL HT</td>
        <td class="tht text-center">'.$sommeht.'</td>
        </tr>';
        $sommetaxe = 0;
        foreach ($resultat as $req):
          $prixtotalht=$req['prixht'] * $req['quantite'];
          $prixtaxe=$prixtotalht * $req['taxe']/100;
      $str .= '
      <tr>
          <td colspan="4" class="text-right tht">TAXE à '.$req['taxe'].' % </td>
          <td class="text-center">'.$prixtaxe.' </td>
      </tr>
      ';

        $sommetaxe += $prixtaxe ;
        endforeach;

        $str .= '
        <tr>
          <td colspan="4" class="text-right tht">TOTAL TTC</td>
          <td class="text-center">'.($sommeht + $sommetaxe).'</td>
        </tr>

        <tr>
        <td colspan="5"><h3>Conditions et moyens de paiement:</h3><br/>'.$resultat1['conditions'].'</td>
        </tr>
    </tfoot>
    </table>
    ';
    //}
    $str .= ' </page> ';

/*
 * On instancie notre constructeur
 * On affiche le contenu
 * On génére notre PDF
 */

 $str = ob_get_clean();

$pdf = new HTML2PDF('P','A4','fr','true','UTF-8');
$pdf->writeHTML($str);
$pdf->Output('facture.pdf');
?>

```

**Comment by jhonnymakis** [comment]
Try to add:
`$pdf = new HTML2PDF('P','A4','fr','true','UTF-8');
$pdf->setModeDebug();
...`

And add this at the beginning
`<?php
error_reporting(E_ALL);
ini_set('display_errors', true);

require_once 'connexion.php';`

**Comment by jhonnymakis** [comment]
This is my code to create a PDF:

require_once LIBRARY_PATH . '/HTML2PDF/HTML2PDF.php';
$html2pdf = new HTML2PDF('P', 'A4', 'pt', true, 'UTF-8', [2, 20, 2, 5]);
$html2pdf->writeHTML($relatorioViewConteudo);
$html2pdf->pdf->SetAuthor(SISTEMA_NOME);
$html2pdf->pdf->setJPEGQuality(100);
$html2pdf->pdf->setWordSpacing(0);
$html2pdf->pdf->SetTitle(mb_strtoupper($serviceRelatorio->inventario->pessoa));
$html2pdf->createIndex(null, 12, 12, false, true, 2);
$html2pdf->Output($uploadPath . $fileName, 'F');

**Comment by jhonnymakis** [comment]
Did you check if the script is creating the PDF file?
Try to change:
$pdf->Output('facture.pdf');
For this:
$pdf->Output('facture.pdf', 'F');

**Comment by Anouchka25** [comment]
With $pdf->Output('facture.pdf', 'F'); ===> I have this error:

> Warning: fopen(): remote host file access not supported, file://facture.pdf in /homepages/0/d513201601/htdocs/Facturation_generale/vendor/tecnickcom/tcpdf/include/tcpdf_static.php on line 1854
> 
> Warning: fopen(file://facture.pdf): failed to open stream: no suitable wrapper could be found in /homepages/0/d513201601/htdocs/Facturation_generale/vendor/tecnickcom/tcpdf/include/tcpdf_static.php on line 1854
> 
> Fatal error: Uncaught exception 'Exception' with message 'TCPDF ERROR: Unable to create output file: facture.pdf' in /homepages/0/d513201601/htdocs/Facturation_generale/vendor/tecnickcom/tcpdf/tcpdf.php:2927 Stack trace: #0 /homepages/0/d513201601/htdocs/Facturation_generale/vendor/tecnickcom/tcpdf/tcpdf.php(7681): TCPDF->Error('Unable to creat...') #1 /homepages/0/d513201601/htdocs/Facturation_generale/vendor/spipu/html2pdf/src/Html2Pdf.php(549): TCPDF->Output('facture.pdf', 'F') #2 /homepages/0/d513201601/htdocs/Facturation_generale/imprimerpdf.php(162): Spipu\Html2Pdf\Html2Pdf->output('facture.pdf', 'F') #3 {main} thrown in /homepages/0/d513201601/htdocs/Facturation_generale/vendor/tecnickcom/tcpdf/tcpdf.php on line 2927

**Comment by jhonnymakis** [comment]
First you need to give write permission on the folder that you are trying to save the file.

You can do that:
Terminal:
sudo chmod folderName/ 777

or the best way:
chown www-data:www-data folderName/

**Comment by Anouchka25** [comment]
I put it :  $pdf->Output('/Facturation_generale/fichierspdf/facture.pdf', 'F');  and i put fichierspdf/777 ===> but i have this error:

> Warning: fopen(file:///Facturation_generale/fichierspdf/facture.pdf): failed to open stream: No such file or directory in /homepages/0/d513201601/htdocs/Facturation_generale/vendor/tecnickcom/tcpdf/include/tcpdf_static.php on line 1854
> 
> Fatal error: Uncaught exception 'Exception' with message 'TCPDF ERROR: Unable to create output file: /Facturation_generale/fichierspdf/facture.pdf' in /homepages/0/d513201601/htdocs/Facturation_generale/vendor/tecnickcom/tcpdf/tcpdf.php:2927 Stack trace: #0 /homepages/0/d513201601/htdocs/Facturation_generale/vendor/tecnickcom/tcpdf/tcpdf.php(7681): TCPDF->Error('Unable to creat...') #1 /homepages/0/d513201601/htdocs/Facturation_generale/vendor/spipu/html2pdf/src/Html2Pdf.php(549): TCPDF->Output('/Facturation_ge...', 'F') #2 /homepages/0/d513201601/htdocs/Facturation_generale/imprimerpdf.php(162): Spipu\Html2Pdf\Html2Pdf->output('/Facturation_ge...', 'F') #3 {main} thrown in /homepages/0/d513201601/htdocs/Facturation_generale/vendor/tecnickcom/tcpdf/tcpdf.php on line 2927

**Comment by jhonnymakis** [comment]
You need to enter the full path here:
$pdf->Output('/homepages/0/d513201601/htdocs/Facturation_generale/facture.pdf', 'F');

This error means that the script can't write the file on that folder because it can't find it.

**Comment by Anouchka25** [comment]
Ok i enter : $pdf->Output('/homepages/0/d513201601/htdocs/Facturation_generale/facture.pdf', 'F');

But i have a empty pdf page !

**Comment by jhonnymakis** [comment]
Ok, try this:

echo $str;
$html = ob_get_clean();

$pdf = new HTML2PDF('P','A4','fr','true','UTF-8');
$pdf->writeHTML($html);
$pdf->Output('facture.pdf');

**Comment by Anouchka25** [comment]
I have a empty html page with it, i haven't pdf page but empty html page:
```
echo $str;
$html = ob_get_clean();

$pdf = new HTML2PDF('P','A4','fr','true','UTF-8');
$pdf->writeHTML($html);
$pdf->output('/homepages/0/d513201601/htdocs/Facturation_generale/fichierspdf/facture.pdf', 'F');
```

**Comment by jhonnymakis** [comment]
Ok, let's try this:

Create a new file and put this:

# Import HTML2PDF Library here..

$pdf = new HTML2PDF('P','A4','fr','true','UTF-8');
$pdf->writeHTML('<h1>Hello Anouchka25</h1>');
$pdf->output('/homepages/0/d513201601/htdocs/Facturation_generale/fichierspdf/facture.pdf', 'F');

**Comment by Anouchka25** [comment]
I have always a empty page, i think that my server has e problem. The simple code should work fine. Please Let me find the solution on the side of my server.

**Comment by Anouchka25** [comment]
My code work fine. My code worked not because i commited vendor folder. I re-install vendor et all works fine, i have a pdf file beautiful ^^ !
