### ISSUE TITLE
font-size: xx-large in html2pdf fail

### ISSUE THREAD

**Issue by ovimax** [spipu/html2pdf#320]
Hi there;

I try to create HTML2PDF, grabbing the html from a TinyMCE, but the HTML2PDF doesn't reconize the font-size, and the font-family that the TinyMCE use. I try to applay the font-size to a test and it doesn'work.

TEST:

```
<?php

require __DIR__.'/vendor/autoload.php';

$html2pdf = new Html2Pdf();
$html2pdf->writeHTML('<h1>HelloWorld</h1>This is my first test<p style="font-size: xx-large;">HOLA MUNDO</p>');
$html2pdf->output();
```

Version TyniMCE Version 3.4.2

Any idea?, Thanks

**Comment by spipu** [comment]
it will be adde in the next release
