### ISSUE TITLE
How send my pfd file in mail ?

### ISSUE THREAD

**Issue by Anouchka25** [spipu/html2pdf#321]
Hi

How send my pfd file in mail ? I would like file is sent to user who connected. Please how do it ?
This is my code that work fine :
```
require_once dirname(__FILE__).'/vendor/autoload.php';
//require_once 'connexion.php';

use Spipu\Html2Pdf\Html2Pdf;
ob_start();
echo $str;
$html = ob_get_clean();
$pdf = new HTML2PDF('P','A4','fr','true','UTF-8');
$pdf->writeHTML($html);
$pdf->output('facture.pdf');
```

**Comment by LittleBigFox** [comment]
Hi!
You have to write your file to disk first
`$pdf->output('facture.pdf', 'F');`
Then use mailTo php function, or phpmailer.
Regards,
LBF
