### ISSUE TITLE
Unable to get the size of the image ....

### ISSUE THREAD

**Issue by honsberg** [spipu/html2pdf#323]
please help. 

Unable to get the size of the image [http://www.onlinembe.de/barcode4j/generaBarcode?type=code128&msg=DE0998-1-00001160-01&height=15mm&mw=0.4&hrp=none&fmt=gif]

the image is visible when opening in firefox.
what can i do.

**Comment by jorgerenteral** [comment]
Same problem, but the problem started yesterday, before thatit was working good

**Comment by jorgerenteral** [comment]
It works, the problem was, in local server allow_url_fopen was on, but on my online server it was off.

**Comment by oboydak** [comment]
Same error. The problem  started today.

**Comment by spipu** [comment]
`allow_url_fopen` php setting must be set to `On`.
maiby you have the same hosting, and they have change the default php configuration

**Comment by oboydak** [comment]
Hi

Thank you for answer

This settings is correct
On 31 Jul 2018, at 11:34, Laurent MINGUET <notifications@github.com<mailto:notifications@github.com>> wrote:


allow_url_fopen php setting must be set to On.
maiby you have the same hosting, and they have change the default php configuration
