### ISSUE TITLE
Use in TYPO3 Framework

### ISSUE THREAD

**Issue by iTommix** [spipu/html2pdf#326]
Hi @all,

how can i use this in TYPO3  within my own Extension (Backend-Module)?

Actually i put all Contens of "src" in a path called "Spipu/Html2Pdf" while the Namespace of my Script is
`namespace Vendor\Newsletter\Controller\BackendModule;`

and try to load with
`use Spipu\Html2Pdf\Html2Pdf;` 

I tried also with a part of my Namespace:
`use Vendor\Newsletter\Spipu\Html2Pdf\Html2Pdf;`

Both gave me an error "not found"

Any ideas?
Regards

**Comment by spipu** [comment]
did not put the contents manually.
you must install it throw composer.
https://github.com/spipu/html2pdf/blob/master/doc/install.md
