### ISSUE TITLE
Hyperlinks to local sections

### ISSUE THREAD

**Issue by robov** [spipu/html2pdf#327]
When i have a html document that includes local anchor links to other sections in the document (interactive TOC). The interactivity is not working in the pdf while it is working in the html doc
Any ideas ?

I href the link to the anchor text:
<a href="#introduction">Introduction</a>
and it jumps to
<span id="introduction">&nbsp;</span><h1>introduction</h1>

Although this is working fine in my html, it is not working in the generated pdf

**Comment by spipu** [comment]
look at the example 7 to see how it works 
Anchor:
```<a name="my_anchor"></a>```

Link:
```<a href="#my_anchor">My Link</a>```
