### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by donny26utama** [spipu/html2pdf#33]
hello, i just use html2pdf on my localhost. then open it in url localhost/html2pdf/example. then i click the qrcode.php. just show the php not directly show download message. the i tried to copy the url and paste it into the other browser and its directly show the download message. can you explain to me why?

**Comment by fagundes** [comment]
It's a bad config on your websever!

**Comment by donny26utama** [comment]
ok. thx for your answer.

**Comment by juchi** [comment]
Hi,
Is your problem solved or do you still have issues with the lib ?

**Comment by donny26utama** [comment]
yeah, the problem was clearly... idm the suspect are. if anyone have
installed idm on their pc, they must use alt button to download the qrcode.
thx a lot of to response my question. i learn so much from you. sorry for
my bad english.

2015-12-23 15:34 GMT+07:00 Julien Chichignoud <notifications@github.com>:

**Comment by juchi** [comment]
Thanks for the solution to yur problem. I'll close the issue then.
