### ISSUE TITLE
Cannot trigger printing

### ISSUE THREAD

**Issue by Williams90** [spipu/html2pdf#330]
Hello, first of all I would like to thanks any help and excuse if my question is too dumb.

I managed to integrate html2pdf into my wordpress site and its working fine, but:

I need html2pdf to export not only a DIV content, but also a custom text that its not currently displayed in the page content.

To do that, I managed to pass the DIV content + the custom content to be printed into a new window.
This new window wont use any script that is being loaded into the domain, so they have to be manually inserted.

I have done it using this code:

```
printWindow.document.write('<script type="text/javascript" src="http://www.mywebsiteurl.com/descargarPDF.js"><\/script>'); 
printWindow.document.write('<script type="text/javascript" src="http://www.mywebsiteurl.com/html2pdf.bundle.min.js"><\/script>');
```

/descargarPDF.js pops out this simple function:
```

function eKoopman2() {
  var element = document.getElementById('carta');
  html2pdf(element);
}
```

And full code of the script popping out the new window is here:

```
jQuery(document).ready(function( $ ){
          $("#imprimirPdf").live("click", function () {
            var divContents = $("#cartaDeAmor").html();
            var printWindow = window.open('', '', 'height=400,width=800')
            printWindow.document.write('<!DOCTYPE html>');    
            printWindow.document.write('<html>');  
            printWindow.document.write('<head>');      
printWindow.document.write('<script type="text/javascript" src="http://www.mywebsiteurl.com/descargarPDF.js"><\/script>');         
printWindow.document.write('<script type="text/javascript" src="http://www.mywebsiteurl.com/html2pdf.bundle.min.js"><\/script>');         
            printWindow.document.write('</head>');
            printWindow.document.write('<div id="carta">Content to be exported</div>');
            printWindow.document.write('<input type="button" value="Function trigger test" onclick="eKoopman2();">');
            printWindow.document.write('</html>');  
            printWindow.document.close();
});
});
```

And the HTML source coded generated by script is this one:

```
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="http://www.mywebsiteurl.com/descargarPDF.js"></script>
<script type="text/javascript" src="http://www.mywebsiteurl.com/html2pdf.bundle.min.js"></script>
</head>
<div id="carta">Content to be exported</div>
<input type="button" value="Function trigger test" onclick="eKoopman2();"></html>
```

But then, the trigger button is not working as it is currently doing on the main domain (not the window opened by the previous JS script).

Am I missing any script to be loaded?

Is there any way to export to PDF the DIV content + some custom content so I dont really have to worry about popping a new window with the extra custom content? 

I have tried the next but didnt work:

```
function eKoopman2() {
  var element = document.getElementById('carta');
  html2pdf(element) + "Custom content";
}
```

Thanks you so much in advance

**Comment by spipu** [comment]
you are not on the good project
>> https://github.com/eKoopmans/html2pdf
