### ISSUE TITLE
Affichage # en numérotation pied de page.

### ISSUE THREAD

**Issue by Macoss117** [spipu/html2pdf#331]
Bonjour tout le monde, j'espères qu'il y a des français qui liront ce message.

Je rencontre des soucis depuis que nous avons mis la dernière version d'html2pdf pour fonctionner avec notre serveur en PHP7.
Tout les documents générés contenant plusieurs ou une seul page, la numérotation de la dernière page est affichée "######".

Merci pour votre aide, si vous une solution je suis preneur.

Bonne soirée.

**Comment by quimcalpe** [comment]
possible duplicate of #294 

Bug is closed but only in master, awaiting a new release by @spipu with the fix...

**Comment by spipu** [comment]
it will be fixed in the next release
