### ISSUE TITLE
Placing ToC

### ISSUE THREAD

**Issue by arget888** [spipu/html2pdf#333]
Hello,

I want to place the Table of Content with the createIndex() method after the heading of my document. 
My Problem is, that the ToC is just overlayed of the normal content.

My html Code looks like:
```<page>
<h1>Heading of the Document</h1>
<bookmark title="Summary" level="0"></bookmark>
<h1>First Chapter</h1>
<bookmark title="First Chapter" level="0"></bookmark>
<p>Content of first Chapter</p>
<h1>Second Chapter</h1>
<bookmark title="Second Chapter" level="0"></bookmark>
<p>Content of second Chapter</p>
</page>
```

The php Code looks like:
```$this->html2pdfwriter = new Html2Pdf("P","A4","de",true,"UTF-8",array(20,25,10,15));
$this->html2pdfwriter->pdfSetDisplayMode("fullpage");
$this->html2pdfwriter->setTestTdInOnePage(false);
$this->html2pdfwriter->writeHTML($html);
$this->html2pdfwriter->createIndex("Summary",20,15,true,true,1);
```

The result is, that the ToC is above my Heading of the Document but I want to place it under it.

**Comment by spipu** [comment]
hi, 

a new parameter $marginTop will be added to the createIndex method on the next release
