### ISSUE TITLE
attachments with mailin.

### ISSUE THREAD

**Issue by Jammerdan** [spipu/html2pdf#334]
> Part of the code

```
ob_start();
    
$content 		=	'jhgjhgj Dit ziet er goed uit';
$html2pdf 		=	new Html2Pdf('P', 'A4', 'nl');
$html2pdf		->	setDefaultFont('Arial');
$html2pdf		->	writeHTML($content);
$contentPdf		=	$html2pdf->output('', true);

$attachment_content = chunk_split(base64_encode($contentPdf));
$attachment = array('myfilename.pdf'=>$attachment_content);
```

When I execute script (in combination with mailin [v2] (SendInBlue), I get the following message:

> Fatal error: Uncaught Spipu\Html2Pdf\Exception\Html2PdfException: The output destination mode [1] is invalid in /var/www/vhosts/example.com/subdomain.example.com/common/html2pdf/src/Html2Pdf.php:531 Stack trace: #0 /var/www/vhosts/davenschot19.nl/vloer.davenschot19.nl/index2.php(51): Spipu\Html2Pdf\Html2Pdf->output('', '1') #1 {main} thrown in /var/www/vhosts/example.com/subdomain.example.com/common/html2pdf/src/Html2Pdf.php on line 531 

When I change 
`$contentPdf		=	$html2pdf->output('', true);`  
to 
`$html2pdf->output('test.pdf'); `
it perfectly generates the pdf.

What am I missing here...??

**Comment by Jammerdan** [comment]
Found it: 
`$contentPdf 	=	$html2pdf->output('example.pdf', 'S');`

**Comment by spipu** [comment]
look at the doc ;)
https://github.com/spipu/html2pdf/blob/master/doc/output.md
