### ISSUE TITLE
Css3

### ISSUE THREAD

**Issue by Angelgalan27** [spipu/html2pdf#335]
Buenas tardes, me gustaria saber si es compatible html2pdf con css3, mas concretamente con flexbox ya que lo estoy intentando pero esta fallando.

Un saludo.

**Comment by LittleBigFox** [comment]
Hi!

Some CSS rules work, but not flexbox, for now ...

**Comment by spipu** [comment]
i will not implement flex and other CSS, because, you are not creating a html for a browser, but for a static pdf format => you have not to use flex

**Comment by Nielsbishere** [comment]
I think using flex is handy though, and it very much helps with rendering modern-ish sites and/or templates.
I'd at least recommend you to please throw an error if flex is encountered, because I was debugging why it wasn't working for a while.
