### ISSUE TITLE
OU télécharger ?

### ISSUE THREAD

**Issue by pasbonte** [spipu/html2pdf#336]
Bonjour
Je suis habitué aux logiciels mais là je ne vois pas...
dsl

**Comment by LittleBigFox** [comment]
Bonjour,

Vous devez utiliser Composer pour installer html2pdf: https://getcomposer.org/download/
Une fois Composer installé, l'installation ne dure que quelques secondes.

Bonne journée!

**Comment by pasbonte** [comment]
Bonjour
Merci
Maius j'installe composer et il me demande: Choose the command line PHP...

**Comment by spipu** [comment]
Html2pdf n’est pas un programme qu’on installe, c’est une librairie php à utiliser ds un autre programme php.
Vous ne pourrez rien en faire directement

**Comment by pasbonte** [comment]
Je sais je veux la librairie c'est tout.


Cordialement
Bonte Pascal
P Afin de contribuer au respect de l'environnement, merci de n'imprimer ce
mail qu'en cas de nécessité.

Le 14 juin 2018 à 09:16, Laurent MINGUET <notifications@github.com> a écrit
:

**Comment by pasbonte** [comment]
Je sais je veux la librairie c'est tout.

**Comment by spipu** [comment]
tout est marqué dans la doc d'install ;)

https://github.com/spipu/html2pdf/blob/master/doc/install.md

**Comment by lenamtl** [comment]
@spipu  pour quelle raison vous ne publiez pas un package avec le dossier Vendor déjà généré?

J'essai de comprendre la différence entre une version que je génère avec Composer 
et une version que vous générez avec Composer?

**Comment by spipu** [comment]
parce que ce n'est pas comme ca que ca fonctionne :)
il ne faut pas cloner ce repo git...
il faut installer ce package via composer.

**Comment by lenamtl** [comment]
Ce que je veux dire c'est qu'une fois le package est généré par Composer celui-ci pourrait être distribuable
et pourrait s'utiliser dans n'importe quel projet.

Le package généré par Composer : comprend le dossier Vendor qui comporte 3 dossiers avec des classes php (composer, spipu, technikcom et un fichier autoload.php) ainsi que les 2 fichiers composer composer.json et composer.lock
