### ISSUE TITLE
Installer Html2Pdf sans tous les fichiers inutiles

### ISSUE THREAD

**Issue by Frenezy90** [spipu/html2pdf#337]
Bonjour,
J'utilise Html2Pdf pour générer mon PDF mais depuis la version 5 on ne peut pas l'utiliser sans composer.

Le problème est qu'il me génère 565 fichiers et 44 fichiers et que la moitié des fichiers me sont totalement inutiles comme les exemples ..

![html2pdf](https://user-images.githubusercontent.com/40271117/41419245-db77938c-6ff1-11e8-912f-36e77933502e.PNG)

Comment utiliser seulement ce qui m'intéresse, c'est à dire la génération de PDF?

Je pense utiliser le composer correctement, j'ai fait:

`composer require spipu/html2pdf`

Et après (dans le dossier):

`composer install --no-dev`

Suis-je obligé de parcourir tous les dossiers et de supprimer les fichiers manuellement ?

Pouvez-vous mettre en place un gitignore afin que l'on puisse uniquement utiliser les fichiers nécessaires au bon fonctionnement de Html2Pdf ?

Merci

**Comment by spipu** [comment]
le problème ne vient pas d'HTML2PDF mais de la dépendance TCPDF : 

```
48K	./vendor/composer
1,6M	./vendor/spipu
32M	./vendor/tecnickcom
33M	./vendor
33M	
```

**Comment by lenamtl** [comment]
C'est le dossier fonts qui prend beaucoup de place

Tu peux garder uniquement ceux dont tu as besoin 
(tu peux toujours en ajouter par la suite)

C'est le helvetica qui est par défaut (chaque font a 3 fichiers et certain ont un dossier aussi)

- fonts/helvetica.php 
- fonts/pdfahelvetica.php 
- fonts/pdfahelvetica.z 

J'ai gardé 3 fonts et le dossier pese 600 ko au lieu de 27 meg
