### ISSUE TITLE
Line number of tokens is wrong when <style> tags exists

### ISSUE THREAD

**Issue by naitsirch** [spipu/html2pdf#338]
If there are style tags in the html, they are removed from the html before the lexing process starts. This results in wrong line numbers for the tokens.

Usually this is no problem, but if there is an error in the html (e.g. tags are closed in a wrong order) and you try to find the error the wrong line number makes it more difficult.

imho there are two solutions:

1. Replace the style content with new lines of the same number than they exists in the removed style  contend
2. Don't remove the style tags and their content. Just don't print it to the PDF.

**Comment by spipu** [comment]
thanks, i will check this

**Comment by spipu** [comment]
it will be fixed in the next release
