### ISSUE TITLE
India Rupee icon not showing in PDF

### ISSUE THREAD

**Issue by manojsinghadha** [spipu/html2pdf#343]
I am trying to show Indian currency (INR) sign in PDF content BUT it not showing correct icon.
Any one has idea, how to add INR sign with default font library

**Comment by lenamtl** [comment]
Hi,

Are you using default font or custom?
Does the font you are using can display it?

Are you using UTF-8?
$pdf = new HTML2PDF('P','LETTER','fr','true','UTF-8');

Some idea you can use str_replace or other replacement depending of the code language you are using.
 also it seems possible to load subset
see this post for similar issue:
https://stackoverflow.com/questions/33217525/special-unicode-character-in-html2pdf

If you need to convert font for TCPDF
https://www.experts-exchange.com/questions/27118197/Convert-Font-file-for-TCPDF.html

**Comment by spipu** [comment]
it works for me:

```
<?php
require_once dirname(__FILE__).'/../vendor/autoload.php';

use Spipu\Html2Pdf\Html2Pdf;
use Spipu\Html2Pdf\Exception\Html2PdfException;
use Spipu\Html2Pdf\Exception\ExceptionFormatter;

try {
    $html2pdf = new Html2Pdf('P', 'A4', 'fr');

    $content = '<page style="font-family: freeserif"><br />10₹</page>';

    $html2pdf->pdf->SetDisplayMode('real');
    $html2pdf->writeHTML($content);
    $html2pdf->output('utf8.pdf');
} catch (Html2PdfException $e) {
    $html2pdf->clean();

    $formatter = new ExceptionFormatter($e);
    echo $formatter->getHtmlMessage();
}
```
you did not use the good font
