### ISSUE TITLE
 $html2pdf->Output('example.pdf','S'); 

### ISSUE THREAD

**Issue by aaiglesias85** [spipu/html2pdf#346]
Hello 

I have a problem I can not export to pdf, I never run this method $ html2pdf-> Output ('example.pdf', 'D'), if I write $ html2pdf-> Output ("C: \ Work \ example.pdf" ); Yes, what can you be?

 Code
 
use Spipu\Html2Pdf\Html2Pdf;
use Spipu\Html2Pdf\Exception\Html2PdfException;
use Spipu\Html2Pdf\Exception\ExceptionFormatter;

 $html = $this->render('flight/flight-print-row.html.twig', array(
        'recordsArr'   => $responseArr     
   ));
      $html_template = $html->getContent();  

try {
        ob_start();                
        $html2pdf = new Html2Pdf('P', 'A4', 'fr');
        $html2pdf->setDefaultFont('Arial');
        $html2pdf->pdf->SetDisplayMode('fullpage');
        $html2pdf->writeHTML($html_template);       
        $html2pdf->Output('example.pdf','D'); 
        // $html2pdf->Output("C:\Work\example.pdf", "F");  
       
       
      } catch (Html2PdfException $e) {
        $html2pdf->clean();
        $formatter = new ExceptionFormatter($e);
        $formatter->getHtmlMessage();
      }

regards

**Comment by lenamtl** [comment]
Try absolute path

**Comment by aaiglesias85** [comment]
Hello @lenamtl it works with absolute path, but I need to work with any path

**Comment by spipu** [comment]
Hi,
only the F output type accept absolute paths. For all the other output types, you must only provide the basename of your pdf file.

https://github.com/spipu/html2pdf/blob/master/doc/output.md
