### ISSUE TITLE
The html tag [br] is not known by Html2Pdf.

### ISSUE THREAD

**Issue by naitsirch** [spipu/html2pdf#348]
Is there a reason why this fundamental tag `<br>` is not supported?

**Comment by lenamtl** [comment]
Hi,

it is supported... Do you a have any error message?
Does your code is W3C valid?

**Comment by naitsirch** [comment]
Hi.
The issue topic was just copy and pasted from an exception message thrown bei html2pdf.

Am 17.07.2018 19:05 schrieb lenamtl <notifications@github.com>:Hi,
it is supported... Do you a have any error message?
Does your code is W3C valid?

**Comment by spipu** [comment]
it is supported, look at the examples.
https://github.com/spipu/html2pdf/blob/master/examples/res/exemple00.php
what is your hml code  sample ?

**Comment by naitsirch** [comment]
Sorry, after I got this error message I decided to switch to DomPDF. It is more stable and standards-compliant (HTML and CSS) than Html2Pdf. Therefore I had to change the HTML and CSS, so that I have not the HTML that produced that error.

I'll close this issue.

**Comment by elobo** [comment]
The html tag [q] is not known by Html2Pdf. You can create it and push it on the Html2Pdf GitHub project.

**Comment by vik0shkum0r** [comment]
The html tag [button] is not known by Html2Pdf. sir can you help me to solve this.
