### ISSUE TITLE
print without open in browser

### ISSUE THREAD

**Issue by udara86** [spipu/html2pdf#351]
I have used html2pdf module to generate the barcode. Now barcode is open in a new browser and then need to print it...

I want to reduce a few button clicks. That means once click on, that should directly open the printer dialog box without opening the pdf.

I highly appreciate anyone of your support for this.

Thanks

**Comment by udara86** [comment]
Hi Lenamtl, Thanks for your quick support. But I couldn't find parameter option for direct print from your resource URL...

Could you please support me to utilize existing parameter for my requirement?

Thanks and waiting for your response.
Bye

**Comment by spipu** [comment]
it is not possible to print directly without opening a url...
