### ISSUE TITLE
HTML Compliance?

### ISSUE THREAD

**Issue by LittleBigFox** [spipu/html2pdf#359]
Hi!

Just a question... Does html2pdf have a HTML level compliance? HTML5, HTML4 ?

For example, does it be interesting to create tag like CENTER,  RIGHT, LEFT, and others HTML5 not supported tag?

I ask this because some RichText Editor still use them, and it could be fair to support it...

i know it's not the purpose of Html2PDF of using this kind of editor, but it could get a widest scope :)

Regards,
LBF

**Comment by spipu** [comment]
thoses html tag have been deprecated in HTML4...

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

=> they must no be used since 1999

**Comment by LittleBigFox** [comment]
Yes I know, I'm in HTML5/CSS3 too, but I asked for information :)

https://www.tutorialspoint.com/html5/html5_deprecated_tags.htm

There is some tags deprecated in html5, but defined in the tag\html directory, that's why i ask what is the level of compliance of Html2PDF ;)

**Comment by spipu** [comment]
It is html 4/5

**Comment by LittleBigFox** [comment]
Ok thanks!
