### ISSUE TITLE
Bump the PHP minimum version

### ISSUE THREAD

**Issue by juchi** [spipu/html2pdf#36]
In order to be able to get PSR4 we'll need to upgrade at least to PHP 5.3
Since the current minimum supported version of PHP is 5.5, we may also discuss which minimum version is more relevant.
As it's a breaking change, i think this should target the 5.0 release

**Comment by boussou** [comment]
+1 ;-)

**Comment by fagundes** [comment]
@boussou I agree with you. The first step is update to 5.3, once TCPDF is a major dependency and it has as mininum supported version PHP 5.3. But we should update after that to PHP 5.4 and newest versions.

And yes, @juchi is BC even if we change to 5.3, so target 5.0 release is a great idea.

**Comment by spipu** [comment]
it is done on the master branch (target 4.5.0), with the TCPDF update version.
Now, the minimum supported version of PHP is 5.3.2 (like composer).

**Comment by fagundes** [comment]
I just saw that, my proposal was to do something like that [fagundes/html2pdf:bump-php-minimum-version](https://github.com/fagundes/html2pdf/tree/bump-minimum-php-version).

Move all classes to src. And change classes name, using PSR-2 standard. My next move would be change methods name to be on PSR-2 standard.

**Comment by fagundes** [comment]
I saw you guys have updated like my branch. I will delete it.

If you need to share same tasks with me. I'm available to help.

**Thank you for this development so fast!**

**Comment by boussou** [comment]
Great work. 
I'll check it out on my side in a few days.

(Remark: I will also look at the real benefits we are supposed to get with this effort)
