### ISSUE TITLE
Table with td and colspan attributes: wrong width calculation

### ISSUE THREAD

**Issue by jessylennesl** [spipu/html2pdf#360]
Hey,

I have a problem (in version ^5.2) with this HTML:

**Don't work:**
```html
<table>
    <thead>
        <tr>
            <td>One</td>
            <td colspan="2">Two</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="3">Three</td>
        </tr>
    </tbody>
</table>
```

The "Two" cell appear outside the table, with a width of 0

I need to add another line to help the lib understand what i want:

**Works:**
```html
<table>
    <thead>
        <tr>
            <td>One</td>
            <td colspan="2">Two</td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="3">Three</td>
        </tr>
    </tbody>
</table>
```

----

Expecting:
We should be able to use two rows and colspan

----

Thanks for your help!

**Comment by jessylennesl** [comment]
Precision:

With the "working" html and a table having a "width 100%", the cell's width is still badly calculated: the table goes outside the parent (the cells are too large)

**Comment by spipu** [comment]
In your case, why using colspan for the first line ? You create a third « virtual » column that html2pdf can not understand...

**Comment by jessylennesl** [comment]
@spipu thanks for your answer,

I simplified my case here, i have a more complex table for the project i'm working on which need those colspan:

I have a thead needing colspan in case of data, and if no data i have a tbody with a cell having full colspan:


```html
<table>
  <thead>
      <tr>
          <td>#</td>
          <td>A</td>
          <td>B</td>
          <td>C</td>
          <td>D</td>
          <td>E</td>
          <td>F</td>
          <td colspan="2">Colspan Here</td>
          <td colspan="2">MColspan Here</td>
      </tr>
      <tr>
          <td colspan="7"></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
      </tr>
  </thead>
  <tbody>
    <-- if data -->
    <tr>
      <td>.a..</td>
      <td>.b.</td>
      <td>..c</td>
      <td>d..</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <-- else -->
    <tr>
      <td colspan="11">
          NO DATA!
      </td>
    </tr>
    <-- /if -->
  </tbody>
</table>
```

Without the second line

```html
      <tr>
          <td colspan="7"></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
      </tr>
```

This don't work properly

**Comment by spipu** [comment]
and if you add <col ...> tags ?

**Comment by jessylennesl** [comment]
hey @spipu  thanks for your answer,

I'm still having the issue using <col...> tags:

```html
        <table border="1">
            <colgroup>
                <col><col><col>
            </colgroup>
            <thead>
                <tr>
                    <td style="padding: 1cm;">First column</td>
                    <td colspan="2" style="padding: 1cm;">Second column with a colspan of 2</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="3" style="padding: 1cm;">Third column with a colspan of 3</td>
                </tr>
            </tbody>
        </table>
```

Results in:
![screenshot-localhost-8080-2018 08 21-16-37-48](https://user-images.githubusercontent.com/18400429/44408475-bceea500-a560-11e8-9e58-cca2105a87dd.png)


I made an example out of it:
https://github.com/jessylennesl/html2pdf/blob/table-colspan-problem/examples/table-colspan.php

I tried to figure it out but \Spipu\Html2Pdf\Html2Pdf::_calculateTableCellSize is barely understandable for a novice.

Thanks for your help,
J.

**Comment by spipu** [comment]
fixed in the master branch.
will be in the next release
