### ISSUE TITLE
I need use it with arabic langaue

### ISSUE THREAD

**Issue by freeaed** [spipu/html2pdf#361]
Hey
thanks for ur work
i need generate file with Arabic content but it is not working

**Comment by LittleBigFox** [comment]
Hi!

Have you try this?
https://tcpdf.org/examples/example_018/
Html2PDF use TCPDF for generate PDF, i suppose this could help you?

Regards,
LBF

**Comment by awaistariq** [comment]
Did it help @freeaed ?
