### ISSUE TITLE
$html2pdf->pdf->setTextShadow();

### ISSUE THREAD

**Issue by nailug** [spipu/html2pdf#362]
Hello,

I would like to put one word in a pdf with a text shadow.
is there a way to do that with html2pdf ?
When I use
`$html2pdf->pdf->setTextShadow(array('enabled' => true, 'depth_w' => 0.5, 'depth_h' => 0.5, 'color' => array(0, 0, 0), 'opacity' => 0.5, 'blend_mode' => 'Multiply'));`
it enables text shadow in the whole pdf
When I use
`$html2pdf->pdf->setTextShadow();`
it disables it.
if I use WriteHTML between, it creates a new page.
Is there a way to insert a small text with shadow in the $html without applying the effect to the whole page ?
Thanks for your help

**Comment by spipu** [comment]
you can create your own shadow tag and your own tag extension, to create a specific tag that will manage the shadow :)

look at the doc to see how to do it
