### ISSUE TITLE
2 Additional blank Pages created

### ISSUE THREAD

**Issue by multicore-association** [spipu/html2pdf#363]
After converting an html file to pdf using html2pdf, I get 2 additional blank pages. How to avoid that?
Here is the code:
‘’’
		$html2pdf = new Html2Pdf("P", "LETTER", "en", true, "UTF-8");
		$html2pdf->writeHTML($html);
		$html2pdf->output($pdf_file, "F");
‘’’
here is the html:
‘’’
<page>
  <p class="secthead" style="text-align:center"><strong>Employee Evaluation Report</strong></p>
  <table width="100%"  border=0 cellpadding="4" cellspacing="2" bgcolor="#FFFFFF">
        <tr>
            <td><b>Employee:</b> Joe Blow</td>
            <td><b>Date of Hire:</b> 11/03/14</td>
        </tr>
        <tr>
            <td><b>Job Title:</b> Clerk</td>
            <td><b>Evaluation Rating Period: </b>1-2018 to 1-2018</td>
        </tr>
                <tr>
          <td colspan="2"><strong>Job Description:</strong> xxxxxxxxxxxxx</td>
        </tr>
        </table>
        <br>
        <table border=1 cellpadding="2" cellspacing="2" class="tbl_border" style="margin-left:10px" width="840">
        <tr>
            <td valign="top" width="360"><strong>Critical <br>
            Performance <br>
            Characteristics</strong></td>
            <td align="center" valign="top" width="120"><strong>Meets Work</strong><br>Performance<br>
Standards<br>
            (1)</td>
            <td align="center" valign="top" width="120"><strong>Needs Improvement</strong><br>
              To Meet Work <br />
              Performance Standards<br>
            (2)</td>
            <td align="center" valign="top" width="120"><strong>Unsatisfactory</strong><br>
Needs Formal <br />
Suggestions for Improvement<br>
            (3)</td>
        </tr>
                <tr>
            <td  width="360">11. Finishes Queue each day as required by management </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                       </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360">12. Is dependable and trustworthy </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                       </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360">13. Knows requirements of job, does a creditable job and accepts direction well </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                       </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360">14. Takes pride in what they are doing </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                       </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360">15. Gives 100% effort to the work that is assigned to them </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                       </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360">16. Wants to grow and become the best they can be </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                       </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360">17. Respects Supervisors and Management </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                       </td>
            <td align="center" width="120">
                        </td>
        </tr>
                </table><br>
        <table border=1 cellpadding="2" cellspacing="2" class="tbl_border" style="margin-left:10px" width="840">
        <tr>
            <td valign="top" width="360"><strong>Job<br>Duties</strong></td>
            <td align="center" valign="top" width="120"><strong>Meets Work</strong><br>Performance<br>
Standards<br>
            (1)</td>
            <td align="center" valign="top" width="120"><strong>Needs Improvement</strong><br>
              To Meet Work <br />
              Performance Standards<br>
            (2)</td>
            <td align="center" valign="top" width="120"><strong>Unsatisfactory</strong><br>
Needs Formal<br />
Suggestions for Improvement<br>
            (3)</td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>1. Decision making on accounts </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>2. Listening: Is a good listener to both the debtor and management </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>3. Time management </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>4. Negotiation: Is proficient in selling PIF and setting up payment plans with the debtor </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>5. Personal issues affecting production </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>6. Speaking: Has a good command of the English Language </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>7. Managing queue properly </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>8. Persistence: Does not take NO for an answer </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>9. Attendance/tardiness </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>10. Multi-tasking: Can effectively TYPE and TALK at the same time </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>11. Personal conversations within the office/Easily distracted </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>12. Typing: Can update the collection system files quickly and accurately </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>13. Asking for PIF on every call </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>14. Participation: Actively participates in collection meetings by asking questions </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>15. Payment plans and amounts established </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>16. Meeting Goals: Strives to attain management assigned goals </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>17. Outbound call volume per day </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>18. Team Player: Takes calls for others when they are on break or at Lunch </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>19. Uses Tools: Effectively uses Scripts/Talk-Offs/Tools </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>20. Talk off/Script/VAPP technique and usage </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>21. Speed in using Collection System (debtor screens and flow) </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>22. Following up on broken promises in a timely manner </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
                <tr>
            <td  width="360" wrap=wrap>23. Asking for auto debit on every call </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
            <td align="center" width="120">
                        </td>
        </tr>
              </table>
        <br>
  <table border=0 cellpadding="2" cellspacing="2" width="840" style="border:none">
        <tr>
          <td><strong>Meets Standards (1) -
           </strong>Supervisor Comments:<br>
           <span style='margin-left:20px'></span>          </td>
        </tr>
        <tr>
          <td><strong>Needs Improvement (2)  </strong>- Supervisor Comments:<br>
           <span style='margin-left:20px'></span>          </td>
        </tr>
        <tr>
          <td><strong>Unsatisfactory (3)</strong> - Supervisor Comments:<br>
           <span style='margin-left:20px'></span>          </td>
        </tr>
        <tr><td><strong>Overall Employee Evaluation Rating Summary:
            </strong><br>
            <span style="margin-left:20px">
                        </span>
            </td>
          </tr>
        </table>
        <br>
  <table border = 0 cellspacing=10 width="840">
        <tr>
            <td align="center" width = "50%" height="200" valign="bottom">
           <br><br><br><br><br>              <p>________________________________________<br>
              Jow Blow<br>Clerck<br>
            Date:08/14/2018</p></td>
            <td align="center" height="200" valign="bottom">
              <p><img src="http://internal.kingscredit.com/images/signature/Vicki_Callahan.png"></p>
              <p>_______________________________________<br>
          	Manager<br>VP Operations
<br>
            Date:08/14/2018</p></td>
          </tr>
        </table>
        <br />
  		<table border = 0 width="840" style="border:none">
        <tr>
            <td colspan = 2><div align="center"><em>Signature indicates employee has seen and reviewed the evaluation
              report and has been informed of his/her rights to comment, but does not necessarily indicate
              complete agreement with it.</em><br>
              <br>
          </div></td>
        </tr>
        <tr>
            <td colspan = 2 align="center">THIS DOCUMENT WILL BE PLACED IN YOUR PERSONNEL FILE. YOU HAVE FIVE
                (5) WORK DAYS FROM RECEIPT OF THIS DOCUMENT TO MAKE ANY SIGNED WRITTEN COMMENTS YOU WISH,
                WHICH WILL BE ATTACHED TO THE DOCUMENT AND PLACE IN YOUR PRIMARY PERSONNEL FILE.</td>
        </tr>
   </table>
</page>
‘’’

**Comment by spipu** [comment]
i have no pb on my side when testing your code.

did you try with the last version of html2pdf ?

and also, try to have a simplest html code ! on your last table, you have unused colspan + useless div and em + deprecated attributes (use css instead) + spaces between attribute and value + ...
