### ISSUE TITLE
unordered lists of div not rendering properly

### ISSUE THREAD

**Issue by libin-n-g** [spipu/html2pdf#366]
The following shows how a list is shown in pdf
![image](https://user-images.githubusercontent.com/24367198/44616955-dbfa7900-a877-11e8-93c3-02052f95782f.png)

But it should be looking as below. 
(the Same list is shown as below in HTML)

![image](https://user-images.githubusercontent.com/24367198/44616965-106e3500-a878-11e8-8a1c-f2592f4c7030.png)

```
      var filename = nid+".pdf";
      var opt = {
        margin:       .5,
        filename:     filename,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2 },
        jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
      };
      html2pdf(element,opt);
```
How do I solve this problem

**Comment by LittleBigFox** [comment]
Hi!
What version of html2pdf do you use? Can you give us your CSS et HTML?
Regards,
LBF
