### ISSUE TITLE
PHP 7 compatibility an composer

### ISSUE THREAD

**Issue by LaurentSEO** [spipu/html2pdf#368]
Hi,
I use for a long time html2pdf and I have migrated a website on a new server and html2pdf doesn't work now.
I thought it's perhaps the new server use PHP 7. So I wanted to try to install last version (I have version 4.03), but I see I must use Composer I don't know at all.

So, can you help me to :
- use last version without composer
- or find a version that works in PHP 7 and doesn't need Composer
- or guide me to begin composer quickly ? I must correct the service as soon as possible.
Thanks !
Laurent

**Comment by LittleBigFox** [comment]
Hi Laurent!
Html2Pdf needs Composer, you can't use it without.
But Composer is very simple to use! Look at this two links:
https://getcomposer.org/doc/00-intro.md
https://github.com/spipu/html2pdf/blob/master/doc/install.md
You'll find Composer very useful for many librairy, for updating yours dependancies in a safe way, for testing new librairy quickly without dirty your code, ...
If you need some help, i can help you in my skill range.
Regards,
LBF

**Comment by LaurentSEO** [comment]
Thank your very much !
It works.
Laurent
