### ISSUE TITLE
CPU 100% usage when creating a PDF file

### ISSUE THREAD

**Issue by jhonnymakis** [spipu/html2pdf#370]
I have a script that create a PDF file (about 38 pages, with texts and images) 15MB.
Since last week when this script is running the server use 98% of the CPU, do you have any ideal why and how can I fix this?

**Comment by jhonnymakis** [comment]
Did you make a change to your html, like change your images or anything else?
NO

But, after I found this issue, I tried to improve my images, but the problems continues.

Server (Digital Ocean)
12 vCPUs
48GB Memory / 960GB Disk SSD

Yesterday I changed the apache to PHP-FPM event and now this process use 98% CPU but the server continues running without crash.

**Comment by spipu** [comment]
duplicate from https://github.com/spipu/html2pdf/issues/230
