### ISSUE TITLE
Using images from a TWIG rendered template

### ISSUE THREAD

**Issue by SwordaDev** [spipu/html2pdf#373]
Hello !

I browsed through the other posts that mentioned bug/strange behaviour towards the use of image with this plugin.

`allow_url_fopen = On` inside my php.ini

On my template i have the following :

`<img src="{{ app.request.getSchemeAndHttpHost() ~ asset('/uploads/logo/' ~ myLogoNameFromDataBase) }}" />` which is generating an absolute URL.

Yet when i run the script i end up with this

`Unable to get the size of the image [http://my_domain.develop/uploads/logo/my_logo.jpg]`

But when i copy/paste the given faulty URL, it leads me correctly to the logo ?

How are we supposed to use HTML2PDF with image that comes from a database it needs an absolute URL and even that is not working.

**Comment by spipu** [comment]
try to use path instead of url
`<img src="{{ app_main_path ~ asset('/uploads/logo/' ~ myLogoNameFromDataBase) }}" />`
