### ISSUE TITLE
Content flowing from one page to the next breaks pdf generation

### ISSUE THREAD

**Issue by schmidtl4** [spipu/html2pdf#375]
Hello,
In testing the code below, there is a phenomenon where adding one additional div, breaks the pdf generation.  Run the code with Hello World! 1 through Hello World! 5 and all is good.  Running the identical code, but adding one more identical `<div>` (for Hello World 6), breaks the app. 

Alternatively, after clearing browser cache, a sixth block will work, but creates 3 extra pages.  In this case a seventh identical `<div>` for Hello World! 7 will break the pdf generation.
 Code follows:

	<?php
        session_start();
        use Spipu\Html2Pdf\Html2Pdf;
	use Spipu\Html2Pdf\Exception\Html2PdfException;
	use Spipu\Html2Pdf\Exception\ExceptionFormatter;
	
		$header = '

			<div class="row">
				
				<div class="col-sm-12">
					
						<h2 style="margin-bottom:25px;">Document repeating Heading</h2>
					
					</div>
				</div>			
		';
		
		$footer = "document important repeating footer";
		
		$dt = new DateTime();
		
		//NOTE:  code works fine without div containing Hello World! 6
		//Hello World! 6 block causes generation to fail
		
		$body = '
		<div class="container curriculum" style="font-size:20px;>
			<h3>first content</h3>
			<div style="margin-top: 90px;">
				<h3>Hello World! 1</h3>
			</div>
			<div style="margin-top: 90px;">
				<h3>Hello World! 2</h3>
			</div>
			<div style="margin-top: 90px;">
				<h3>Hello World! 3</h3>
			</div>
			<div style="margin-top: 90px;">
				<h3>Hello World! 4</h3>
			</div>
			<div style="margin-top: 90px;">
				<h3>Hello World! 5</h3>
			</div>
			<div style="margin-top: 90px;">
				<h3>Hello World! 6</h3>
			</div>
		</div>';		
		
		$filepath = DB_ROOT.'/test_'.$dt->format('Ymd').'.pdf';	
		
		create_pdf($filepath,$header,$footer,$body);
		
		//CREATE_PDF
		function create_pdf($filepath,$header='',$footer='',$body)	{

			$pg_tM = 5;
			$pg_bM = 5;
			$pg_lM = 15;
			$pg_rM = 15;
			$fileDest = 'FI';
			$font = 'Times';
		
			$html = '				
				<page backtop="20mm" backbottom="25mm" backleft="0mm" backright="0mm" pageset="new" footer="page">
					<page_header>'.$header.'</page_header>
					<page_footer backtop="10mm" >'.$footer.'</page_footer>'.
					$body.'
				</page>';
				
			echo $html;
			
			try {
				
				$html2pdf = new Html2Pdf('P','LETTER','en',false, 'UTF-8', array($pg_lM,$pg_tM,$pg_rM,$pg_bM));
				$ver = $html2pdf->getVersion();				
				
			} catch (Html2PdfException $e) {
				$html2pdf->clean();
			    $formatter = new ExceptionFormatter($e);
			    echo $formatter->getHtmlMessage();				
				
			} 
			
			try {
				$html2pdf->writeHTML($html);
				if(empty($filepath)) {
					$html2pdf->output();
				} else {
					if(!empty($fileDest)) {
						$html2pdf->output($filepath,$fileDest);
					} else {
						$html2pdf->output($filepath);
					}
				}
			} catch (Html2pdfException $e) {
				$html2pdf->clean();
				$formatter = new ExceptionFormatter($e);
				echo $formatter->getHtmlMessage();
			}
			
		}		
    ?>

**Comment by spipu** [comment]
you must create html code for HTML2PDF, all your div are useless... add directly the margin on the H3 tags !

div can not be on more than 1 page
