### ISSUE TITLE
output shows only a blank page in production

### ISSUE THREAD

**Issue by jloguercio** [spipu/html2pdf#377]
Hi, i use html2pdf to render some html documents in my web application, on localhost do the work fine, but if i upload the script into a CPANEL host only shows a pdf blank page.

- No error outputs
- html content retrieve fine.

Here is the code :

$html2pdf = new Html2Pdf('P', 'A4');
$html2pdf->writeHTML($content);
$html2pdf->output();

**Comment by p-drolima** [comment]
Hi,

I am also getting issues but in my case related to images. no errors, text displays properly but images dont appear to render. only a blank space.

#380 > if you want to follow that as well

best,

Pedro

**Comment by spipu** [comment]
blank page => fatal error => look at you log on your server
