### ISSUE TITLE
Background different

### ISSUE THREAD

**Issue by Vincent54800** [spipu/html2pdf#379]
Bonjour

Comment peut-on obtenir un backimg  différent sur la première page (sachant que la longueur du document est inconnue) ?

Merci.

**Comment by spipu** [comment]
le plus simple, tu te fais une div en tout début de ta page, en "position absolute top 0 left 0" qui ne sera utilisé que pour mettre une image là ou tu veux.

**Comment by Vincent54800** [comment]
Merci. Effectivement, sauf que, bien entendu, rien n'est simple en ce bas monde :)
J'ai une autre background pour les pages suivantes (en clair, un courrier avec en page 1 un fond, en page 2 et +, un autre fond). 
A moins de savoir quand je dois replacer la div en 0,0, c'est a dire détecter le saut de page, mais malheureusement, cela non plus je ne sais pas le faire :)

Et puis histoire de corser le tout, je suis resté très fidèle à la version... 4.03 :) :)

Merci de m'avoir lu

**Comment by spipu** [comment]
tu peux 
 * faire un header qui en fait t'affichera ton fond d'écran pour les pages >= 2
 * dire que tu ne le veux pas sur la page 1 avec la propriété hideheader, 
 * utiliser une div en tout premier pour la page 1

mais tu ne pourra le faire que dans les dernières version d'html2pdf ... la V4 n'est plus supporté, désolé
