### ISSUE TITLE
Fatal error: Namespace declaration statement has to be the very first statement in the script

### ISSUE THREAD

**Issue by Manueltekux** [spipu/html2pdf#381]
Fatal error: Namespace declaration statement has to be the very first statement in the script in C:\AppServ\www\Prefectura\vendor\spipu\html2pdf\src\Parsing\Html.php on line 13

Hi how are you ?, I have a problem when I try to generate a pdf I get this error (Fatal error: Namespace declaration statement has to be the very first statement in the script in C:\AppServ\www\Prefectura\vendor\spipu\html2pdf\src\Parsing\Html.php on line 13), and I can not solve it.

**Comment by spipu** [comment]
hi
do you have the same file that this one ?

https://github.com/spipu/html2pdf/blob/master/src/Parsing/Html.php
