### ISSUE TITLE
$html2pdf->output($filepath, 'F') Not working

### ISSUE THREAD

**Issue by franciscocervantes** [spipu/html2pdf#382]
Im trying to create the PDF and save it in the Server, but it keeps showing the created PDF in the browser, and not creating the file on the PDF 

	$html2pdf = new HTML2PDF('P','A4','es');
	$html2pdf->WriteHTML($content);
	$file = $html2pdf->Output($url_temp.$document_title.'.pdf','F');

Please help!

**Comment by p-drolima** [comment]
Hi,

Can you check what version of TCPDF you have installed? perhaps unrelated but I was having other issue and reverted TCPDF version to 6.2.12 and worked then.

Also, make sure there is no permissions issue in write. Output second argument might be returning null and defaulting to browser

**Comment by franciscocervantes** [comment]
Hi, 


problem solved. I found that the version wasnt the right one. Now it is working. Thanks so much!

**Comment by AmitM13** [comment]
what version will work with this package io have TCPDF Version 6.2.26
