### ISSUE TITLE
TCPDF 6.2.12 => solved my issue and could solve yours

### ISSUE THREAD

**Issue by p-drolima** [spipu/html2pdf#383]
I was recently encontering issues with image rendering and someone advised me to downgrade the version of TDPDF to 6.2.12 (@boileau) - I just thought of making this suggestion to others that might be encountering similar problems and give that a try.

Hope this saves you time.

**Comment by spipu** [comment]
hi,
did you find the exact version of TCPDF that cause the pb ?

i see this on the last version 6.2.25 : 
https://github.com/tecnickcom/TCPDF/commit/a5135e2cf02f8c935b71e9e7d676f0f1d31b1b9d

**Comment by p-drolima** [comment]
yes, I tried 6.2.12 and worked for me. I havent test other versions but just know that one works at least for my use case

**Comment by p-drolima** [comment]
I did a pull request on it... if you like to merge

**Comment by spipu** [comment]
have you test with the 6.2.25 ? they fix the pb i think with the commit i give in my last message

**Comment by spipu** [comment]
(fixing the exact version of a dependency is a very bad practice)

**Comment by p-drolima** [comment]
I am aware of that, just more for your reference... had the feeling you would not want to merge it :)

**Comment by p-drolima** [comment]
I will try 6.2.25

**Comment by naitsirch** [comment]
Same problem here.
Image rendering worked fine with *TCPDF* 6.2.21. It stopped working with 6.2.22.

**Comment by naitsirch** [comment]
In my case even 6.2.25 does not work.

I am using inline images (data URLs) like this:

```html
<img src="data:image/png;base64,#######">
```

CC: @nicolaasuni

**Comment by LittleBigFox** [comment]
Hi!
I make the update this morning of tcpdf, all worked fine when i installed php-curl on my server, and restart apache... 
If it can help you...
Regards, 
LBF

**Comment by ThymonA** [comment]
@p-drolima Thank you, the downgrade of LCPDF is indeed the solution

**Comment by reimax** [comment]
I am using inline images 
data:image/jpeg;base64,#######

and in pdf this image not show. how fix this?

**Comment by LittleBigFox** [comment]
hi @reimax !

It's a TCPDF issue, force tcpdf version in composer a 6.2.12.

Regards,
LBF

**Comment by reimax** [comment]
**hi LittleBigFox**,
force to 6.2.17 and image show. 
Thank you

**Comment by Jaggle** [comment]
please publish a new release to support inline images, like @remix said.
