### ISSUE TITLE
Whatsapp baloon html

### ISSUE THREAD

**Issue by shinesoftware** [spipu/html2pdf#385]
Hi guys,

is there a way to create a simple Whatsapp page style like this by html code?

![image](https://user-images.githubusercontent.com/1553035/45946043-debfc980-bfef-11e8-82cc-0eb80dd95ab2.png)

I have created the pdf attached as idea...

[document.pdf](https://github.com/spipu/html2pdf/files/2410368/document.pdf)

thanks!

**Comment by spipu** [comment]
try to use the border-radius css properties

**Comment by shinesoftware** [comment]
already done but I need to create the triangle close the box.
[document (1).pdf](https://github.com/spipu/html2pdf/files/2410868/document.1.pdf)

**Comment by shinesoftware** [comment]
Up

**Comment by spipu** [comment]
Hi,
i test, and there was some errors on the css parser. I fix them on the master branch.
I provide also a example in the new `balloon` example.

all this will be in the next release

**Comment by spipu** [comment]
It is now available in th 5.2.1 release
