### ISSUE TITLE
HTML to PDF 

### ISSUE THREAD

**Issue by TonyElGreco** [spipu/html2pdf#386]
Hello Everybody,

I am new in this chatroom.
I was wondering if somebody could help me with my issue please:

As you can see in the printed image below (see link), The size of the different "td cells " of the table are not equal (I also added some "colspan" on the first line).

Do you know how could I modify and fix the width of those please? 

I tried to add a width in the css page but I have the error below showing off:

ERREUR nÂ°7
Fichier : C:\wamp\www\cuvesusgen_2.3.2_en_dev\sp_generator\html2pdf.class.php
Ligne : 5524
le contenu d'une balise TD ne rentre pas sur une seule page
(the content of td cell doesn't fit in one page...)
 
IMAGE BELOW:
![pic](https://user-images.githubusercontent.com/43614230/46150241-69146180-c26c-11e8-9c1c-a86c090e75be.png)

**Comment by TonyElGreco** [comment]
I am using a library of PHP

**Comment by spipu** [comment]
you mean the size of each table is not the same ? or the size of the cells in a same table ?

for the first pb, put a with on each table
