### ISSUE TITLE
Unable to Render Images - HTTP ERROR 500

### ISSUE THREAD

**Issue by awaistariq** [spipu/html2pdf#387]
Hi,
Unable to render Images in my production server. Things are working fine in dev / localhost.

composer.json:
`"spipu/html2pdf": "^5.0",`

I am providing image absolute path, but apache throws error 500 without any description.

My .htaccess is:

```
RewriteEngine on
RewriteCond $1 !^(index\.php|assets|xml|images|js|css|uploads|favicon.png|image.png)
RewriteCond %(REQUEST_FILENAME) !-f
RewriteCond %(REQUEST_FILENAME) !-d
RewriteRule ^(.*)$ ./index.php/$1 [L]

```

Image Tag Src is:

`/var/www/html/SiteFolder/assets/images/image.png`

What can be wrong?

I am using CodeIgniter as the framework.

**Comment by awaistariq** [comment]
Apparently, issue went once I changed image from PNG to JPEG. But I still can't figure what's wrong with PNG?

**Comment by LittleBigFox** [comment]
Hi! 
I'd the same problem, i had to install php-curl and restart apache... See your log if you can!
Regards,
LBF

**Comment by spipu** [comment]
exactly, look at if you have the good php extensons (curl, gd, ...)
