### ISSUE TITLE
html2pdf - 5.2 not showing images 

### ISSUE THREAD

**Issue by DanielZambranoC** [spipu/html2pdf#392]
I was using 5.1 until yesterday, I've updated my composer packages but suddenly images shown in my pdf, specifically the images inside p, I tested it going back to version 5.1 so I can see the images.

I will try to identify the problem to give more information, I wanted to give you this information.

**Comment by DanielZambranoC** [comment]
Here is the error, please take note of this 
https://github.com/tecnickcom/TCPDF/commit/a5135e2cf02f8c935b71e9e7d676f0f1d31b1b9d

**Comment by spipu** [comment]
yes, it is a TCPDF error, sorry about this :(

**Comment by spipu** [comment]
duplicate of https://github.com/spipu/html2pdf/issues/383
