### ISSUE TITLE
Problem with backimg

### ISSUE THREAD

**Issue by flesblue** [spipu/html2pdf#394]
Hi,
I have a problem with backimg into page tag.  The image size on the first page (only) is incorrect but it's correct on the other pages.
![example](https://user-images.githubusercontent.com/12549674/46973635-8a8f8e80-d05d-11e8-91d9-c701d18391da.jpg)
[test.txt](https://github.com/spipu/html2pdf/files/2480289/test.txt)

**Comment by spipu** [comment]
thanks for this report !
on the first page, HTML2PDF forget to take in account the orientation before caculate the width of the image :)

i will fix it

**Comment by spipu** [comment]
it is fixed on the master branch, and will be included in the next release
