### ISSUE TITLE
Tags are closed in a wrong order for [a]

### ISSUE THREAD

**Issue by zeekinio** [spipu/html2pdf#395]
hello i got this error when i try to start my pdf : 
`Html2Pdf Error [1]
Tags are closed in a wrong order for [a]
File: C:\wamp64\www\trombi\vendor\spipu\html2pdf\src\Parsing\Html.php
Line: 262
Invalid Tag: a
Html Line: 10`

My main page : 

http://textup.fr/292424UH

And my page for get my pdf : 

http://textup.fr/292425FF

Thx for your help

**Comment by LittleBigFox** [comment]
You have a problem with your code:
`<div class='top'><a href='#haut'><img src="./img/top.png">**</a></a>**</div>`

Regards,
LBF

**Comment by zeekinio** [comment]
Oh thx ! i don't see this ^^ 

"The html tag [nav] is not known by Html2Pdf. You can create it and push it on the Html2Pdf GitHub project." 

A solution for nav html ? :/

**Comment by LittleBigFox** [comment]
You may have to create the missing tag in \vendor\spipu\html2pdf\src\Tag\Html.
It's not very difficult, but [nav] is a block type, and i don't see block tags in this folder... I can't recommand you any tag for copy/paste...

**Comment by zeekinio** [comment]
Yeah i see, and no Header too :/ maybe spipu help me

**Comment by LittleBigFox** [comment]
You just have to add this in your Html2Pdf.php code:

```
   /**
     * tag : NAV
     * mode : OPEN
     *
     * @param  array $param
     * @return boolean
     */
    protected function _tag_open_NAV($param)
    {
        $this->_tag_open_DIV($param);
        // nothing to do here

        return true;
    }

    /**
     * tag : NAV
     * mode : CLOSE
     *
     * @param    array $param
     * @return boolean
     */
    protected function _tag_close_NAV($param)
    {
        $this->_tag_close_DIV($param);
        // nothing to do here

        return true;
    }

```

**Comment by zeekinio** [comment]
And now i have the problem for <script> ! Lol , is not possible to take just a div ?

**Comment by LittleBigFox** [comment]
Of course, if you make an include or a class with functions...
In this case, you just have to extract the body and parse it with Html2Pdf.

**Comment by zeekinio** [comment]
Yeah but i need to include the full page ? i can't include juste a div ... 

I don't know the fonction for select just a div in Html2Pdf

**Comment by LittleBigFox** [comment]
You can't, in Html2Pdf. You have to parse your input before, unfortunatly.

**Comment by LittleBigFox** [comment]
Not really in another page, if you use a class

```
class guestbook
{
  function __construct() {

  }

  function toHTML()
  {
     // Call you entire html page here
   
    // Begin html
    echo $this->htmlBody();
    // End html
  }

  function toPDF() {
     // call your page body here, write it to the PDF
  }

  function htmlBody()
  {
    // Return your html body
  }
}
```

**Comment by zeekinio** [comment]
And this not working ? 

`preg_match('`<body[^>]*>(.*)</body[^>]*>`isU', $page, $matches);
$body = $matches[1];`

**Comment by LittleBigFox** [comment]
Yes i think it could work :)

**Comment by zeekinio** [comment]
I choose this finally ^^
http://textup.fr/292449Zu

But i have a problem , my picture doesn't work :/

**Comment by zeekinio** [comment]
I get this erro : Unable to get the size of the image
