### ISSUE TITLE
 Unable to get the size of the image

### ISSUE THREAD

**Issue by zeekinio** [spipu/html2pdf#396]
Hello i have a problem with my code, picture doesn't work and i get this error : Unable to get the size of the image
My code here : http://textup.fr/292515m9

Thx for your help

**Comment by zeekinio** [comment]
I just revolve my probleme with this ! 
`  if(file_exists('./upload_img/img/'.$result['ID_EMP'].'.jpg'))
                  {
                      echo ' <img src="./upload_img/img/'.$result['ID_EMP'].'.jpg" alt="" style="width:100px;height:100px;">';
                  }else{
                    echo '<img src="./img/no-image.jpg" alt=""  style="width:100px;height:100px;"/>';
                  }`

**Comment by cakephp2** [comment]
If you use HTML2PDF 
there is a function:
protected function _drawImage($src, $subLi = false)
contain coment:
// WARNING : if URL, "allow_url_fopen" must turned to "on" in php.ini
In your CPANEL : 
[Set on "allow_url_fopen"](https://chemicloud.com/kb/article/how-to-enable-or-disable-allow_url_fopen-in-cpanel/)
