### ISSUE TITLE
Import Google Fonts

### ISSUE THREAD

**Issue by webdev2009** [spipu/html2pdf#398]
HI;
how can I use Google Fonts . Any method I use , generate error 👍 
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />

or 

@import url(https://fonts.googleapis.com/css?family=Open+Sans);

will appreciate help .
j

**Comment by spipu** [comment]
you can not directly, you must convert it...
https://github.com/spipu/html2pdf/blob/master/doc/font.md
