### ISSUE TITLE
Bullets not visible on Output to server 

### ISSUE THREAD

**Issue by wgstjf** [spipu/html2pdf#4]
I have a strange one for you :-)

My pdf is happily displaying bullets (both UL and OL) when I output straight to the browser or as a download. The problem is when I save the pdf to the browser they disappear....! Can anyone help? I just noticed this and the project has to go live tomorrow afternoon!

Thanks in advance,

Will

**Comment by georaldc** [comment]
What do you mean by "Save the PDF to the browser", and how is that different from "outputting straight to the browser"?

Bullets show up fine for me by the way.

**Comment by wgstjf** [comment]
My apologies, I meant to write 'save it to the server'... As opposed to viewing in browser or downloading. 

Thanks for your reply.

Will

**Comment by goulvench** [comment]
I have noticed that PDF rendering can be different when using browser plugin (Firefox using pdf.js for example) versus Adobe Acrobat. Try saving the PDF received in your browser, then getting the one you've generated on the server (using FTP for instance) and comparing both files using the same viewing software.  

By the way, go-live on Fridays is a big no-no. You're waving at Murphy when you agree to that :-)

**Comment by georaldc** [comment]
Going live on a friday makes things exciting though XD

But I agree. We usually focus on bug fixing and support before the week ends

**Comment by wgstjf** [comment]
Gentlemen,

I agree that a Friday go-live is never a good plan.  In reality it was client sign-off rather than official go-live but it still leaves me with this problem.

Downloading the pdf then saving it to the server (via FTP) is not a possible solution as the pdf is being auto-generated on submission of a form and then attached to the user's auto-generated confirmation email.

I have now resolved the problem, with a bit of a hack, by replacing the ul bullets with background images (ordered lists work fine for some reason).  It is a solution but not the best...would be great to know a real solution though... :-)

Cheers,

Will

**Comment by spipu** [comment]
can you product a light HTML example that has the pb ?
