### ISSUE TITLE
HtmlParsingException - The HTML tag [<foo  bar baz>] provided is invalid

### ISSUE THREAD

**Issue by ctu-lshtm** [spipu/html2pdf#401]
Hi Spipu

Thanks for this great plugin!  It's very useful for us!

We've had an issue with people entering text that look like HTML tags, which then causes problems when converting to PDF:

> 2018-10-25 15:46:43 Error: [Spipu\Html2Pdf\Exception\HtmlParsingException] The HTML tag [<foo bar >] provided is invalid

Is it possible not to crash in this case and just show the < foo bar baz > as that literally in the PDF?

If it's not a valid tag then just output it as normal text?

**Comment by spipu** [comment]
If you want to display a tag, escape it !

**Comment by ctu-lshtm** [comment]
You mean like this:

> This is some &lt;b&gt;bold&lt;/b&gt; text.

I think from a design point of view, it should also be handled your side as well (considering other plugins we use escape this sort of thing already).

**Comment by spipu** [comment]
if they contribute throw a wysiwyg, the < and > are automatically escaped.
If they contribute throw a textarea without wysiwyg, then they write html code => < and > char must not be used. &gt; and &lt; must be used
