### ISSUE TITLE
font-size is ignored

### ISSUE THREAD

**Issue by multicore-association** [spipu/html2pdf#404]
I added 
<style>
body {font-size: 14px;}
p {font-size: 14px;}
</style>
to my html file but it ignores it.
How do I change font-size?

**Comment by spipu** [comment]
Normally it works. Look at example.

Be carefull, body tag does not really exist on html2pdf, look at the page tag documentation

**Comment by DubbleClick** [comment]
Since the body tag doesn't exist, you can do:

`<style>
* {
    font-size: 14pt;
}

p {
    font-size: 10pt;
}`

and override it whereever you want, such as above in the <p> tag.
