### ISSUE TITLE
message erreur  maj php7

### ISSUE THREAD

**Issue by biloubil83** [spipu/html2pdf#407]
Bonjour
Depuis la migration vers php7 j'ai ce message d'erreur :
Since migrating to php7 I have this error message::

_Parameter must be an array or an object that implements Countable in /customers/3/1/f/blabla/httpd.www/Facturier2/PDF/_class/locale.class.php on line 68_

code   
```
`            // load the file
              self::$_list = array();
               $handle = fopen($file, 'r');
                  while (!feof($handle)) {
                    $line = fgetcsv($handle);
**line 68=>**  if (count($line)!=2) continue;
                   self::$_list[trim($line[0])] = trim($line[1]);
        }`
```

merci de votre aide
Thank you for your help

**Comment by LittleBigFox** [comment]
Hi!
Je ne pense pas que vous ayez la dernière version de Html2pdf, ce bug a été résolu depuis un bout...
Essayez un composer update avec la nouvelle version?

Sinon ligne 68, ajoutez avant if(count...:
`if (!is_array($line)) continue;`

Regards,
LBF
