### ISSUE TITLE
Throwing 500 error

### ISSUE THREAD

**Issue by Aronasoft** [spipu/html2pdf#409]
Hello, 

I am trying to make 4 pages PDF but when I am passing second page it shows 500 error. I am not sure why. I also notices it only accepting HTML from page1 and only one line form page2. If I add more lines in page2 it through 500 error.  Please help me in fixing this problem. 

Here is my code 
`<?php  
ob_start();
session_start();
require __DIR__.'/htmltopdf/vendor/autoload.php';
use Spipu\Html2Pdf\Html2Pdf; 

$html2pdf = new Html2Pdf('P','A4','en');
$html2pdf->pdf->SetDisplayMode('fullpage'); 

$html2pdf->writeHTML('<page backtop="7mm" backbottom="7mm" backleft="10mm" backright="10mm" style="font-size: 14px">
<div class="pdf-one">
	<img class="probe-logo" src="images/areaprobe-logo.jpg" width="200"/>Powered by Ribbon Demographics
	<h2>Demand Analysis</h2>
	<ul>
		<li>1</li>
		<li>2</li>
		<li>3</li>
		<li>4</li>
		<li>5</li>
	</ul>
</div>
</page>');
$html2pdf->writeHTML('<page backtop="7mm" backbottom="7mm" backleft="10mm" backright="10mm" style="font-size: 14px">
<h4>SCOPE OF WORK</h4>
The following is an analysis performed to assess the extent of potential The following is an analysis performed to assess the extent of potential The following is an analysis performed to assess the extent of potential The following is an analysis performed to assess the extent of potential
</page>');
$html2pdf->output();
`

**Comment by LittleBigFox** [comment]
Hi!
Could you use the CODE tag in your post? We can't read anything here...
Regards,
LBF

**Comment by spipu** [comment]
error 500 => what is the exact error ? look at in you php error log file

**Comment by spipu** [comment]
no returns => close
