### ISSUE TITLE
Old Version 4.03 doesn't work anymore?

### ISSUE THREAD

**Issue by danypt77** [spipu/html2pdf#410]
Hello,

i had the old version of 4.03 installed on my webserver. Now it doesn't work anymore. Since 1 or 2 weeks, it shows me an error when i try to open a pdf trough a link created by me. 

It doesn't work anymore, i don't know why.  When loading the pdf i become an error message. Don't know why. I didn't change anything on codes or so... 

Thank you for your help

**Comment by LittleBigFox** [comment]
Hi!
Can you provide your error message please?
Regards,
LBF

**Comment by LittleBigFox** [comment]
You can:
- Try to get your error.log file for a more verbose message, 
- Use the debug mode of Html2Pdf, 
- Try to get the Html output first

**Comment by danypt77** [comment]
i activated on the file html2pdf.class.php this: 

$this->_debugActif = true;

and i get this on output: 

PAGE 1 Begin                1 542 120 088 612.9 ms1 542 120 088 612.9 ms         0.0 Ko         0.0 Ko
  PAGE 1 End                  1 542 120 088 617.4 ms      4.5 ms         0.0 Ko         0.0 Ko
  PAGE 2 Begin                1 542 120 088 617.4 ms      0.1 ms         0.0 Ko         0.0 Ko
  PAGE 2 End                  1 542 120 088 619.4 ms      2.0 ms         0.0 Ko         0.0 Ko
  PAGE 3 Begin                1 542 120 088 619.5 ms      0.1 ms         0.0 Ko         0.0 Ko
  PAGE 3 End                  1 542 120 088 621.4 ms      1.9 ms         0.0 Ko         0.0 Ko
  PAGE 4 Begin                1 542 120 088 621.4 ms      0.1 ms         0.0 Ko         0.0 Ko
  PAGE 4 End                  1 542 120 088 623.3 ms      1.9 ms         0.0 Ko         0.0 Ko
  PAGE 5 Begin                1 542 120 088 623.4 ms      0.0 ms         0.0 Ko         0.0 Ko
  PAGE 5 End                  1 542 120 088 625.3 ms      1.9 ms         0.0 Ko         0.0 Ko
Before output                 1 542 120 088 625.8 ms      0.5 ms         0.0 Ko         0.0 Ko

**Comment by danypt77** [comment]
_Try to get the Html output first_

i made that, everything in html seems to appear well. but a little bit crooked.

**Comment by danypt77** [comment]
_Try to get your error.log file for a more verbose message_

don't know how to do that :S

**Comment by danypt77** [comment]
what i get on w3 validator is this: 

Fatal Error: Cannot recover after last error. Any further errors will be ignored.

From line 388, column 30; to line 389, column 31

g_match('/<body/isU', $html))↩                $html = $this->getHtm


**Is there a way to get a new source file ? but the way i can upload it , instead of using command line with composer... ?**

**Comment by spipu** [comment]
Have look at the content of your pdf file to see if there is directly a php error ?

And also, look your php error file. If you don’t know how, it means that you never look at errors, that is very very bad...
