### ISSUE TITLE
Create new page if content overflows the first page

### ISSUE THREAD

**Issue by lorrandavid** [spipu/html2pdf#412]
What I want to achieve is: I have some **headers** and other **infos** in a div before a table, in this table there are a lot of data, sometimes it'll overflow to the next page. I want to whenever this happen (page overflows), create a new page with those **headers** and **infos** as I described before and make a new table with only those overflowed elements inside.

Is it possible? I don't really care if it's hacky

**Comment by DubbleClick** [comment]
Put the overflowing content in without <div> tags and use the <page backtop="" backleft="" backbottom backright>properties to get your content to the right position. That's what worked for me at least, even with lists and other constructs.

**Comment by lorrandavid** [comment]
I modified the way I was creating this file therefore I'm closing this issue.
