### ISSUE TITLE
Enclosed image in html not shown

### ISSUE THREAD

**Issue by NoxxieNl** [spipu/html2pdf#413]
Hiya,

I got html files where the image file is included inside the html like:
``<div class="par" style="vertical-align:baseline;font-family:inherit;font-size:0;font-weight:inherit;font-style:inherit;background-color:transparent;margin:0;padding:0;border:0;text-align:left;line-height:13.00pt;margin-top:0.00000pt;margin-bottom:0.00000pt;margin-left:0.00000pt;margin-right:0.00000pt;text-indent:0.00000pt;direction:ltr;"><span style="vertical-align:baseline;background-color:transparent;margin:0;padding:0;border:0;font-family:'Arial',sans-serif;font-size:0;font-weight:bold;font-style:normal;color:#000000;text-decoration:none;"><img style="font-family:inherit;font-size:0;font-weight:inherit;font-style:inherit;margin:0;vertical-align:text-bottom;background-color:transparent;padding:0.00000pt 0.00000pt 0.00000pt 0.00000pt;border:0.75pt solid transparent;" height="114" src="data:image/bmp;base64,Qk0+iAYAAAAAADYAAAAoAAAAIgIAAAUBAAABABgAAAAAAAiIBgBiBQAAEwMA
AAAAAAAAAAAA////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////...``

base64 encoded :-). Although it isnt showing in the output, am I missing something here?

**Comment by LittleBigFox** [comment]
Hi!
Data url have a bug in TCPDF, for this i've forced TCPDF version in Composer:
`
"require":{
    "spipu/html2pdf":"~5",
    "tecnickcom/tcpdf": "6.2.17"
}
`
Regarsd,
LBF

**Comment by Pattoow** [comment]
That did the trick thanks! 👍 

So happy works great!

**Comment by Vitexus** [comment]
Error is still occured with dev-master :(

`Fatal error: Uncaught Spipu\Html2Pdf\Exception\ImageException: Unable to get the size of the image [@u�Z�f�{�g���{�"T��B��� in /home/vitex/Projects/EASE/php-flexibee-reminder/vendor/spipu/html2pdf/src/Html2Pdf.php on line 1519`
