### ISSUE TITLE
need to set size of POS ticket

### ISSUE THREAD

**Issue by mscreation** [spipu/html2pdf#414]
My need : i want to generate a POS ticket (width :  8,92 cm => 89.20 mm ) and can't find the saize that i should use.

i used this relation to calculate the size but i didn't have the correct size
/**
 * Array of page formats
 * measures are calculated in this way: (inches * 72) or (millimeters * 72 / 25.4)
 * @public static
*/

can anyone help me please.

thanks

**Comment by spipu** [comment]
did you try the format attribute of the page tag ?

example: https://github.com/spipu/html2pdf/blob/master/examples/res/ticket.php
