### ISSUE TITLE
Problems with CSS hacks : linear-gradient & text-fill

### ISSUE THREAD

**Issue by nikonico** [spipu/html2pdf#415]
Hi,
I'm trying to use some CSS hacks for an electron project. Here's the result in electron :
![screenshot_20181121_123938](https://user-images.githubusercontent.com/32792402/48817964-bbd83a00-ed40-11e8-826e-5f360046b27f.png)
https://i.postimg.cc/xTDgsV0y/Screenshot-20181121-123938.png
Here's the CSS : 
```
/* For the s */
-webkit-text-fill-color: black;
-webkit-text-stroke-color: rgb(255, 255, 255);
-webkit-text-stroke-width: 1.5px;

/* For the oi */
-webkit-background-clip: text;
-webkit-text-fill-color: transparent;
background: -webkit-linear-gradient(top, rgb(147, 203, 193) 60%, white 40%);
```
But here's what I get in the PDF :
![screenshot_20181121_124755](https://user-images.githubusercontent.com/32792402/48817990-d9a59f00-ed40-11e8-9749-95424f8588fb.png)
https://i.postimg.cc/bvwjs2WJ/Screenshot-20181121-124755.png

The 's' is not displayed (I think the outline doesn't work) and for the oi, it's just not what I'm expecting. Do you have any ideas why and how I could fix this?

Thank you very much for your help.
Cheers,
Niko

**Comment by spipu** [comment]
CSS hack will not works.
sorry
