### ISSUE TITLE
Download pdf and continue execution of code

### ISSUE THREAD

**Issue by aveshnaik007** [spipu/html2pdf#416]
I have successfully install html2pdf. All the functionality is working fine. My requirement is to download the pdf and redirect to other page.

The file is getting downloaded but system does not redirect to other page.

$html2pdf->output("ok.pdf", "D");

**Comment by imadetouil** [comment]
$html2pdf->output("ok.pdf", "D");

**Comment by LittleBigFox** [comment]
Hi!
Try to use some javascript (document.location.href="..."), because when you generate the pdf, the buffer is sent and the response is stopped...
Regards,
LBF

**Comment by spipu** [comment]
you can not send a result, AND send a redirect header in the same page.

it is not a html2pdf issue...

try to use a JS hack before request the pdf.
