### ISSUE TITLE
Error when running under Linux/ubuntu/Xampp

### ISSUE THREAD

**Issue by CaptainChristian** [spipu/html2pdf#420]
Hello everybody
I have been using the **html2pdf library** since long without any significant problems as long as the script was either in development **under Windows/Wampp or online**
I wish to **switch to Linux/Ubuntu and now html2pdf fails** 
The message is: "**Warning: count(): Parameter must be an array or an object that implements Countable in /opt/lampp/htdocs/es...../html2pdf/class/locale.class.php on line 68**"
Is anyone able to give me any lead to get out of this problem?
Best regrads

**Comment by LittleBigFox** [comment]
Hi!

It's because you use php7.2 at least, this error was corrected in a recent version of html2pdf ;)

**Comment by CaptainChristian** [comment]
Thank you LittleBigFox: The library I have been using until now is outdated although it works fine on my scripts except when using Xampp

Then I have been trying to load a more recent version of html2pdf "https://www.html2pdf.fr/"

I have loaded "composer" from "github.com" as it seems to be required but I am totally unable to set the required dependancies (composer.json, composer.lock)

Reading again the guidelines in getcomposer.org gives me  headaches but leads me nowhere

Is there anybody familiar with this process who would help me resolve the problem in simple words?
Thanks

**Comment by LittleBigFox** [comment]
Hi!
You can just replace __DIR__ with your root path, __DIR__ mean in fact the directory where you file is. It's a magic constant.
For example, you could use 
`require '/www/vendor/autoload.php'`

Regards,
LBF

**Comment by CaptainChristian** [comment]
It's Captainchristian again!

My php script has been compiled fine in the message I sent you as you can see
I am sending it again without the php codings:

**"require_once'/opt/lampp/phpmyadmin/vendor/autoload.php';
$html2pdf = new Spipu/Html2Pdf/Html2Pdf('P','A4','en');
$html2pdf->writeHTML('<h1>HelloWorld</h1><p>This is my first test</p>');
$html2pdf->output();**"

**Comment by CaptainChristian** [comment]
Sorry! 
I try again: 
`require_once'/opt/lampp/phpmyadmin/vendor/autoload.php';
$html2pdf = new Spipu/Html2Pdf/Html2Pdf('P','A4','en');
$html2pdf->writeHTML('<h1>HelloWorld</h1><p>This is my first test</p>');
$html2pdf->output();`

**Comment by LittleBigFox** [comment]
Hi!
Try
`$html2pdf = new /Spipu/Html2Pdf/Html2Pdf('P','A4','en');`
because the namespace have to be at the root of php namespace.

If it doesn't work, try to read again the examples:
https://github.com/spipu/html2pdf/tree/master/examples

It may be a bad reference to your vendor folder.

Regards,
LBF

**Comment by CaptainChristian** [comment]
Hi!
Look at this:

**HelloWorld**
This is my first test

It was a matter of reference to the vendor folder, you were right LBF!
This is the finalized code:
`<?php
require_once '/home/christian/vendor/autoload.php';
use Spipu\Html2Pdf\Html2Pdf;
$html2pdf = new Html2Pdf();
$html2pdf->writeHTML('<h1>HelloWorld</h1><p>This is my first test</p>');
$html2pdf->output();
?>`
All the difficulty was to give the right path in the 'require_once' instruction
many thanks to you LBF
Captainchristian
