### ISSUE TITLE
float property doesn't work. Another option?

### ISSUE THREAD

**Issue by doberk** [spipu/html2pdf#422]
Hello, my document have an undefined number of boxes with data. The number of boxes depends of the number of elements I have to show in the document each time. I would like to create a div or a table for each element and show alongside each other. When there was not enough space in the document, next element will be showed in the next line. The most easy way is using float:left property. Another way is using display: inline-block. However, none of these properties work in html2pdf.

Any suggestion to get it working?

**Comment by spipu** [comment]
it will not works, sorry. Html2Pdf can not do responsive rendering.
Try to do the cut by yourself :(
