### ISSUE TITLE
HTML2Pdf not working for long html page

### ISSUE THREAD

**Issue by Dipranil** [spipu/html2pdf#426]
I am using HTML2pdf for a long html page, not sure why it is not generating the full html page into pdf. inline css are included in the html not external css. Only 1 and half page is converting into pdf not all the full html.

Html Dropbox link : https://www.dropbox.com/s/htmz1uctzpd8tgn/html%284%29.zip?dl=0

**Comment by spipu** [comment]
your html code is too complex.

you try complete a real html page directly. HTML2PDF has not been created for this. Look at the readme ;)
