### ISSUE TITLE
Insert SVG File

### ISSUE THREAD

**Issue by danganPM** [spipu/html2pdf#428]
Hello,
I already read the doc, but I want to insert a SVG file in HTML2PDF.
I can't insert LINE, PATH, G, .. only a real file from a directory.
Like this : <img src="directory/schema.svg" />

If it no possible, can you help me to read a SVG file to insert in DRAW ?

Thanks

**Comment by LittleBigFox** [comment]
Hi!

Hav you try the draw tag?
https://github.com/spipu/html2pdf/blob/master/doc/svg.md

Regards,
LBF

**Comment by spipu** [comment]
exactly, you must yuse the draw tag.

look at the https://github.com/spipu/html2pdf/blob/master/examples/res/svg.php example
