### ISSUE TITLE
La etiqueta <CENTER> todaví­a no existe.

### ISSUE THREAD

**Issue by ralbor85** [spipu/html2pdf#430]
Saludos, tengo un problema con la librería, al generar el pdf me muestra el siguiente error La etiqueta <CENTER> todavía no existe. Podrías ayudarme con este error. Gracias!

**Comment by LittleBigFox** [comment]
Hi!

You have to use CSS instead. Just put style="text-align:center;" on your element,

Regards,
LBF

**Comment by ralbor85** [comment]
Eso lo sé, el problema radica en que en mi base de datos ya existen esa etiqueta <center> almacenadas y al momento de generar el PDF, me muestra el error.

Hay alguna forma de corregir eso.

Gracias.

**Comment by jhonNumpaque** [comment]
https://lenguajehtml.com/p/html/semantica/etiquetas-html-obsoletas y basicamente explica que quieres hacer o que intentas hacer y como generas el codigo para que lo lea la libreria...

**Comment by ralbor85** [comment]
Para solucionar y evitar el error lo que hice fue reemplazar la etiqueta obsoleta con la función str_replace antes de mandarlo a generar el pdf, con eso quedo andando.
Gracias por sus respuestas!
