### ISSUE TITLE
Problem with serbian latin, letters Ć and Č shows like ? ?

### ISSUE THREAD

**Issue by fkojic** [spipu/html2pdf#436]
```
$html2pdf = new Html2Pdf('P', 'A4', 'cs', TRUE, 'UTF-8');
$html2pdf->writeHTML($compiled);
$html2pdf->output('document.pdf');
```
when i dump $compiled letters is okey, but in pdf return "?". Any solution?

**Comment by LittleBigFox** [comment]
Hi!

It's a TCPDF feature, try to have a look to:
https://stackoverflow.com/questions/10685964/why-cant-i-use-%C4%8D-%C4%87-%C4%91-charters-in-tcpdf-table

If i guess right, you have to use iconv...

Regards,
LBF

**Comment by fkojic** [comment]
Hi,
Thank you, i tried but without success. I solved the problem with the https://github.com/mpdf/mpdf.
