### ISSUE TITLE
Header hide except new pagegroup

### ISSUE THREAD

**Issue by steffiv** [spipu/html2pdf#438]
Hi,

When I merge 2 documents I can already reset the number with pagegroup="new" but I would like the page header to always be on the first page of the document (also with the 2nd).

Now I can only show the first page thanks to hideheader.

Can you help me with this?

**Comment by LittleBigFox** [comment]
Hi!
With pageset="new" ?
See: https://github.com/spipu/html2pdf/blob/master/examples/res/groups.php
Regards,
LBF

**Comment by steffiv** [comment]
Thank you very much!
It works great!
