### ISSUE TITLE
Fatal error: Uncaught Exception: TCPDF ERROR: Unable to create output file

### ISSUE THREAD

**Issue by CaptainChristian** [spipu/html2pdf#439]
Hi anyone who might solve my problem!

When trying the following command`    $pdf->Output('../uploads/'.$nompdf,'F');` instead of `$pdf->Output($nompdf);` (which by the way works fine), I get the following error message:
> Warning: fopen(): remote host file access not supported, file://../uploads/FichePesee-F-TEST-11.pdf in /opt/lampp/htdocs/PESER_CENTRER/dossier/vendor/tecnickcom/tcpdf/include/tcpdf_static.php on line 1821

> Warning: fopen(file://../uploads/FichePesee-F-TEST-11.pdf): failed to open stream: no suitable wrapper could be found in /opt/lampp/htdocs/PESER_CENTRER/dossier/vendor/tecnickcom/tcpdf/include/tcpdf_static.php on line 1821

> Fatal error: Uncaught Exception: TCPDF ERROR: Unable to create output file: ../uploads/FichePesee-F-TEST-11.pdf in /opt/lampp/htdocs/PESER_CENTRER/dossier/vendor/tecnickcom/tcpdf/tcpdf.php:2926 Stack trace: #0 /opt/lampp/htdocs/PESER_CENTRER/dossier/vendor/tecnickcom/tcpdf/tcpdf.php(7676): TCPDF->Error('Unable to creat...') #1 /opt/lampp/htdocs/PESER_CENTRER/dossier/vendor/spipu/html2pdf/src/Html2Pdf.php(575): TCPDF->Output('../uploads/Fich...', 'F') #2 /opt/lampp/htdocs/PESER_CENTRER/historique_maintenance/pdfFichePeseePlanMotoTurbo.php(380): Spipu\Html2Pdf\Html2Pdf->output('../uploads/Fich...', 'F') #3 {main} thrown in /opt/lampp/htdocs/PESER_CENTRER/dossier/vendor/tecnickcom/tcpdf/tcpdf.php on line 2926

Note that the file name I wish to upload is a variable ($nompdf) ...
If somebody might see what the problem is, please let me know
Kind regards and happy new year!
Captainchristian

**Comment by LittleBigFox** [comment]
Hi Captain!

Are you sure you have the writing right on this folder? 

Regards,
LBF

**Comment by CaptainChristian** [comment]
Hi LBF,
I have switched the chmod of the folder to be uploaded (../uploads) to 777 along with the chmod of my pdf2html script
In addition as I suspected that the name of the file to be uploaded might be a problem, I changed it into 'FichePesee_F_CGOB_23'  instead of 'FichePesee-F-CGOB-23'
Now this is the Error message I get:

> Fatal error: Uncaught Exception: TCPDF ERROR: Unable to create output file: ../uploads/FichePesee_F_CGOB_23.pdf in /homepages/11/d600469567/htdocs/pesercentrerfr/dossier/vendor/tecnickcom/tcpdf/tcpdf.php:2926 Stack trace: #0 /homepages/11/d600469567/htdocs/pesercentrerfr/dossier/vendor/tecnickcom/tcpdf/tcpdf.php(7676): TCPDF->Error('Unable to creat...') #1 /homepages/11/d600469567/htdocs/pesercentrerfr/dossier/vendor/spipu/html2pdf/src/Html2Pdf.php(575): TCPDF->Output('../uploads/Fich...', 'F') #2 /homepages/11/d600469567/htdocs/pesercentrerfr/historique_maintenance/pdfFichePeseePlanMotoTurbo.php(388): Spipu\Html2Pdf\Html2Pdf->output('../uploads/Fich...', 'F') #3 {main} thrown in /homepages/11/d600469567/htdocs/pesercentrerfr/dossier/vendor/tecnickcom/tcpdf/tcpdf.php on line 2926

Regards
Captainchristian

**Comment by ConstantBrum** [comment]
I've used this solution by Atul Baraiya on stackoverflow https://stackoverflow.com/a/32610232

He has found that the function fopenLocal has a if statement that will use file:// and that doesn't work for some people. I use windows so maybe this is only a windows problem.

See edited function below from the tcpdf_status.php file:

`	public static function fopenLocal($filename, $mode) {
		// if (strpos($filename, '://') === false) {
		// 	$filename = 'file://'.$filename;
		// } elseif (stream_is_local($filename) !== true) {
		// 	return false;
		// }
		return fopen($filename, $mode);
	}`
	
You need to comment out the whole if else statement and it will work as expected.
