### ISSUE TITLE
Turkish Character Problem

### ISSUE THREAD

**Issue by gunaysirbudak** [spipu/html2pdf#440]
Hi,
I'm converting pdf from php file with html code from sql.
We use "ş ğ ı" character the question mark (?)  appears for the characters.

If I write these characters with php echo before printing the data in sql, these characters appear.

html2pdf export code
`ob_start();                
                        echo 'Ş Ğ Ü Ö Ç İ
                        <br>
                        ş ğ ü ö ç ı';
                        echo $proposal_template_detail->header;

                        echo $proposal_template_detail->entry_text;

                        echo $proposal_template_detail->note;

                        echo $proposal_template_detail->footer;

                        $content = ob_get_clean();
                        
                        $html2pdf = new Html2Pdf('P', 'A4', 'en', true, 'UTF-8', array(0, 0, 0, 0));
                        
                        $html2pdf->pdf->SetDisplayMode('fullpage');
                        $html2pdf->pdf->SetFont('dejavusans');
                        
                        $html2pdf->writeHTML($content);
                        ob_end_clean();               
                        
                        $html2pdf->output('test.pdf', 'D');`

example sql html code:
<p>Merhaba&nbsp;{PERSON_FULLNAME},</p>

<p>Talebinize istinaden teklifimiz aşağıdadır.</p>
Ş Ğ Ü Ö Ç İ
<br>
ş ğ ü ö ç ı
<p>&#350;</p> -->Ş

**Comment by LittleBigFox** [comment]
Hi!

Try to use unicode font, like 
$pdf->SetFont('freesans');
Many language aren't supported by all fonts...

Regards,
LBF
