### ISSUE TITLE
Can't resolve 'child_process' in node_modules\html2pdf

### ISSUE THREAD

**Issue by fredmbarrett** [spipu/html2pdf#443]
I'm running a Vue.js app, and have installed html2pdf using `node i html2pdf --save`.
On my vue component, I've imported the file using `import html2pdf from 'html2pdf'`.
When I run webpack, I get the following error:
ERROR in ./node_modules/html2pdf/html2pdf.node.js
Module not found: Error: Can't resolve 'child_process' in 'D:\....\node_modules\html2pdf'
 @ ./node_modules/html2pdf/html2pdf.node.js 5:16-40

Is this a known error? I've installed html2pdf v0.0.11.
Thanks!

**Comment by spipu** [comment]
Not the good project

Here, it is a php project :p

**Comment by vykhy** [comment]
How did you fix this?

**Comment by spipu** [comment]
Not the good project

Here, it is a php project :p
