### ISSUE TITLE
Error with NPM install

### ISSUE THREAD

**Issue by oselly** [spipu/html2pdf#473]
Hello,

I'm having a bit of an issue with the npm install (previously has worked fine) but when i'm trying to run the npm install html2pdf.js command it's hanging on 
"fetchMetadata: sill resolveWithNewModule base64-arraybuffer@0.1.5 checking installable status" and not resolving itself. 

I can install other npm packages without issue, (my proxy is configured) and I can install the base64-arraybuffer via npm without issue as well. Is there something going on behind the scenes or is it just my setup somehow?

**Comment by LittleBigFox** [comment]
Hi!

That's not the same Html2pdf, this repository is about php html2pdf.

Regards,
LBF

**Comment by oselly** [comment]
Hello, Thanks typically noticed as soon as i opened the issue!
