### ISSUE TITLE
setCellPaddings and setCellMargin methods does not exists in MyPdf class

### ISSUE THREAD

**Issue by marcomag89** [spipu/html2pdf#481]
Hi, this methods does not exists in MyPdf.php.

https://github.com/spipu/html2pdf/blob/83c9bd942e8520681808b70584e01d17157335ba/src/MyPdf.php#L64

https://github.com/spipu/html2pdf/blob/83c9bd942e8520681808b70584e01d17157335ba/src/MyPdf.php#L65

**Comment by LittleBigFox** [comment]
Hi!

In fact, this methods exists in tcpdf.php.

Regards,
LBF

**Comment by marcomag89** [comment]
So sorry, my application was included an old/wrong version of tcpdf, and this methods does not exists at runtime.

Ty!
