### ISSUE TITLE
does utf-8 support

### ISSUE THREAD

**Issue by Shreeshrii** [spipu/html2pdf#5]
unicode fonts with devanagari script for Hindi language?

**Comment by spipu** [comment]
Normally it will work, have you try the UTF8 example ?

**Comment by Shreeshrii** [comment]
I looked at http://demo.html2pdf.fr/examples/pdf/utf8.pdf
It does not have a hindi example.

Please add the following for a test ..

यूनिकोड क्या है?
यूनिकोड प्रत्येक अक्षर के लिए एक विशेष नम्बर प्रदान करता है,
चाहे कोई भी प्लैटफॉर्म हो,
चाहे कोई भी प्रोग्राम हो,
चाहे कोई भी भाषा हो।

(What is Unicode? Translation from http://unicode.org/standard/translations/hindi.html)
