### ISSUE TITLE
Is there any way to change the Creator of PDF generation? (or is it allowed)

### ISSUE THREAD

**Issue by koyanyaroo** [spipu/html2pdf#500]
Hi there, 

I've been using html2pdf version 5.2 in laravel 5.8 to generating PDF, and trying to set my own creator name on the PDF.

Is that any way to change it via Html2Pdf class (without modifying the vendor)? or am I allowed to do that?

**Comment by LittleBigFox** [comment]
Hi!

Yes you can:
`$objPDF->pdf->SetCreator("Creator");
$objPDF->pdf->SetAuthor("Author");
$objPDF->pdf->SetTitle("Title");
$objPDF->pdf->SetSubject("Subject");`

Regards,
LBF

**Comment by koyanyaroo** [comment]
Thanks @LittleBigFox  that what I need.
