### ISSUE TITLE
Header and the Footer ONLY on the First Page?

### ISSUE THREAD

**Issue by reinhardjung** [spipu/html2pdf#522]
Hi @ll

Does anybody know how to just use the Header and the Footer ONLY on the First Page?

So the Opposite of the page hideHeader="" :-(

AND/But the Page Numbers on every Page.

Thanx a lot 4 any help!

**Comment by reinhardjung** [comment]
I changed something about the Page, but then (somehow logical) the first page will be empty (with not Invoice-Positions) :-(

[rechnungs_nr.pdf](https://github.com/spipu/html2pdf/files/3942774/rechnungs_nr.pdf)

**Comment by marbetschar** [comment]
@spipu trying to accomplish a similar thing: Two different layouts, one for the first page and another one for all subsequent pages. Unfortunately I don't know how much content I have beforehand - so I can't say whether the content needs more than one page or not.

Tried to get this done using one page layout containing a footer, which hides parts with css - depending on the page number `[[page_cu]]`: The css class names contain `[[page_cu]]`, enabling me to distinguish between first or subsequent pages. Unfortunately this does not seem to work. The `[[page_cu]]` dependent css rules have no effect at all (code below).

What's the recommended approach here?

```
<style type="text/css">
<!--
.footer-primary { position:absolute; left:-1000px; }
.footer-primary.footer-primary-1 { position:static; left:auto; }
.footer-secondary.footer-secondary-1 { position:absolute; left:-1000px; }
-->
</style>
<page backtop="30mm" backbottom="25mm" backleft="0mm">
<page_footer>
  <table border="1" style="width: 100%;" class="footer-primary footer-primary-[[page_cu]]">
  <tr>
  <td style="width: 100%; text-align: center;">
    <img style="width:400px;" src="'.$myFileFooter.'"/>
  </td>
  </tr>
  </table>
<table border="1" style="width: 100%;" class="footer-secondary footer-secondary-[[page_cu]]">
      <tr>
          <td style="width: 100%; text-align: right">
              Page <strong>[[page_cu]]</strong> of <strong>[[page_nb]]</strong>
          </td>
      </tr>
  </table>
</page_footer>
```

**Comment by marbetschar** [comment]
@spipu added pull request with needed change to fix footer styling for first/subsequent pages. Any chance this can be merged soon with a new release? Would be awesome!
