### ISSUE TITLE
Invalid HTML code, tags are not closed in the right order.

### ISSUE THREAD

**Issue by danieltan007** [spipu/html2pdf#527]
hello guys,
when i want to create a report i got error like this:

![error html2pdf](https://user-images.githubusercontent.com/59051848/71169784-58df0c80-228c-11ea-9ad7-d10f5285f799.jpg)

any help will be appreciated

**Comment by danieltan007** [comment]
here is what i got from the parsinghtml.class.pgp
![image](https://user-images.githubusercontent.com/59051848/71226215-b7000400-230d-11ea-8789-bbe611c24c77.png)

**Comment by Mr-TOA** [comment]
what is your code ?

**Comment by spipu** [comment]
if you use the <page> tag, does not use the native <html>, <head>, and <body> tags. Look at examples
