### ISSUE TITLE
Fatal error: Uncaught <span style="color: #AA0000; font-weight: bold;"> ERREUR n°5</span><br> file: C:\wamp64\www\missions_msas\etat_pdf\vendor\spipu\html2pdf\_class\parsingHtml.class.php<br> Ligne : 222<br> <br> ###### thrown in C:\wamp64\www\missions_msas\etat_pdf\vendor\spipu\html2pdf\_class\parsingHtml.class.php on line 222

### ISSUE THREAD

**Issue by madinaserigne** [spipu/html2pdf#529]
I have this error.
Here is my php html file
`<?php
 $mission_agent_id= $_POST['mission_agent_id'];
	include(dirname(__FILE__).'/../functions.php');
$bdd_mission_msas=connect();
$reponse_agent_missions_page = $bdd_mission_msas->query('SELECT agt.prenom,agt.nom,agt.fonction,sitf.siuationfamille,grd.nom_grade,
                                                        miss.lieu,miss.motif,miss.depart_mission,miss.arrivee_mission FROM  missions miss,agent agt,
														situation_famille sitf,grade grd,mission_agents missagt where miss.mission_id='.$mission_agent_id.'
														and missagt.mission_id=miss.mission_id and missagt.agent_id=agt.agent_id and agt.grade_id=grd.grade_id and 
														   agt.sitfamille_id=sitf.sitfamille_id;');
					
		while ($donnees_mission_agents_page = $reponse_agent_missions_page->fetch())
{
	    //$date_mission_fiche=date("d/m/Y", strtotime($donnees_mission_fiche ['depart_mission']));
		$prenom_agent=$donnees_mission_agents_page ['prenom'];
		$nom_agent=$donnees_mission_agents_page ['nom'];
		$fonction_agent=$donnees_mission_agents_page ['fonction'];
		$sitfamille_agent=$donnees_mission_agents_page ['siuationfamille'];
		$grade_agent=$donnees_mission_agents_page ['nom_grade'];
		$lieu_agent=$donnees_mission_agents_page ['lieu'];
		$motif_agent=$donnees_mission_agents_page ['motif'];
		$depart_mission_agent=$donnees_mission_agents_page ['depart_mission'];
		$retour_mission_agent=$donnees_mission_agents_page ['arrivee_mission'];
	     
 ?>
<page backtop="25mm" backbottom="10mm>
<page_header>

		<div align="left" ><?php echo date('d/m/Y');?></div>
            
			 <div align="right" >page [[page_cu]]/[[page_nb]]</div>

				
 </page_header>
 
	
	<h3>ORDRE DE MISSION</h3>
	<h3>Monsieur  <?php echo $prenom_agent ;?>  <?php echo $nom_agent ;?></h3>
	 <h3><?php echo $grade_agent ;?>  <?php echo $fonction_agent ;?></h3>
	<h3>Motif de la mission : <?php echo $motif_agent ;?></h3>
	<h3>Date de départ : <?php echo $depart_mission_agent ;?></h3>
	<h3>Date de retour :  <?php echo $retour_mission_agent ;?></h3>
	<h3>Imputation budgétaire des frais de transport :.....................</h3>
	<h3>Chapitre............................Article ..................................</h3>

 <?php

 }
 
$reponse_agent_missions_page->closeCursor();
  ?>
 </page>
  

`
Help please ?

**Comment by spipu** [comment]
our html  is invalid, you must fix it
