### ISSUE TITLE
Html2Pdf@_drawRectangle throws "Trying to access array offset on value of type null error" on php7.4

### ISSUE THREAD

**Issue by eric-reichenbach** [spipu/html2pdf#530]
## Specs
- Version: v5.2.1
- PHP: 7.4.1

## Bug
In php 7.4 you can't access array indexes on non array

https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.non-array-access

## How to repro
if the radiuses in the Html2Pdf@_drawRectangle are not set, it will crash.

I've forked the project and I fixed the issue. I'll submit a pull request ASAP

**Comment by EricReichenbach** [comment]
I've submitted a pull request for the bug #531

**Comment by hai05** [comment]
To fix it, change line 1756 to 1767 in the file spipu\html2pdf\src\Html2Pdf.php

if ($inTL == NULL || $inTL[0]<=0 || $inTL[1]<=0) {
            $inTL = NULL;
        }
        if ($inTR == NULL || $inTR[0]<=0 || $inTR[1]<=0) {
            $inTR = null;
        }
        if ($inBR == NULL || $inBR[0]<=0 || $inBR[1]<=0) {
            $inBR = null;
        }
        if ($inBL == NULL || $inBL[0]<=0 || $inBL[1]<=0) {
            $inBL = null;
        }

**Comment by spipu** [comment]
fixed on the master branch

**Comment by florianproxi** [comment]
Hi @spipu this is not fix the problem. I already have to replace with the trick of @hai05

**Comment by borekid** [comment]
thx u sOo much @hai05

**Comment by crazy-logic** [comment]
> To fix it, change line 1756 to 1767 in the file spipu\html2pdf\src\Html2Pdf.php
> 
> if ($inTL == NULL || $inTL[0]<=0 || $inTL[1]<=0) { $inTL = NULL; } if ($inTR == NULL || $inTR[0]<=0 || $inTR[1]<=0) { $inTR = null; } if ($inBR == NULL || $inBR[0]<=0 || $inBR[1]<=0) { $inBR = null; } if ($inBL == NULL || $inBL[0]<=0 || $inBL[1]<=0) { $inBL = null; }

I also ran into this and this fix solved it.

**Comment by snchezjuarez** [comment]
para mi también funciono ademas en tcpdf.php agrega el siguiente condición

if(isset($this->footer_font) && !empty($this->footer_font)){
     $this->SetFont($this->footer_font[0], $this->footer_font[1], $this->footer_font[2]);
}  

if ($inTL == NULL || $inTL[0]<=0 || $inTL[1]<=0) { $inTL = NULL; } if ($inTR == NULL || $inTR[0]<=0 || $inTR[1]<=0) { $inTR = null; } if ($inBR == NULL || $inBR[0]<=0 || $inBR[1]<=0) { $inBR = null; } if ($inBL == NULL || $inBL[0]<=0 || $inBL[1]<=0) { $inBL = null; }
