### ISSUE TITLE
error php 7.4

### ISSUE THREAD

**Issue by edgrod01** [spipu/html2pdf#542]
Hello!

I get a problem, when  install xampp with php 7.4, is deprecated the use of arrays, and i see that this tool is not apdate. 

Somebody knows, or can help me

Thanks

**Comment by LittleBigFox** [comment]
Hi!

I use the latest html2pdf version with php7.4, there no errors...

Any more information? Version of html2pdf maybe?

**Comment by edgrod01** [comment]
Thanks for respond, what version html2pdf that you use? . 

My version is 5.2.1 from 2018-10-26

**Comment by LittleBigFox** [comment]
Yes same, and don't have any error...

Have you a line maybe?

**Comment by coffeemedia** [comment]
@edgrod01 @LittleBigFox 
Can repoduce at least one usecase of this error, running v5.2.1 with PHP 7.4.3

```
Trying to access array offset on value of type null in .../vendor/spipu/html2pdf/src/Html2Pdf.php on line 1756
Call Stack
#	Time	Memory	Function	Location
1	0.0030	362904	{main}( )	.../invoice.php:0
2	0.4700	4642600	Spipu\Html2Pdf\Html2Pdf->writeHTML( )	.../invoice.php:43
3	0.4960	4827016	Spipu\Html2Pdf\Html2Pdf->_makeHTMLcode( )	.../Html2Pdf.php:595
4	0.6016	5179888	Spipu\Html2Pdf\Html2Pdf->_executeAction( )	.../Html2Pdf.php:1407
5	0.6016	5179960	Spipu\Html2Pdf\Html2Pdf->_tag_open_TABLE( )	.../Html2Pdf.php:1439
6	0.6019	5184592	Spipu\Html2Pdf\Html2Pdf->_drawRectangle( )	.../Html2Pdf.php:4997
```

**Comment by coffeemedia** [comment]
Just opened up a PR for my usecase: https://github.com/spipu/html2pdf/pull/551

**Comment by spipu** [comment]
merged :) you can use the master branch. i will release a new version soon
