### ISSUE TITLE
How can i use html2pdf with crontab ?

### ISSUE THREAD

**Issue by swfm** [spipu/html2pdf#546]
I have to create a daily crontab to send a pdf list to an email address.
The script works fine by calling from a browser, but not in a crontab
I know that is a path problem but anything works (relative path, full url).
Can you help me ? Thank you

```
<?php
    $url= ?
    include("$url/html2pdf/html2pdf.class.php");
    $html2pdf = new HTML2PDF('P','A4','fr');
    $html2pdf->WriteHTML($content);
    $html2pdf->Output('$url/pdf/list.pdf',F);
?>
```

**Comment by spipu** [comment]
you can do all what you want, like any php program, but it is not the purpose of html2pdf to manage it
