### ISSUE TITLE
Using <page></page> generates one blank page.

### ISSUE THREAD

**Issue by tgbv** [spipu/html2pdf#548]
Hello. I have the following HTML structure:
```
<!DOCTYPE html>
<html>
<head>
	<style> ... </style>
</head>
<body>
	<page> page 1 </page>
	<page> page 2 </page>
</body>
</html>
```

When run the following procedures, I get a PDF with 3 pages, first one being completely blank:
```
$H2P = new Html2Pdf();
$H2P->writeHTML( $html );
return $H2P->output(__DIR__ .'/statistics.pdf', 'F');
``` 

How can I solve this issue? 🤔 
I'm using the latest version installed via composer.

**Comment by zangetsu182** [comment]
<**page**> they are precisely pages, I would recommend that you make the pages you require and treat them as normal "html" pages, using <div> to segment your sections

**Comment by spipu** [comment]
look at example: do not use the <html>, <head>, <body> tags when you use the <page> tag

**Comment by tgbv** [comment]
What are , , tags?  I don't understand

**Comment by spipu** [comment]
i edit my last comment, the tags was hidden :(
