### ISSUE TITLE
Composer deprecation notices

### ISSUE THREAD

**Issue by adrienfr** [spipu/html2pdf#555]
Hi,

Since composer 1.10 release ([here](https://github.com/composer/composer/releases/tag/1.10.0)), I have the following deprecation notices:

> Deprecation Notice: Class Spipu\Html2Pdf\Tests\Output\FileNameOkTest located in ./vendor/spipu/html2pdf/src/Tests/Output/FileNameTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
> Deprecation Notice: Class Spipu\Html2Pdf\Tests\Parsing\BackgroundOkTest located in ./vendor/spipu/html2pdf/src/Tests/Image/BackgroundOkTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
> Deprecation Notice: Class Spipu\Html2Pdf\Tests\Parsing\BackgroundErrorTest located in ./vendor/spipu/html2pdf/src/Tests/Image/BackgroundErrorTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
> Deprecation Notice: Class Spipu\Html2Pdf\Tests\Parsing\SrcOkTest located in ./vendor/spipu/html2pdf/src/Tests/Image/SrcOkTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
> Deprecation Notice: Class Spipu\Html2Pdf\Tests\Parsing\SrcErrorTest located in ./vendor/spipu/html2pdf/src/Tests/Image/SrcErrorTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185

Is this something you already fixed somewhere?

Thanks

**Comment by xrobau** [comment]
I'm still getting this error when doing a 'composer require':

```
composer require spipu/html2pdf
Using version ^5.2 for spipu/html2pdf
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing tecnickcom/tcpdf (6.3.5): Downloading (100%)
  - Installing spipu/html2pdf (v5.2.1): Downloading (100%)
spipu/html2pdf suggests installing fagundes/zff-html2pdf (if you need to integrate Html2Pdf with Zend Framework 2 (zf2))
spipu/html2pdf suggests installing ext-gd (Allows to embed images into the PDF)
Writing lock file
Generating optimized autoload files
Deprecation Notice: Class Spipu\Html2Pdf\Tests\Parsing\BackgroundErrorTest located in ./vendor/spipu/html2pdf/src/Tests/Image/BackgroundErrorTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Spipu\Html2Pdf\Tests\Parsing\BackgroundOkTest located in ./vendor/spipu/html2pdf/src/Tests/Image/BackgroundOkTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Spipu\Html2Pdf\Tests\Parsing\SrcErrorTest located in ./vendor/spipu/html2pdf/src/Tests/Image/SrcErrorTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Spipu\Html2Pdf\Tests\Parsing\SrcOkTest located in ./vendor/spipu/html2pdf/src/Tests/Image/SrcOkTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Spipu\Html2Pdf\Tests\Output\FileNameOkTest located in ./vendor/spipu/html2pdf/src/Tests/Output/FileNameTest.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

```

**Comment by adrienfr** [comment]
@xrobau current package version is 5.2.2 (and you're fetching 5.2.1)

**Comment by xrobau** [comment]
That's why I posed the command - I didn't specify a version, but it pulled 5.2.1.

**Comment by adrienfr** [comment]
Don't you have another package in your composer.json which require spin/html2pdf@5.2.1?

**Comment by xrobau** [comment]
I couldn't have, otherwise I wouldn't have needed to type the 'composer require' - but it looks like you fixed it after I reported this yesterday, as now I'm pulling 5.2.2!

```
[root@docker1 test]# composer require spipu/html2pdf
Using version ^5.2 for spipu/html2pdf
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing tecnickcom/tcpdf (6.3.5): Downloading (100%)
  - Installing spipu/html2pdf (v5.2.2): Downloading (100%)
spipu/html2pdf suggests installing fagundes/zff-html2pdf (if you need to integrate Html2Pdf with Zend Framework 2 (zf2))
Writing lock file
Generating autoload files
[root@docker1 test]#
```

I also ran a 'composer update' on the project from yesterday, and that upgraded happily:

```
[root@docker1 mail2tiff]# composer update
Loading composer repositories with package information                                                                                  Updating dependencies (including require-dev)
Package operations: 2 installs, 3 updates, 0 removals
  - Updating spipu/html2pdf (v5.2.1 => v5.2.2): Loading from cache
  - Updating nikic/php-parser (v4.4.0 => v4.5.0): Downloading (100%)
  - Installing chillerlan/php-settings-container (1.2.1): Loading from cache
  - Installing chillerlan/php-qrcode (4.0.1): Loading from cache
  - Updating clearlyip/cipfax dev-master (7a5fbcb => d739ea6):  Checking out d739ea6d20
chillerlan/php-qrcode suggests installing chillerlan/php-authenticator (Yet another Google authenticator! Also creates URIs for mobile apps.)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
14 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
[root@docker1 mail2tiff]#
```

If you didn't do anything, then this is REALLY crazytown!  Anyway, confirmed fixed 8)

**Comment by adrienfr** [comment]
Last release was on March 22th, then nothing has changed since yesterday ;)
