### ISSUE TITLE
My god, please help me with this problem 

### ISSUE THREAD

**Issue by dxobject** [spipu/html2pdf#573]
// prepare the out radius
        $outTL = ($outTL[0] && $outTL[1]) ? $outTL : null;
        $outTR = ($outTR[0] && $outTR[1]) ? $outTR : null;
        $outBR = ($outBR[0] && $outBR[1]) ? $outBR : null;
        $outBL = ($outBL[0] && $outBL[1]) ? $outBL : null;

        // prepare the in radius
        $inTL = $outTL;
        $inTR = $outTR;
        $inBR = $outBR;
        $inBL = $outBL;

        if (is_array($inTL)) {
            $inTL[0]-= $border['l']['width'];
            $inTL[1]-= $border['t']['width'];
        }
        if (is_array($inTR)) {
            $inTR[0]-= $border['r']['width'];
            $inTR[1]-= $border['t']['width'];
        }
        if (is_array($inBR)) {
            $inBR[0]-= $border['r']['width'];
            $inBR[1]-= $border['b']['width'];
        }
        if (is_array($inBL)) {
            $inBL[0]-= $border['l']['width'];
            $inBL[1]-= $border['b']['width'];
        }

        if ($inTL[0]<=0 || $inTL[1]<=0) {
            $inTL = null;
        }
        if ($inTR[0]<=0 || $inTR[1]<=0) {
            $inTR = null;
        }
        if ($inBR[0]<=0 || $inBR[1]<=0) {
            $inBR = null;
        }
        if ($inBL[0]<=0 || $inBL[1]<=0) {
            $inBL = null;
        }
*******
The above section is the source code, if  '$inTL' is NULL , The judgment in if will be wrong. I don't quite understand why there is no judgment.I have the same problem: "Notice: Trying to access array offset on value of type null  ,in D:\projects\3clicks\trunk\sf4\main\vendor\spipu\html2pdf\src\Html2Pdf.php (line 1756)".
The PDF printed properly when I added the judgment, but I couldn't easily modify it.
symfony4.4
php7
![1593335330(1)](https://user-images.githubusercontent.com/50607953/85970326-c36fc280-b9fc-11ea-876a-431b3c387b0d.jpg)

**Comment by cedric-r-mycelium** [comment]
May be use  if (!empty($inTL) && is_array($inTL)) {

**Comment by leegarner** [comment]
Changing the lines starting at 1756 like so seems to take care of it.
```
        if (!$inTL || $inTL[0]<=0 || $inTL[1]<=0) {
            $inTL = null;
        }
        if (!$inTR || $inTR[0]<=0 || $inTR[1]<=0) {
            $inTR = null;
        }
        if (!$inBR || $inBR[0]<=0 || $inBR[1]<=0) {
            $inBR = null;
        }
        if (!$inBL || $inBL[0]<=0 || $inBL[1]<=0) {
            $inBL = null;
        }
```

**Comment by dxobject** [comment]
Thanks. Updated to the latest version, this issue has been resolved
