### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable / Html2Pdf.php:5150

### ISSUE THREAD

**Issue by 1YalcinSahin1** [spipu/html2pdf#577]
Hi,

I got this error when trying to create a PDF.

count(): Parameter must be an array or an object that implements Countable 

What is the cause of the problem? Do you have an idea?

Thank you.

**Comment by 1YalcinSahin1** [comment]
I skipped this problem as follows:
```
      if (is_array(self::$_tables[$param['num']]['height']) && count(self::$_tables[$param['num']]['height'])>1) {
                $y = $this->_margeTop+self::$_tables[$param['num']]['height'][count(self::$_tables[$param['num']]['height'])-1];
            } elseif (is_array(self::$_tables[$param['num']]['height']) && count(self::$_tables[$param['num']]['height']) == 1) {
                $y = self::$_tables[$param['num']]['curr_y']+self::$_tables[$param['num']]['height'][count(self::$_tables[$param['num']]['height'])-1];
            } else {
                $y = self::$_tables[$param['num']]['curr_y'];
            }
```

But now I get an error like this. The current sentence takes more than 1000 lines is the current box

  $html2pdf->setSentenceMaxLines(700000); 

Even this did not solve my mistake. It took a long time.

**Comment by spipu** [comment]
normally it has been resolved in the last version of html2pdf

which version do you use ?
