### ISSUE TITLE
Error: <path> attribute d: Expected arc flag ('0' or '1'), "…-17 191a1 1 0 0 -3 0 2h2a1 1 0 0…".

### ISSUE THREAD

**Issue by LuoReid** [spipu/html2pdf#580]
My demo is show :Error: <path> attribute d: Expected arc flag ('0' or '1'), "…-17 191a1 1 0 0 -3 0 2h2a1 1 0 0…". and the pdf content is empty.

**Comment by spipu** [comment]
can you give me the full svg example to make some tests ?

thanks

**Comment by LuoReid** [comment]
> can you give me the full svg example to make some tests ?
> 
> thanks

I as so sorry for this. The reason is my project svg file's error.
thanks
