### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by arifulalam** [spipu/html2pdf#6]
Hello,
How to add background image for generated PDF file?

Regards

**Comment by georaldc** [comment]
You can use html2pdf's page element and pass a background image to it using the backimg attribute

```
<page backimg="path/to/image">
...content of pdf
</page>
```

See the docs here for more info on all the other available attributes:

http://wiki.spipu.net/doku.php?id=html2pdf:en:v4:page

**Comment by spipu** [comment]
you can also use the css background-image property :)
