### ISSUE TITLE
Using the script in a for loop

### ISSUE THREAD

**Issue by oetrb** [spipu/html2pdf#603]
Hey,

I want to use the <page> tag multiple times to create pages dynamically.
How is this possible?
I tried the following:

for ($x=0; $x < 4; $x++){
echo "begin for";	?>
<page style="font-size: 12px"; >
<bookmark title="Rechnungsbeilage Erwachsene Seite 1" level="0" ></bookmark>
<a name="document_reprise"></a>
	--------------------------- page content --------------
</page>
<?php echo "ende for";}} ?>

This only do it one time.

**Comment by spipu** [comment]
it works exactly like when you try to build any html. look at example 7, you will see that à do that for lines

**Comment by oetrb** [comment]
thanks!
