### ISSUE TITLE
Insert image from local file without exposing publicly

### ISSUE THREAD

**Issue by chrispytoes** [spipu/html2pdf#604]
I am trying to use a data URI to display an image but it's throwing an exception that has no error message. I need to put images into my PDF that are inside a private directory without needing to expose them.

```
$mime_type = mime_content_type($file_path);
$image_data = base64_encode(file_get_contents($file_path));
$data_uri = "data: $mime_type;base64,$image_data";
```

When I try using `$data_uri` as an `img` src, it throws a blank error with no message.

**Comment by spipu** [comment]
same response that in https://github.com/spipu/html2pdf/issues/605 

put the image path in the src attribute of the image tag

**Comment by chrispytoes** [comment]
@spipu Ah okay, I will try it with a file path when I get a chance.

I was only under the impression the image had to be public because [example 9](https://github.com/spipu/html2pdf/blob/master/examples/example09.php) was the first one I read, which does use a public image URL. I do see the other examples that use a relative local path now.

Sorry for the duplicate issue. It bugged out on me and posted it twice.
