### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by md4github** [spipu/html2pdf#606]
Hello,

I use an old version of html2pdf which will be soon unusable in php 8 (some notices/warnings will become errors).
That's why I would like to get and install the last version of html2pdf on my web server.
Unfortunately it is now necessary to install and use composer. I could install it on my computer (version 2.0.6)
but I get the following message when I try to install html2pdf with 'composer require spipu/html2pdf' :
'Root package 'spipu/html2pdf' cannot require itself in its composer.json'
It is probably because I do not understand the instruction (English is not my mother language) : 
'You have to commit the composer.json and composer.lock files'

Best regards,

**Comment by W0rma** [comment]
@md4github Can you please share the content of your `composer.json`?
