### ISSUE TITLE
How to add font family ?

### ISSUE THREAD

**Issue by thierryler** [spipu/html2pdf#629]
I've tried many things to add a new font, like comics, but I get errors whatever the technique used.

Does anybody have a real example to copy ?

**Comment by thierryler** [comment]
After many hours, I finally figured out how to do...

First, download the ttl files of your font. For example, I've downloaded the free font "DancingScript-Regular" from Google font.

Then, go to https://www.xml-convert.com/fr/convertir-fichiers-polices-ttf-en-afm-pfa-fpdf-tcpdf to convert your file into php. I choosed "DancingScript-Regular.ttl" and it created "DancingScript-Regular.php" in my example.

Place the converted files and the font files into the same folder.

Then, here is what it should look like:

```
$html2pdf = new Html2Pdf('P', 'A4', 'fr', true, 'UTF-8', array(0, 0, 0, 0));
$html2pdf->addFont('DancingScript', 'regular', '/var/.../font/DancingScript/DancingScript-Regular.php');
```

Then in you CSS block:
```
div.foo {
    font-family: DancingScript;
    font-size: 14pt;
}
```

Hope it helps.

**Comment by PadharaHitesh** [comment]
> ny hours, I finally figured out ho

Hello @thierryler,

I have tried this solution but when I convert the given URL it will throw some errors. Please check the [below](url) SS.
!
![error](https://user-images.githubusercontent.com/31240842/141779801-2a57ad74-5caf-4406-8634-e17012c2879b.png)
