### ISSUE TITLE
Css Border:0; render a border.

### ISSUE THREAD

**Issue by Maypeur** [spipu/html2pdf#63]
Hello,
I do not know if it has to be considered as a problem but :

If i have border:0; in my css html2pdf draw a border on the styled block.
In a browser there isn't any border.
Finaly, I must set border:0px; (force unit) to do not draw a border.
Thanks.

**Comment by spipu** [comment]
if you do not want a border, you have to use border: none;

but there is a bug in the CSS parser, method readBorder : the test `if ($v) {` is wrong. It muse be `if ($v !=='') {`

**Comment by spipu** [comment]
fixed on branch master and v4.5

will be added to the next versio v4.5.1 of HTML2PDF
