### ISSUE TITLE
Can't "install" html2pdf

### ISSUE THREAD

**Issue by TorakikiSan** [spipu/html2pdf#643]
Situation: Apache with multiple virtual hosts and php 7.4.16

```
/ home / project1
/ home / project2
/ home / project3
```

etc.

I tried putting the html2pdf-master folder on level

`/ home / html2pdf-master`

or within a project

`/ home / project1 / html2pdf-master`

but every time I launch composer, just installed and from inside the folder, I get the error

**`> composer require spipu/html2pdf`**
```
Using version ^5.2 for spipu/html2pdf
Root package 'spipu/html2pdf' cannot require itself in its composer.json
```
Any hint?

**Comment by allgrowsm** [comment]
I guess you better share an error messages.
Otherwise, no one can help you.
