### ISSUE TITLE
CSS NOT SUPPORTED

### ISSUE THREAD

**Issue by alisaleem252** [spipu/html2pdf#648]
CSS doesn't work, so no point of using this library.

**Comment by dominikfladung** [comment]
CSS is supportet. If you need help, than you must be more specfic.

**Comment by alisaleem252** [comment]
Style and link tag does not work and, no documentation available to add a stylesheet or embed css.

**Comment by YuriZoko** [comment]
Hello, try :

<link rel="stylesheet" type="text/css" href="style.css">

work for me

**Comment by alisaleem252** [comment]
Okay i haven't tested it, but i am closing this issue.

**Comment by williansmartins** [comment]
I tested but doesn't work.
