### ISSUE TITLE
 Parse error: syntax error, unexpected 'use' (T_USE) in 

### ISSUE THREAD

**Issue by md4github** [spipu/html2pdf#665]
Hello,

When I try tu use the example 'example00.php' installed on my web site,
it gives me a correct pdf file without issue.

But when I try to use the same code one another web page (on the root of my web site, I get the following error message: 
"Parse error: syntax error, unexpected 'use' (T_USE) in ..."
... for the line:
"use Spipu\Html2Pdf\Html2Pdf;"

Does it mean that the autoload.php is not correctly loaded:
require_once('.../vendor/autoload.php');
And if yes, I do not understand why because the path is correct.

Best regards,

**Comment by tasiot** [comment]
Hi,

Your code is invalid (parse error) on your file and it's not about html2pdf. 
Please read https://www.php.net/manual/en/language.namespaces.importing.php and fix your code.

Publish your code here if help is really needed but your require_once example is also wrong: "..." instead of ".."

So read and fix your php code and close this issue. 
Thanks

**Comment by md4github** [comment]
Thank you for your help

**Comment by Bouquetin-fr** [comment]
It's strange : i've the same error but i don't understand why.
I try to include htmltopdf in a function wordpress but it doesn't work.
When I use just this code :
`	<?php
         require $_SERVER["DOCUMENT_ROOT"].'/wp-content/bin/vendor/autoload.php';
	use Spipu\Html2Pdf\Html2Pdf;

	$html2pdf = new Html2Pdf();
	$html2pdf->writeHTML('<h1>HelloWorld</h1>This is my first test');
	$html2pdf->output();
?>`
It's work, no problem.

But, when I pu the same code in a function, There is a critical problem : "Parse error: syntax error, unexpected 'use' (T_USE) in "
`function bouton_pdf($fiche, $cat) {
	require $_SERVER["DOCUMENT_ROOT"].'/wp-content/bin/vendor/autoload.php';
	use Spipu\Html2Pdf\Html2Pdf;

	$html2pdf = new Html2Pdf();
	$html2pdf->writeHTML('<h1>HelloWorld</h1>This is my first test');
	$html2pdf->output();
}`

How is possible ? It's the same code ! Do you have an idea ?

**Comment by tasiot** [comment]
Use : $html2pdf = new Spipu\Html2Pdf\Html2Pdf();

Please read php documentation about namespace…

**Comment by Bouquetin-fr** [comment]
Thanks for your help.

I tried to read before. It's not clear to me. But thanks.
