### ISSUE TITLE
Background  Image appearing in multiple pages

### ISSUE THREAD

**Issue by Hatchberries** [spipu/html2pdf#667]
I am adding background image as watermark for a section but the thing is if some portion of the section moves in to next page that image is appearing on next page also. How can i correct this.
![localhost-profilecheck-PHP-pdf-sample-](https://user-images.githubusercontent.com/83953670/124771257-9bdcff80-df58-11eb-8d81-cee2ad7436ab.png)

**Comment by gulm75bs** [comment]
Greetings friend, sorry how you inserted background image with html2pdf, I want to use it but I could not

**Comment by Hatchberries** [comment]
I fount this is  the feature of this pdf and it appears along with the content.
