### ISSUE TITLE
Install without Composer

### ISSUE THREAD

**Issue by ev5unleash** [spipu/html2pdf#67]
Hi there,

I don't have server level access to the website I'm developing and I would like to know how to easily include HTML2PDF without the need of composer? Is there a fully extractable package that I can use? 

Thanks,

**Comment by juchi** [comment]
Hi,
You can use Html2Pdf without using composer, but that will be a bit more cumbersome : clone the repository and its dependencies (currently you only need TCPDF) and you'll have all the necessary code on your machine. You will however not have class autoloading out of the box so you'll need to do it manually.

However, if you don't have server access at all, you won't be able to modify any of the code on it, am I wrong ? In this case I'm afraid there's nothing you can do.

**Comment by ev5unleash** [comment]
Sorry' I meant remote access. I can FTP. Thanks for the help and the swift
response!

**Comment by spipu** [comment]
Then, just prepare your app on your computer, and install html2pdf with composer on your computer.

Then upmoad your app via ftp on your serveur

**Comment by kikoseijo** [comment]
No so clever. so, composer yes or yes?
Faster finding an alternative.

**Comment by tpaksu** [comment]
In my case I did something like this:

1) Installed composer on my local computer
2) created a `composer-packages` folder inside the project root
3) navigated inside it with command line, run `composer init`, answered questions
4) when everything else finished, ran `composer require spipu/html2pdf`, waited for it to finish
5) then on my main code:
```php
// include autoloader
require_once 'composer-packages/vendor/autoload.php';
$html2pdf = new Spipu\Html2Pdf\Html2Pdf();
$html2pdf->writeHtml("testing");
$html2pdf->output("test.pdf", "I");
```` 

It worked. I think it will also work when uploaded to the server with all the files included.

**Comment by ObstinateDipak** [comment]
> In my case I did something like this:
> 
> 1. Installed composer on my local computer
> 2. created a `composer-packages` folder inside the project root
> 3. navigated inside it with command line, run `composer init`, answered questions
> 4. when everything else finished, ran `composer require spipu/html2pdf`, waited for it to finish
> 5. then on my main code:
> 
> ```
> // include autoloader
> require_once 'composer-packages/vendor/autoload.php';
> $html2pdf = new Spipu\Html2Pdf\Html2Pdf();
> $html2pdf->writeHtml("testing");
> $html2pdf->output("test.pdf", "I");
> ```
> 
> It worked. I think it will also work when uploaded to the server with all the files included. Might not need composer to be installed to the server if you upload all your `composer-packages` folder.

This saved my day. Worked perfectly.

**Comment by astrakid** [comment]
thanks as well!!! helped me a lot!
