### ISSUE TITLE
Possible to use html2pdf without composer?

### ISSUE THREAD

**Issue by gustavopi** [spipu/html2pdf#679]
First, the statement of MUST use composer, years late etc. is kinda offensive. I don't use any framework in my php 7 projects, I am a pure php coder, it's a way of working of many coders around the world. You should have some respect for people thinking different than you.

I have composer installed already but won't use it right now, is not working good in my macOS Big Sur, not sure why, got no time to make it work. I just want to know if I is possible and ALLOWED to use html2pdf without composer (as Facebook SDK and Google API).

Thanks.

**Comment by tizis** [comment]
> First, the statement of MUST use composer, years late etc. is kinda offensive. I don't use any framework in my php 7 projects, I am a pure php coder, it's a way of working of many coders around the world. You should have some respect for people thinking different than you.
> 
> I have composer installed already but won't use it right now, is not working good in my macOS Big Sur, not sure why, got no time to make it work. I just want to know if I is possible and ALLOWED to use html2pdf without composer (as Facebook SDK and Google API).
> 
> Thanks.

Composer — is php standard if you don't want to be a deprecated; It is not about frameworks;

But — if you really, really can't use composer (in this situation — composer's psr-4 autoloader) — you can create your custom autoloader for this package; 

(https://stackoverflow.com/questions/39571391/psr4-auto-load-without-composer)

**Comment by spipu** [comment]
i update the doc

https://github.com/spipu/html2pdf/blob/master/doc/install.md

about composer, it becomes a standard now. i think we will always have it for next years, it is like yarn on JS, or apt on linux
