### ISSUE TITLE
Question Installation

### ISSUE THREAD

**Issue by CismE97** [spipu/html2pdf#69]
Hey, 

I want to install HTML2PDF in my Website ... But I don't how to do it..
I have download the files by FTP. 

And I have this error : "[ERROR] It seems that HTML2PDF dependencies are not installed... you must install thems with `composer install`"

I Know, I must install "composer" but how ? By SSH in my server ?

Thanks

**Comment by fagundes** [comment]
Yes, you can install composer when you are logged by SSH.

There are several ways to install the composer. See here [composer download](https://getcomposer.org/download/).

**Comment by CismE97** [comment]
Yes I have try this : but I have this error : 

bash-4.2$ curl -sS https://getcomposer.org/installer | php
bash: php: command not found
curl: (77) Problem with the SSL CA cert (path? access rights?)

I'm not good with ssl and server.. I know...

**Comment by juchi** [comment]
Hi,
The message is pretty straightforward : you do not have access to a php executable on this server. Are you sure PHP is installed ?

**Comment by juchi** [comment]
Closing the issue as it is not Html2Pdf related.

**Comment by christekue** [comment]
i had the same probleme use this https://www.youtube.com/watch?v=lyEemHKMPPg to install

**Comment by christekue** [comment]
this is my probleme : [ERROR] It seems that HTML2PDF dependencies are not installed... you must install thems with `composer install` / need help

**Comment by juchi** [comment]
You just need to run a composer install process
`composer install` or `php composer.phar install` depending on the location of your composer binary.

**Comment by christekue** [comment]
Hi guys is it possible to send the pdf generate by attachement trought email? if yes? how? pls help is any solutions

**Comment by CismE97** [comment]
Yes it's possible.
Saves your pdf in your server.
And then ,  I'use phpmailer to Write And attach the file:)

**Comment by christekue** [comment]
thanks for your answer, but pls can you try more to explain i am just junior in devolopping php. Thanks

**Comment by krisanachai** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]
