### ISSUE TITLE
How to use HTML2PDF without Composer

### ISSUE THREAD

**Issue by jpbond13** [spipu/html2pdf#690]
Hello, 
i'm not familiar with Composer, and i just want to use HTML2PDF in my existing PHP Bootstrap 4 project to be able to create a PDF version of my existing PHP/HTML page without using the print to PDF function.
Is there a way to do it ?
Best regards

**Comment by mhpcc** [comment]
In the readme: You must use Composer to install this library.

Composer is simple.
```
sudo dnf install composer
composer init
composer require spipu/html2pdf
```
done

**Comment by XTeslaUA** [comment]
Hi. Install XAMPP on local machine.
Install Composer on local machine.
Install "composer require spipu/html2pdf" on local machine. in cmd windows. 
Copy directory vendor\ to Website directory!
