### ISSUE TITLE
[Bug 5.2.3] text-align center: last line incorrectly positioned

### ISSUE THREAD

**Issue by mhpcc** [spipu/html2pdf#693]
5.2.2: 
![image](https://user-images.githubusercontent.com/50452722/146027755-48a6fd27-ce63-4c50-a22f-bbcfdd92d01e.png)

5.2.3:
![image](https://user-images.githubusercontent.com/50452722/146028162-71f071d7-4886-4183-b635-52eb0958fa9e.png)

I haven't yet been able to check out why this happens but it surely looks bad.

**Comment by mhpcc** [comment]
https://github.com/spipu/html2pdf/commit/4e1360acc186f125eceaaad35e7fd2c48d2bd4a5

This is what makes it all weird. It cuts strings into weird pieces instead of what I'd expect.

**Comment by spipu** [comment]
hi,

if the encoding is utf8, why do you need to convert your string into utf8 ? normally the encoding to provide is the one you use :)

maybe you did not provide UTF8 string to html2pdf ? in that case, convert your html string before, or provide the good encoding to html2pdf constructor

**Comment by mhpcc** [comment]
Hi, weirdly enough my encoding already is utf-8. mb_detect_encoding returns utf-8, mb_check_encoding returns true - I need to html_encode any string I pass to html2pdf with utf8_encode

**Comment by spipu** [comment]
can you test with the last release https://github.com/spipu/html2pdf/releases/tag/v5.2.4 ?

normally it should be fixed

**Comment by mhpcc** [comment]
yeah since that reverts the change, it also fixes the position issue

**Comment by martin-watts** [comment]
Hi @mhpcc, I'm working on a project that needed https://github.com/spipu/html2pdf/commit/4e1360acc186f125eceaaad35e7fd2c48d2bd4a5 as we were seeing multibyte chars being split in the middle of the character: Just wondering if you can supply the source string for your examples above so we can attempt a fix that also is multibyte aware?
