### ISSUE TITLE
HTML2PDF draw image on php 8.1

### ISSUE THREAD

**Issue by alexmfCAT** [spipu/html2pdf#705]
Hi

I updated my PHP to latest version (8.1) and, then, I get this error on my PDF generation:
![image](https://user-images.githubusercontent.com/102383319/160179592-68d1e224-dc14-4a6e-9021-7a362fcded5f.png)

How I can fix this?

Best regards

**Comment by lenamtl** [comment]
Hi,
Are you using the latest HTML2PDF version?

**Comment by lenamtl** [comment]
Hi,
I'm planning to update to PHP 8.1 did you fix the problems?

**Comment by spipu** [comment]
it occurs when the html is bad formatted (ex: not the same number of cells on each row of a table)
