### ISSUE TITLE
how to check if the pdf downloaded finish?

### ISSUE THREAD

**Issue by nikalailk** [spipu/html2pdf#71]
Hi, I use html2pdf and output as 'd' (i.e. $html2pdf->Output($diffname,'d');).
I want to add some alert/close the current after the download finish.
How can I check this?

**Comment by juchi** [comment]
Hi,
To my knowledge you cannot know (server side) when the file transfer will be done, as it's not managed directly by the PHP code. The code after the call to Output() will be executed after the data is sent but you have no guarantee that the download is finish on the browser.
If you are dealing with the download in AJAX you should probably be able to determine when the transfer is done.

**Comment by nikalailk** [comment]
or can i know when the download start?

**Comment by juchi** [comment]
Your question is quite unclear. Are you talking server side or client side ? What do you mean exactly by "download start" ?
Anyhow, this doesn't seem to be related directly to Html2pdf as is more of a raw PHP or JS question depending on your use case.
