### ISSUE TITLE
Import a Chart.js into html2pdf

### ISSUE THREAD

**Issue by ytreza9** [spipu/html2pdf#712]
Dear all,

I'm trying to do exactly what is on the title, eg call from my html2pdf document a php file where is created a chart with chart.js.
I understood that both are not working from the same side of the server, and an anwer could be to to create an image of the chart and to call this image from the html2pdf document. Nevertheless, I cannot find any exemple how to do that...

Any idea for me ?

Thank you all

**Comment by andreas83** [comment]
i would use phantomjs to create a screenshot of your chart.js and than simply add it into your pdf. 

```
var page = require('webpage').create();
page.open('https://www.chartjs.org/docs/latest/samples/line/line.html', function() {
    setTimeout(function() {
        page.render('chartjs.png');
        phantom.exit();
    }, 200);
});
```

and then add "chartjs.png" to your pdf via img tag. 

`<img src="chartjs.png" />`

**Comment by spipu** [comment]
html2pdf is to generate Paper documents... no JS ...
