### ISSUE TITLE
Installation compozer dernière version (v5)

### ISSUE THREAD

**Issue by Arthezius** [spipu/html2pdf#726]
Bonjour à tous,

Je viens de faire l'installation avec composer de HTML2PDF.
Je suis sur Ubuntu, j'ai installé composer récupéré HTML2PDf avec la commande :
`php composer.phar require spipu/html2pdf`

HTML2PDF a bien été installé dans mon dossier.

Toutefois c'est la version _HTML2PDF v4.6.1 - 2016-04-05_ qui a été téléchargée.

J'ai un problème avec cette version puisque j'ai le message suivant qui apparaît quand j'affiche le PDF généré:
` Fatal error: Array and string offset access syntax with curly braces is no longer supported in /homepages/14/d291669841/htdocs/cseAubin/vendor/tecnickcom/tcpdf/tcpdf.php on line 16900`

Il s'agirait d'un problème de compatibilité avec les dernières versions de PDF si j'ai bien compris.
Comment avoir la dernière version ?

Merci par avance.

**Comment by jausions** [comment]
Il faut plutôt voir côté composer.json ou composer.lock pour comprendre pourquoi la version installée est 4.6.1 et non pas une plus récente. Pour info, c'est la dernière qui tourne sous PHP 5.3.
