### ISSUE TITLE
Wrong width of <TD> when using border-collapse and a <div> element

### ISSUE THREAD

**Issue by naitsirch** [spipu/html2pdf#73]
Hi.
I have found a bug, when having a table with `border-collapse: collapse` and there is a <div> element in one of the cells.
You can reproduce the issue with this snippet:

``` html
<style type="text/css">
    table {border-collapse: collapse;}
    .table-bordered {border-width: 0.25mm; border-style: solid; border-color: #aaaaaa;}
</style>
<page backtop="5mm" backbottom="5mm" backleft="5mm" backright="5mm">
    <table>
        <tr>
            <th class="table-bordered" style="width: 20mm;">0 0</th>
            <th class="table-bordered" style="width: 21mm;">0 1</th>
            <th class="table-bordered" style="width: 22mm;">0 2</th>
        </tr>
        <tr>
            <td class="table-bordered"><div>1 0</div></td>
            <td class="table-bordered">1 1</td>
            <td class="table-bordered">1 2</td>
        </tr>
    </table>
</page>
```

The result of this code looks like this:
![with-collapse](https://cloud.githubusercontent.com/assets/1118790/12671361/650ded1e-c66f-11e5-879f-016726fd3702.png)
The first column is stretched over the whole page, because of the `<div>`element in the table cell.
But if you remove the `table {border-collapse: collapse;}` the table is rendered correctly. See:
![without-collapse](https://cloud.githubusercontent.com/assets/1118790/12671440/f14c2a8e-c66f-11e5-93f0-179547f5aa90.png)

I tried to debug the code and find out why this happens. But I was unsuccessful. So I hope you are more successful and can fix the issue @spipu ;-)

**Comment by spipu** [comment]
it is because you do not put any width to the div.
You must specify the width of the divs for HTML2PDF. If you do not specify it, HTML2PDF use all the page's width.

It was not possible to determine the possible width of a diff without any performance pb.

**Comment by naitsirch** [comment]
In CSS a block element inherits the width from its parent element. In this case the parent element is the `TD`.
It would be nice if this behaviour could be implemented ;-)

But I wonder why the `DIV` does not use the whole page width when `border-collapse: collapse` is not used.

**Comment by spipu** [comment]
we have to look at why it works without collapse...

**Comment by naitsirch** [comment]
Yes. I tried to do that, but it was too confusing :-/

**Comment by spipu** [comment]
There was a little bug on the div position, it is fixed on master branch.

Now it works with this : 

```
<style type="text/css">
    .table-bordered {border-width: 0.25mm; border-style: solid; border-color: #aaaaaa;}
</style>
<page backtop="5mm" backbottom="5mm" backleft="5mm" backright="5mm">
    <table>
        <col class="table-bordered" style="width: 20mm;">
        <col class="table-bordered" style="width: 21mm;">
        <col class="table-bordered" style="width: 22mm;">
        <tr>
            <th>0 0</th>
            <th>0 1</th>
            <th>0 2</th>
        </tr>
        <tr>
            <td><div>1 0</div></td>
            <td>1 1</td>
            <td>1 2</td>
        </tr>
    </table>
    <table style="border-collapse: collapse;">
        <col class="table-bordered" style="width: 20mm;">
        <col class="table-bordered" style="width: 21mm;">
        <col class="table-bordered" style="width: 22mm;">
        <tr>
            <th >0 0</th>
            <th>0 1</th>
            <th>0 2</th>
        </tr>
        <tr>
            <td><div>1 0</div></td>
            <td>1 1</td>
            <td>1 2</td>
        </tr>
    </table>
</page>
```
