### ISSUE TITLE
How to include XML into a PDF ? (Factur-X format)

### ISSUE THREAD

**Issue by thierryler** [spipu/html2pdf#735]
The "factur-x" standard requires PDF invoice files to include data in XML. How can this XML be added using html2pdf?

**Comment by thierryler** [comment]
I've founded that

```
$html2pdf->pdf->Annotation(0, 0, 0, 0, '', array(
  'Subtype' => 'FileAttachment', 
  'Name'    => 'PushPin', 
  'FS'      => $attachedFile,
));
```

where attachedFile is the xml file on the disk.

Maybe there is something better than an annotation...

**Comment by spipu** [comment]
this is not related to html2Pdf, but more to tpdf, ask on their project :)
