### ISSUE TITLE
Firefox error

### ISSUE THREAD

**Issue by Aphexus** [spipu/html2pdf#738]
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://bab08e37-c513-4404-adf6-b1d8ddac8e71/userscripts/nlab%20pdf%20printer.user.js?id=9ee22c4a-475e-46dc-8f1b-6809d8f04e94
Source Map URL: html2pdf.bundle.min.js.map/

I have a very simple script that prints a page, a few lines of code essentially from the sample script but I'm using it in tampermonkey. It works fine in IE except I get a blank page before or after and I'm trying to figure out how to stop it(I had to set pagebreak:    { mode: 'avoid-all', after: '#Content' } because I would get breaking in the middle of lines but this adds a blank page after).

Anyways, in Firefox I get the error about sourcemaps and this seems to be related to a bug in firefox which hasn't been fixed for years.

https://firefox-source-docs.mozilla.org/devtools-user/debugger/source_map_errors/index.html
https://bugzilla.mozilla.org/show_bug.cgi?id=1437937

**Comment by spipu** [comment]
not the good html2pdf project. here it is about php project, not js project
