### ISSUE TITLE
i got this error in php 5.3.3

### ISSUE THREAD

**Issue by sabardotnet** [spipu/html2pdf#74]
Fatal error: Can't inherit abstract function Spipu\Html2Pdf\Tag\TagInterface::getName() (previously declared abstract in Spipu\Html2Pdf\Tag\AbstractTag) in /var/www/ikoolclub.com/public_html/vkooladmin/html2pdf/src/Tag/AbstractTag.php on line 25

how to fix it thanks

**Comment by juchi** [comment]
Hi,
This is a PHP bug fixed in 5.3.9.
Since the code you are using is from the master branch and was not released yet, I advise you to use the version 4.5.0 of Html2Pdf which should be working fine on your configuration.

**Comment by sabardotnet** [comment]
i just upgrade php and solved.. thanks..
