### ISSUE TITLE
Error Output method

### ISSUE THREAD

**Issue by OswaldoAranda** [spipu/html2pdf#748]
When using the Output method with the 'F' parameter, it is returning a Deprecated error.

"PHP message: PHP Deprecated: Creation of dynamic property Spipu\Html2Pdf\Html2Pdf::$_pdfa is deprecated in /usr/local/.../.../.../vendor/spipu/html2pdf/src/Html2Pdf.php

If I use the Output method without parameters, it works without errors.

Use  "spipu/html2pdf": "^5.2"

**Comment by spipu** [comment]
fixed in the last version 5.2.6
