### ISSUE TITLE
Creation of dynamic property in PHP 8.2

### ISSUE THREAD

**Issue by fredmatrack** [spipu/html2pdf#749]
We're currently testing html2pdf in PHP 8.2. When enabling all errors, we see a lot of these errors:

> Deprecated: Creation of dynamic property Spipu\Html2Pdf\Html2Pdf::$_pdfa is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/Html2Pdf.php on line 192
> 
> Deprecated: Creation of dynamic property Spipu\Html2Pdf\Html2Pdf::$_pdfa is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/Html2Pdf.php on line 192
> 
> Deprecated: Creation of dynamic property Spipu\Html2Pdf\MyPdf::$ws is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/MyPdf.php on line 237
> 
> Deprecated: Creation of dynamic property Spipu\Html2Pdf\MyPdf::$ws is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/MyPdf.php on line 237
> 
> Deprecated: Creation of dynamic property Spipu\Html2Pdf\MyPdf::$ws is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/MyPdf.php on line 237
> 
> Deprecated: Creation of dynamic property Spipu\Html2Pdf\MyPdf::$ws is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/MyPdf.php on line 237
> 
> Deprecated: Creation of dynamic property Spipu\Html2Pdf\MyPdf::$ws is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/MyPdf.php on line 237
> 
> Deprecated: Creation of dynamic property Spipu\Html2Pdf\MyPdf::$ws is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/MyPdf.php on line 237
> 
> Deprecated: Creation of dynamic property Spipu\Html2Pdf\MyPdf::$ws is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/MyPdf.php on line 237
> 
> Deprecated: Creation of dynamic property Spipu\Html2Pdf\MyPdf::$ws is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/MyPdf.php on line 237
> 
> Deprecated: Creation of dynamic property Spipu\Html2Pdf\MyPdf::$ws is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/MyPdf.php on line 237

Deprecated: Creation of dynamic property Spipu\Html2Pdf\MyPdf::$ws is deprecated in /var/www/vhosts/inc/vendor/spipu/html2pdf/src/MyPdf.php on line 237

**Comment by sroehrl** [comment]
Addressed in https://github.com/spipu/html2pdf/pull/751 

I don't know if & how fast the maintainer can address this. If you want to play around, feel free to use my fork for now.

**Comment by spipu** [comment]
fixed in the last version 5.2.6
