### ISSUE TITLE
how to attach with codeigniter email ?

### ISSUE THREAD

**Issue by sabardotnet** [spipu/html2pdf#75]
i use pjmail in codeigniter but not working, may be problem with email config like smtp host..etc,

how to send html2pdf convert as attach in send mail codeigniter or may u want to tell me how to use pjmail in codeigniter.. thanks..

**Comment by juchi** [comment]
Hi,
This is not an issue related to Html2Pdf but rather a question about codeigniter, so I advise that you ask this question on the project's page. On Html2Pdf side you will just need to save the file on disk before sending it.
Regards
