### ISSUE TITLE
errors with some files inclusion

### ISSUE THREAD

**Issue by sashabeep** [spipu/html2pdf#76]
Trying to open test examples and get this errors:

```
Warning: require_once(/-----------/html2pdf/examples/../vendor/autoload.php) [function.require-once]: failed to open stream: No such file or directory
```
And then fatal error, of course
Where can i find this file?

**Comment by juchi** [comment]
Hi,
Did you run composer before trying to run your application ? If you didn't, please follow the installation step from the readme file.
Regards,

**Comment by sashabeep** [comment]
I don't have composer on shared hosting

**Comment by juchi** [comment]
Well in this case you have only a few solutions :
* push the vendor directory after running a composer install on our local machine
* manage the autoloading manually
* not use a shared hosting

**Comment by rafelck** [comment]
You need to copy your vendor folder to shared hosting.
