### ISSUE TITLE
hyphenation

### ISSUE THREAD

**Issue by rikricci** [spipu/html2pdf#77]
Hi
is the hypenation (plugin of fpdf) supported?
I tried with this code

$html2pdf = new HTML2PDF('P', 'A4', 'it', true, 'UTF-8',array(0,0,0,0));
$html2pdf->pdf->SetDisplayMode('fullpage');
$hyphen_patterns = $html2pdf->pdf->getHyphenPatternsFromTEX('hyphens/it.tex');
$content = $html2pdf->pdf->hyphenateText($content, $hyphen_patterns, array(), 1, 2, 1, 8);
$html2pdf->writeHTML($content);
$html2pdf->Output($allegato, 'F');

but not works

Thanks

**Comment by spipu** [comment]
HTML2PDF doest no use FPDF, it use TCPDF, you can not use fpdf plugins

**Comment by rikricci** [comment]
But The hypenation is possible?
Il 02/Mar/2016 11:59, "Laurent MINGUET" <notifications@github.com> ha
scritto:
