### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by sectroyer** [spipu/html2pdf#777]
Hello.
I would like ot ask how can I report a security issue in Html2Pdf?
Regards.

**Comment by spipu** [comment]
Hi,

You can send a message to the email that is in the phpdoc @author in all the files.

thanks a lot,

Spipu - Laurent

**Comment by sectroyer** [comment]
Hello.
I have sent details regarding the issue we have found to the email from source file. Wanted to make sure if you received it? Do you need any more details?
Regards.

**Comment by spipu** [comment]
i did not receive any thing.

can you send it to spipu@spipu.net ? thanks. i will remove this email from the comment in 1 hour
