### ISSUE TITLE
Allow to specify a fallback image if an image is not available

### ISSUE THREAD

**Issue by clement-michelet** [spipu/html2pdf#79]
When an image is not available, it is currently replaced by a pink area.

It could be great to :
- allow to specify the background color to use if no image is available
- allow to specify a replacement image

This change will imply to update `_drawImage` and `_drawRectangle` methods.

**Comment by spipu** [comment]
we can add 2 methods setImageFallbackBackground and setImageFallbackImage and use thems if they are used.

JUCHI, what do you think ?

**Comment by juchi** [comment]
Yes, it could be an improvement for the 4.6 release. I'll add the milestone.
On the 5.* branch I hope we'll be able to provide some kind of configuration for this.

**Comment by juchi** [comment]
Hi,
The fallback image system is in place as of 4.6.0. Still, there is currently no change for the default greyish color when no image (or fallback) is found.
