### ISSUE TITLE
hypenation

### ISSUE THREAD

**Issue by rikricci** [spipu/html2pdf#83]
The hypenation is suported in html2pdf? If yes how is the function?
Thanks

**Comment by rikricci** [comment]
So I haven't an answer to my question.
I can suggest to other user another plugin, mPdf http://www.mpdf1.com/mpdf/index.php.
It solve the problem of the hypenation and more others.
it is also much faster and leaner than html2pdf

Bye

**Comment by fagundes** [comment]
@rikricci  I do not know what you mean about hypenation (hyphens property in css?) but, this is a open source project, you can contribute any time, same about speed.

**Comment by juchi** [comment]
Hi,

Hyphenation is not supported in Html2Pdf at this time.

Julien

**Comment by rikricci** [comment]
Thanks

2016-04-12 9:37 GMT+02:00 Julien Chichignoud <notifications@github.com>:

> Hi,
>
> Hyphenation is not supported in Html2Pdf at this time.
>
> Julien
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/spipu/html2pdf/issues/83#issuecomment-208757153>
>



-- 

*Riccardo Ricci*

*Tel: 349/5811158*

*Email: rikricci@gmail.com <rikricci@gmail.com>*
