### ISSUE TITLE
css dir=-rtl not worked ,

### ISSUE THREAD

**Issue by apsana** [spipu/html2pdf#88]
dir=rtl not worked ;

**Comment by juchi** [comment]
Hi,
Care to give more insight about your problem/question ?
To my knowledge, right to left text direction is not supported by Html2pdf if that's what you are wondering.

**Comment by apsana** [comment]
look your email webmaster@html2pdf.fr
iI send a email

**Comment by apsana** [comment]
github i can't send picture

**Comment by juchi** [comment]
Hi,
Github issues are now the official location for reporting issues. You may add an image to your message by attaching it with the specific link below the textbox. Please also provide an explanation to your issue.
Thank you.

**Comment by apsana** [comment]
[http://open.microhat.cn/public/12.png](url)
this a test  image  set dr =rtl

**Comment by juchi** [comment]
Hi,
Your link is marked as unsafe so I removed it.
If you cannot provide an understandable explanation of your problem here i'll have to close the issue as it's not getting anywhere.
