### ISSUE TITLE
External Js

### ISSUE THREAD

**Issue by sajumani** [spipu/html2pdf#89]
Hi,

how do we use external js( Jquery plugins ).

i have html page with javascript, highcharts, html, css but its not working with external js

any solution ..??

**Comment by spipu** [comment]
PDF is static... So you can not create / modify the page with JS.

You will never be able to use jquery or others...

**Comment by DanielZambranoC** [comment]
Even if its an generated chart in jquery that I want to print into the pdf?

**Comment by spipu** [comment]
No. You have to generate your chart before, and create an image
