### ISSUE TITLE
Right to left (RTL) support

### ISSUE THREAD

**Issue by matrix-amiel** [spipu/html2pdf#93]
Hi.

I’m developing for OpenEMR project. The project uses html2pdf library v.x.x.x to generate PDF from HTML.
I’m trying to fix their PDF report generation to generate right-to-left ( RTL ) documents correctly.
It seems there is a problem there.

` $pdf = new HTML2PDF ($GLOBALS['pdf_layout'],`
`      $GLOBALS['pdf_size'],`
`     $GLOBALS['pdf_language'],`
`      true, // default unicode setting is true`
`      'UTF-8', // default encoding setting is UTF-8`
      `array($GLOBALS['pdf_left_margin'],$GLOBALS['pdf_top_margin'],$GLOBALS['pdf_right_margin'],$GLOBALS['pdf_bottom_margin'])
  );`

 ` $pdf->pdf->setRTL(true);`

  `$pdf->writeHTML($content, false);`
 ` if ($PDF_OUTPUT == 1) {`
    
    $pdf->Output('report.pdf', $GLOBALS['pdf_output']); // D = Download, I = Inline
 ` }`

Do you support RTL languages?    
I don’t success to use with ‘setRTL’ method of TCPDF library.

Please let me knew about this.

Thank you.
Amiel.

**Comment by spipu** [comment]
Hi,

HTML2PDF does not support RTL for now.

**Comment by juchi** [comment]
Since #96 has been merged, can we consider this issue solved?

**Comment by matrix-amiel** [comment]
Hi,
Yes, of course.
